import type { KeycloakGroup, KeycloakRole, KeycloakUser } from "#/keycloak";

const roles: KeycloakRole[] = [
	{
		id: "role-sysadmin",
		name: "SYSADMIN",
		description: "系统管理员，负责平台全局配置",
		composite: true,
		clientRole: false,
		containerId: "realm",
		attributes: { category: "核心", dataSecurityLevel: "DATA_TOP_SECRET" },
	},
	{
		id: "role-opadmin",
		name: "OPADMIN",
		description: "业务运维管理员，负责业务平台整体运维和关联工具组件的运维",
		composite: true,
		clientRole: false,
		containerId: "realm",
		attributes: { category: "核心", dataSecurityLevel: "DATA_TOP_SECRET" },
	},
	{
		id: "role-authadmin",
		name: "AUTHADMIN",
		description: "授权管理员，审批用户与角色变更",
		composite: false,
		clientRole: false,
		containerId: "realm",
		attributes: { dataSecurityLevel: "DATA_SECRET" },
	},
	{
		id: "role-auditadmin",
		name: "AUDITADMIN",
		description: "审计管理员，巡检并导出安全日志",
		composite: false,
		clientRole: false,
		containerId: "realm",
		attributes: { dataSecurityLevel: "DATA_SECRET" },
	},
	{
		id: "role-dept-owner",
		name: "DEPT_OWNER",
		description: "部门主管，具备本部门数据治理与授权能力",
		composite: false,
		clientRole: false,
		containerId: "realm",
		attributes: { dataSecurityLevel: "DATA_SECRET" },
	},
	{
		id: "role-dept-editor",
		name: "DEPT_EDITOR",
		description: "部门数据专员，负责本部门数据维护",
		composite: false,
		clientRole: false,
		containerId: "realm",
		attributes: { dataSecurityLevel: "DATA_INTERNAL" },
	},
	{
		id: "role-dept-viewer",
		name: "DEPT_VIEWER",
		description: "数据查阅员，只能在本部门查看数据",
		composite: false,
		clientRole: false,
		containerId: "realm",
		attributes: { dataSecurityLevel: "DATA_PUBLIC" },
	},
	{
		id: "role-inst-owner",
		name: "INST_OWNER",
		description: "研究所领导，可对全院共享区数据授权",
		composite: false,
		clientRole: false,
		containerId: "realm",
		attributes: { dataSecurityLevel: "DATA_TOP_SECRET" },
	},
	{
		id: "role-inst-editor",
		name: "INST_EDITOR",
		description: "研究所数据专员，维护全院共享区数据",
		composite: false,
		clientRole: false,
		containerId: "realm",
		attributes: { dataSecurityLevel: "DATA_SECRET" },
	},
	{
		id: "role-inst-viewer",
		name: "INST_VIEWER",
		description: "研究所数据查阅员，可访问全院共享区数据",
		composite: false,
		clientRole: false,
		containerId: "realm",
		attributes: { dataSecurityLevel: "DATA_INTERNAL" },
	},
	{
		id: "role-data-steward",
		name: "DATA_STEWARD",
		description: "数据管家，维护数据资产目录",
		composite: false,
		clientRole: false,
		containerId: "realm",
		attributes: { dataSecurityLevel: "DATA_INTERNAL" },
	},
];

const users: KeycloakUser[] = [
	{
		id: "user-zhang-wei",
		username: "zhangwei",
		email: "zhang.wei@demo.cn",
		firstName: "张伟",
		enabled: true,
		attributes: {
			department: ["数据平台组"],
			position: ["平台架构师"],
			personnel_security_level: ["IMPORTANT"],
			person_security_level: ["IMPORTANT"],
			person_level: ["IMPORTANT"],
			data_levels: ["PUBLIC", "INTERNAL", "SECRET"],
		},
		groups: ["数据平台组"],
		realmRoles: ["SYSADMIN"],
		createdTimestamp: Date.parse("2024-03-15T08:00:00Z"),
	},
	{
		id: "user-li-xiaomei",
		username: "lixiaomei",
		email: "li.xiaomei@demo.cn",
		firstName: "李晓美",
		enabled: true,
		attributes: {
			department: ["市场洞察组"],
			position: ["数据分析师"],
			personnel_security_level: ["GENERAL"],
			person_security_level: ["GENERAL"],
			person_level: ["GENERAL"],
			data_levels: ["PUBLIC", "INTERNAL"],
		},
		groups: ["市场洞察组"],
		realmRoles: ["DATA_STEWARD", "DEPT_VIEWER"],
		createdTimestamp: Date.parse("2024-02-28T10:20:00Z"),
	},
	{
		id: "user-wang-hong",
		username: "wanghong",
		email: "wang.hong@demo.cn",
		firstName: "王虹",
		enabled: false,
		attributes: {
			department: ["安全审计部"],
			position: ["安全审核员"],
			personnel_security_level: ["CORE"],
			person_security_level: ["CORE"],
			person_level: ["CORE"],
			data_levels: ["PUBLIC", "INTERNAL", "SECRET", "TOP_SECRET"],
		},
		groups: ["AI创新组"],
		realmRoles: ["AUDITADMIN"],
		createdTimestamp: Date.parse("2024-01-18T06:45:00Z"),
	},
	{
		id: "user-chen-yu",
		username: "chenyu",
		email: "chen.yu@demo.cn",
		firstName: "陈宇",
		enabled: true,
		attributes: {
			department: ["数据治理小组"],
			position: ["数据治理专员"],
			personnel_security_level: ["NON_SECRET"],
			person_security_level: ["NON_SECRET"],
			person_level: ["NON_SECRET"],
			data_levels: ["PUBLIC"],
		},
		groups: ["数据治理小组"],
		realmRoles: ["DATA_STEWARD", "AUTHADMIN", "DEPT_EDITOR"],
		createdTimestamp: Date.parse("2023-12-02T04:15:00Z"),
	},
	{
		id: "user-lu-qi",
		username: "luqi",
		email: "lu.qi@demo.cn",
		firstName: "卢琦",
		enabled: true,
		attributes: {
			department: ["数据平台组"],
			position: ["部门主管"],
			personnel_security_level: ["IMPORTANT"],
			person_security_level: ["IMPORTANT"],
			person_level: ["IMPORTANT"],
			data_levels: ["PUBLIC", "INTERNAL", "SECRET"],
		},
		groups: ["数据平台组"],
		realmRoles: ["DEPT_OWNER"],
		createdTimestamp: Date.parse("2024-04-12T02:40:00Z"),
	},
	{
		id: "user-jiang-hui",
		username: "jianghui",
		email: "jiang.hui@demo.cn",
		firstName: "姜辉",
		enabled: true,
		attributes: {
			department: ["研究所共享区"],
			position: ["数据专员"],
			personnel_security_level: ["CORE"],
			person_security_level: ["CORE"],
			person_level: ["CORE"],
			data_levels: ["PUBLIC", "INTERNAL", "SECRET", "TOP_SECRET"],
		},
		groups: ["AI创新组"],
		realmRoles: ["INST_OWNER"],
		createdTimestamp: Date.parse("2024-03-02T03:30:00Z"),
	},
];

const groups: KeycloakGroup[] = [
	{
		id: "group-data-platform",
		name: "数据平台组",
		path: "/数据平台组",
		attributes: { leader: ["张伟"], orgType: ["DEPARTMENT"], orgCode: ["DPF"] },
		subGroups: [
			{
				id: "group-data-governance",
				name: "数据治理小组",
				path: "/数据平台组/数据治理小组",
				attributes: { leader: ["陈宇"], orgType: ["TEAM"], orgCode: ["DPF-GOV"] },
			},
		],
	},
	{
		id: "group-ai-innovation",
		name: "AI创新组",
		path: "/AI创新组",
		attributes: { leader: ["王强"], orgType: ["TEAM"], orgCode: ["AI-01"] },
		subGroups: [],
	},
];

const groupMembers: Record<string, string[]> = {
	"group-data-platform": ["user-zhang-wei", "user-li-xiaomei", "user-lu-qi"],
	"group-data-governance": ["user-chen-yu"],
	"group-ai-innovation": ["user-wang-hong", "user-jiang-hui"],
};

export const keycloakDb: {
	roles: KeycloakRole[];
	users: KeycloakUser[];
	groups: KeycloakGroup[];
	groupMembers: Record<string, string[]>;
} = {
	roles,
	users,
	groups,
	groupMembers,
};
