(function () {
  "use strict";

  window.DQPrototype = window.DQPrototype || {};

  var dimensions = [
    { key: "completeness", name: "完整性", passRate: 98.6, passed: 128, total: 130, templateCount: 13 },
    { key: "accuracy", name: "准确性", passRate: 97.2, passed: 104, total: 107, templateCount: 8 },
    { key: "consistency", name: "一致性", passRate: 96.9, passed: 94, total: 97, templateCount: 5 },
    { key: "timeliness", name: "时效性", passRate: 94.8, passed: 91, total: 96, templateCount: 15 },
    { key: "uniqueness", name: "唯一性", passRate: 99.1, passed: 109, total: 110, templateCount: 8 },
    { key: "validity", name: "有效性", passRate: 97.7, passed: 127, total: 130, templateCount: 29 },
  ];

  var rules = [
    {
      id: "DQR-000128",
      name: "预算执行主键非空",
      dimension: "完整性",
      severity: "强规则",
      table: "dwd_finance_budget_execution",
      dataSource: "治理演示库",
      scope: "字段级",
      target: "budget_execution_id",
      template: "字段非空校验",
      threshold: "空值率 = 0%",
      schedule: "每日 02:10",
      owner: "财务数据治理组",
      enabled: true,
      latestResult: "通过",
      passRate: 100,
      updatedAt: "2026-07-31 09:18",
      description: "保障预算执行明细的业务主键完整，可被下游模型稳定引用。",
    },
    {
      id: "DQR-000127",
      name: "项目编号标准格式",
      dimension: "有效性",
      severity: "强规则",
      table: "dwd_project_master",
      dataSource: "治理演示库",
      scope: "字段级",
      target: "project_no",
      template: "正则表达式校验",
      threshold: "不合规率 <= 0.2%",
      schedule: "每日 02:20",
      owner: "项目数据治理组",
      enabled: true,
      latestResult: "异常",
      passRate: 99.6,
      updatedAt: "2026-07-31 09:12",
      description: "校验项目编号符合统一编码规则，减少跨系统关联失败。",
    },
    {
      id: "DQR-000126",
      name: "预算金额非负",
      dimension: "准确性",
      severity: "强规则",
      table: "dwd_finance_budget_execution",
      dataSource: "治理演示库",
      scope: "字段级",
      target: "budget_amount",
      template: "数值范围校验",
      threshold: "budget_amount >= 0",
      schedule: "每日 02:10",
      owner: "财务数据治理组",
      enabled: true,
      latestResult: "通过",
      passRate: 100,
      updatedAt: "2026-07-31 09:06",
      description: "确保预算金额符合业务取值边界。",
    },
    {
      id: "DQR-000125",
      name: "项目主数据唯一",
      dimension: "唯一性",
      severity: "强规则",
      table: "dim_project",
      dataSource: "治理演示库",
      scope: "字段级",
      target: "project_no",
      template: "字段唯一性校验",
      threshold: "重复率 = 0%",
      schedule: "每日 01:40",
      owner: "项目数据治理组",
      enabled: true,
      latestResult: "通过",
      passRate: 100,
      updatedAt: "2026-07-31 08:58",
      description: "确保项目编号在有效主数据中唯一。",
    },
    {
      id: "DQR-000124",
      name: "日报分区按时产出",
      dimension: "时效性",
      severity: "弱规则",
      table: "ads_project_daily_board",
      dataSource: "分析演示库",
      scope: "表级",
      target: "业务日期分区",
      template: "分区产出时效校验",
      threshold: "08:00 前完成",
      schedule: "每日 08:05",
      owner: "分析应用治理组",
      enabled: true,
      latestResult: "异常",
      passRate: 92.9,
      updatedAt: "2026-07-31 08:31",
      description: "监测项目日报分区是否在服务窗口前完成。",
    },
    {
      id: "DQR-000123",
      name: "责任部门编码一致",
      dimension: "一致性",
      severity: "弱规则",
      table: "dwd_project_master",
      dataSource: "治理演示库",
      scope: "字段级",
      target: "department_code",
      template: "标准代码值域校验",
      threshold: "不一致率 <= 0.5%",
      schedule: "每日 02:20",
      owner: "项目数据治理组",
      enabled: true,
      latestResult: "通过",
      passRate: 99.8,
      updatedAt: "2026-07-31 08:20",
      description: "对照责任部门标准代码集检查字段取值。",
    },
    {
      id: "DQR-000122",
      name: "里程碑完成日期完整",
      dimension: "完整性",
      severity: "弱规则",
      table: "fct_project_milestone",
      dataSource: "治理演示库",
      scope: "条件字段级",
      target: "actual_finish_date",
      template: "条件非空校验",
      threshold: "完成状态下空值率 = 0%",
      schedule: "每日 03:00",
      owner: "项目数据治理组",
      enabled: false,
      latestResult: "未运行",
      passRate: null,
      updatedAt: "2026-07-30 17:46",
      description: "已完成的里程碑必须填写实际完成日期。",
    },
  ];

  var templates = [
    { id: "DQT-001", name: "字段非空校验", dimension: "完整性", scope: "字段级", dataRange: "字符、数值、日期字段", description: "统计字段空值率，并按阈值判断是否通过。", enabledRules: 18, totalRules: 21, system: true, threshold: "空值率 <= 阈值", updatedAt: "2026-07-18" },
    { id: "DQT-002", name: "表行数波动校验", dimension: "完整性", scope: "表级", dataRange: "全量表、增量分区", description: "将当前行数与历史基线对比，识别异常波动。", enabledRules: 9, totalRules: 11, system: true, threshold: "波动率在设定区间内", updatedAt: "2026-07-18" },
    { id: "DQT-003", name: "数值范围校验", dimension: "准确性", scope: "字段级", dataRange: "数值字段", description: "判断数值是否落入允许的业务区间。", enabledRules: 12, totalRules: 12, system: true, threshold: "异常率 <= 阈值", updatedAt: "2026-07-16" },
    { id: "DQT-004", name: "正则表达式校验", dimension: "有效性", scope: "字段级", dataRange: "字符字段", description: "使用正则表达式检查编码、证件或文本格式。", enabledRules: 10, totalRules: 13, system: true, threshold: "不合规率 <= 阈值", updatedAt: "2026-07-15" },
    { id: "DQT-005", name: "字段唯一性校验", dimension: "唯一性", scope: "字段级", dataRange: "主键、业务编码", description: "统计重复值占比，检查候选键的唯一性。", enabledRules: 8, totalRules: 8, system: true, threshold: "重复率 = 0%", updatedAt: "2026-07-14" },
    { id: "DQT-006", name: "标准代码值域校验", dimension: "一致性", scope: "字段级", dataRange: "已绑定标准代码的字段", description: "对照 DTS 标准代码集检查字段取值。", enabledRules: 7, totalRules: 9, system: true, threshold: "不一致率 <= 阈值", updatedAt: "2026-07-12" },
    { id: "DQT-007", name: "分区产出时效校验", dimension: "时效性", scope: "表级", dataRange: "周期分区表", description: "判断目标分区是否在承诺的服务窗口前产出。", enabledRules: 6, totalRules: 7, system: true, threshold: "完成时间 <= 截止时间", updatedAt: "2026-07-11" },
    { id: "DQT-008", name: "跨表记录数一致性", dimension: "一致性", scope: "跨表级", dataRange: "具有关联关系的两张表", description: "比较上下游或主从表记录数差异。", enabledRules: 4, totalRules: 5, system: true, threshold: "差异率 <= 阈值", updatedAt: "2026-07-09" },
    { id: "DQT-009", name: "日期逻辑校验", dimension: "准确性", scope: "多字段级", dataRange: "开始、结束日期字段", description: "检查日期字段之间的先后顺序是否符合业务逻辑。", enabledRules: 3, totalRules: 3, system: true, threshold: "异常率 <= 阈值", updatedAt: "2026-07-08" },
    { id: "DQT-C01", name: "项目状态流转校验", dimension: "有效性", scope: "多字段级", dataRange: "项目主数据", description: "检查项目状态与关键日期组合是否满足管理规则。", enabledRules: 2, totalRules: 2, system: false, threshold: "异常记录数 = 0", updatedAt: "2026-07-29" },
  ];

  var runs = [
    { id: "DQRUN-73101", ruleId: "DQR-000128", ruleName: "预算执行主键非空", dimension: "完整性", status: "通过", disposition: "无需处置", finishedAt: "2026-07-31 09:18", table: "dwd_finance_budget_execution", scope: "字段级", template: "字段非空校验", duration: "42秒", rows: "1,284,620" },
    { id: "DQRUN-73102", ruleId: "DQR-000127", ruleName: "项目编号标准格式", dimension: "有效性", status: "异常", disposition: "待确认", finishedAt: "2026-07-31 09:12", table: "dwd_project_master", scope: "字段级", template: "正则表达式校验", duration: "18秒", rows: "48,276" },
    { id: "DQRUN-73103", ruleId: "DQR-000126", ruleName: "预算金额非负", dimension: "准确性", status: "通过", disposition: "无需处置", finishedAt: "2026-07-31 09:06", table: "dwd_finance_budget_execution", scope: "字段级", template: "数值范围校验", duration: "37秒", rows: "1,284,620" },
    { id: "DQRUN-73104", ruleId: "DQR-000125", ruleName: "项目主数据唯一", dimension: "唯一性", status: "通过", disposition: "无需处置", finishedAt: "2026-07-31 08:58", table: "dim_project", scope: "字段级", template: "字段唯一性校验", duration: "11秒", rows: "12,604" },
    { id: "DQRUN-73105", ruleId: "DQR-000124", ruleName: "日报分区按时产出", dimension: "时效性", status: "异常", disposition: "处理中", finishedAt: "2026-07-31 08:31", table: "ads_project_daily_board", scope: "表级", template: "分区产出时效校验", duration: "6秒", rows: "365,290" },
    { id: "DQRUN-73096", ruleId: "DQR-000123", ruleName: "责任部门编码一致", dimension: "一致性", status: "通过", disposition: "无需处置", finishedAt: "2026-07-31 08:20", table: "dwd_project_master", scope: "字段级", template: "标准代码值域校验", duration: "16秒", rows: "48,276" },
  ];

  window.DQPrototype.data = {
    meta: {
      title: "DTS 数据质量",
      workspace: "数据治理演示空间",
      environment: "生产环境 · 演示数据",
      refreshedAt: "2026-07-31 09:30",
    },
    summary: {
      assetCount: 42,
      configuredTables: 28,
      ruleCount: 96,
      enabledRules: 83,
      checksToday: 1260,
      passRate: 97.8,
      issueCount: 18,
      strongIssues: 5,
      weakIssues: 13,
    },
    dimensions: dimensions,
    qualityDimensions: dimensions,
    trend: [
      { label: "07-25", passRate: 96.4, runs: 1088 },
      { label: "07-26", passRate: 97.1, runs: 1116 },
      { label: "07-27", passRate: 96.8, runs: 1124 },
      { label: "07-28", passRate: 98.2, runs: 1193 },
      { label: "07-29", passRate: 97.6, runs: 1218 },
      { label: "07-30", passRate: 97.4, runs: 1237 },
      { label: "07-31", passRate: 97.8, runs: 1260 },
    ],
    hourlyTrend: [
      { label: "04:00", passRate: 97.2, runs: 146 },
      { label: "05:00", passRate: 98.1, runs: 172 },
      { label: "06:00", passRate: 96.9, runs: 205 },
      { label: "07:00", passRate: 97.5, runs: 236 },
      { label: "08:00", passRate: 97.1, runs: 268 },
      { label: "09:00", passRate: 98.4, runs: 233 },
    ],
    runSummary: { passed: 1219, warning: 23, failed: 18, running: 4 },
    sources: [
      { id: "SRC-01", name: "治理演示库", type: "PostgreSQL", environment: "生产", tableCount: 31, status: "已连接" },
      { id: "SRC-02", name: "分析演示库", type: "ClickHouse", environment: "生产", tableCount: 11, status: "已连接" },
      { id: "SRC-03", name: "研发验证库", type: "MySQL", environment: "开发", tableCount: 16, status: "已连接" },
    ],
    rules: rules,
    templates: templates,
    runs: runs,
    alerts: [
      { id: "DQI-2408", title: "项目编号出现 19 条格式异常", severity: "强", status: "待确认", owner: "项目数据治理组", updatedAt: "09:12" },
      { id: "DQI-2407", title: "项目日报分区延迟 31 分钟", severity: "弱", status: "处理中", owner: "分析应用治理组", updatedAt: "08:31" },
      { id: "DQI-2398", title: "预算执行表行数较基线下降 8.4%", severity: "弱", status: "已关闭", owner: "财务数据治理组", updatedAt: "07-30 09:20" },
    ],
    reports: [
      { id: "DQREP-01", name: "数据质量周报", cycle: "每周一 09:00", subscribers: 6, status: "已启用", updatedAt: "2026-07-28", owner: "数据治理运营组", channel: "站内通知" },
      { id: "DQREP-02", name: "财务域质量月报", cycle: "每月 1 日 10:00", subscribers: 4, status: "已启用", updatedAt: "2026-07-01", owner: "财务数据治理组", channel: "邮件摘要" },
      { id: "DQREP-03", name: "项目域异常简报", cycle: "工作日 17:30", subscribers: 3, status: "草稿", updatedAt: "2026-07-30", owner: "项目数据治理组", channel: "站内通知" },
    ],
  };
})();
