package com.yuzhi.dts.metrics.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.yuzhi.dts.metrics.service.dto.MetricArtifactPreviewResult;
import com.yuzhi.dts.metrics.service.dto.MetricPackValidationResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

@Service
public class MetricArtifactGenerationService {

    private final MetricPackValidationService validationService;
    private final MetricFormulaSqlGenerator formulaSqlGenerator;
    private final ObjectMapper yamlMapper = new ObjectMapper(new YAMLFactory());

    public MetricArtifactGenerationService(
        MetricPackValidationService validationService,
        MetricFormulaSqlGenerator formulaSqlGenerator
    ) {
        this.validationService = validationService;
        this.formulaSqlGenerator = formulaSqlGenerator;
    }

    public MetricArtifactPreviewResult preview(String manifestContent) {
        MetricPackValidationResult validation = validationService.validateManifest(manifestContent);
        if (!validation.valid()) {
            return MetricArtifactPreviewResult.invalid(validation.errors(), validation.summary());
        }
        Map<String, Object> manifest;
        try {
            manifest = yamlMapper.readValue(manifestContent, new TypeReference<LinkedHashMap<String, Object>>() {});
        } catch (IOException e) {
            return MetricArtifactPreviewResult.invalid(List.of("manifest.yml is not valid YAML: " + e.getMessage()), validation.summary());
        }

        String packId = String.valueOf(manifest.get("pack_id"));
        String modelName = "dws_" + packId.replace('-', '_') + "_summary";
        String sourceModel;
        List<String> dimensions;
        List<MetricColumn> metrics;
        Map<String, String> artifacts = new LinkedHashMap<>();
        try {
            sourceModel = safeRefName(String.valueOf(manifest.getOrDefault("source_model", "replace_with_dwd_model")));
            dimensions = readDimensions(manifest.get("dimensions"));
            metrics = readMetrics(manifest.get("metrics"));
            artifacts.put("dbtModelSql", dbtModelSql(modelName, sourceModel, dimensions, metrics));
            artifacts.put("schemaYml", schemaYml(modelName, metrics));
            artifacts.put("metricDoc", metricDoc(packId, dimensions, metrics));
        } catch (IllegalArgumentException e) {
            return MetricArtifactPreviewResult.invalid(List.of(e.getMessage()), validation.summary());
        }

        List<String> warnings = new ArrayList<>();
        warnings.add("Generated artifacts are candidates only; platform/dbt release gate must review and publish them.");
        if (metrics.isEmpty()) {
            warnings.add("No inline metrics were found; generated placeholder artifact requires metric files to be imported later.");
        }
        warnings.add("Platform asset existence and permission checks must pass before preview or publish.");

        Map<String, Object> summary = new LinkedHashMap<>(validation.summary());
        summary.put("modelName", modelName);
        summary.put("sourceModel", sourceModel);
        summary.put("dimensionCount", dimensions.size());
        summary.put("metricCount", metrics.size());
        return MetricArtifactPreviewResult.valid(summary, artifacts, warnings);
    }

    private String dbtModelSql(String modelName, String sourceModel, List<String> dimensions, List<MetricColumn> metrics) {
        List<String> selectRows = new ArrayList<>();
        for (String dimension : dimensions) {
            selectRows.add("    " + dimension);
        }
        if (metrics.isEmpty()) {
            selectRows.add("    1 as metric_pack_ready");
        } else {
            for (MetricColumn metric : metrics) {
                selectRows.add("    " + metric.sql() + " as " + metric.code());
            }
        }
        StringBuilder sql = new StringBuilder();
        sql.append("{{ config(materialized='table', tags=['dts-metrics', 'metric-pack']) }}\n\n");
        sql.append("-- Candidate artifact generated by dts-metrics. Review through platform/dbt release gate before publishing.\n");
        sql.append("select\n");
        sql.append(String.join(",\n", selectRows));
        sql.append("\nfrom {{ ref('").append(sourceModel).append("') }}\n");
        if (!dimensions.isEmpty()) {
            sql.append("group by\n");
            for (int i = 0; i < dimensions.size(); i++) {
                sql.append("    ").append(dimensions.get(i));
                sql.append(i + 1 < dimensions.size() ? ",\n" : "\n");
            }
        }
        return sql.toString();
    }

    private String schemaYml(String modelName, List<MetricColumn> metrics) {
        StringBuilder yml = new StringBuilder();
        yml.append("version: 2\n\nmodels:\n");
        yml.append("  - name: ").append(modelName).append("\n");
        yml.append("    description: dts-metrics generated candidate model; publish through platform/dbt gate.\n");
        yml.append("    columns:\n");
        if (metrics.isEmpty()) {
            yml.append("      - name: metric_pack_ready\n");
            yml.append("        description: Metric pack placeholder column.\n");
        } else {
            for (MetricColumn metric : metrics) {
                yml.append("      - name: ").append(metric.code()).append("\n");
                yml.append("        description: ").append(metric.name()).append("\n");
            }
        }
        return yml.toString();
    }

    private String metricDoc(String packId, List<String> dimensions, List<MetricColumn> metrics) {
        StringBuilder doc = new StringBuilder();
        doc.append("# Metric Pack ").append(packId).append("\n\n");
        doc.append("## Dimensions\n\n");
        if (dimensions.isEmpty()) {
            doc.append("- No inline dimensions declared.\n");
        } else {
            dimensions.forEach(item -> doc.append("- ").append(item).append("\n"));
        }
        doc.append("\n## Metrics\n\n");
        if (metrics.isEmpty()) {
            doc.append("- No inline metrics declared.\n");
        } else {
            metrics.forEach(item -> doc.append("- `").append(item.code()).append("`: ").append(item.name()).append("\n"));
        }
        return doc.toString();
    }

    private List<String> readDimensions(Object raw) {
        if (!(raw instanceof List<?> list)) {
            return List.of();
        }
        List<String> dimensions = new ArrayList<>();
        for (Object item : list) {
            if (item instanceof Map<?, ?> map && map.get("field") != null) {
                dimensions.add(MetricFormulaSqlGenerator.safeIdentifier(String.valueOf(map.get("field"))));
            } else {
                dimensions.add(MetricFormulaSqlGenerator.safeIdentifier(String.valueOf(item)));
            }
        }
        return dimensions;
    }

    private List<MetricColumn> readMetrics(Object raw) {
        if (!(raw instanceof List<?> list)) {
            return List.of();
        }
        List<MetricColumn> metrics = new ArrayList<>();
        for (Object item : list) {
            if (!(item instanceof Map<?, ?> map)) {
                continue;
            }
            Object codeRaw = map.get("metric_code") != null ? map.get("metric_code") : map.get("code");
            String rawCode = String.valueOf(codeRaw == null ? "" : codeRaw).trim();
            if (!StringUtils.hasText(rawCode) || map.get("formula") == null) {
                continue;
            }
            String code = safeRefName(rawCode);
            Object nameRaw = map.get("metric_name") != null ? map.get("metric_name") : map.get("name");
            String name = String.valueOf(nameRaw == null ? code : nameRaw);
            metrics.add(new MetricColumn(code, name, formulaSqlGenerator.render(map.get("formula"))));
        }
        return metrics;
    }

    private static String safeRefName(String value) {
        String text = String.valueOf(value == null ? "" : value).trim().toLowerCase(Locale.ROOT).replace('-', '_');
        return MetricFormulaSqlGenerator.safeIdentifier(text);
    }

    private record MetricColumn(String code, String name, String sql) {}
}
