## Overlay for deployment: minimize exposed host ports and rely on Traefik

services:

  dts-admin:
    # remove host port mapping in deploy
    ports: []

  dts-platform:
    # remove host port mapping in deploy
    ports: []


  dts-admin-webapp:
    # remove host port mapping in deploy; expose via Traefik
    ports: []
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dts-core"
      - "traefik.http.routers.dts-admin-ui.rule=Host(`${HOST_ADMIN_UI}`)"
      - "traefik.http.routers.dts-admin-ui.entrypoints=websecure"
      - "traefik.http.routers.dts-admin-ui.tls=true"
      - "traefik.http.services.dts-admin-ui.loadbalancer.server.port=80"

  dts-platform-webapp:
    # remove host port mapping in deploy; expose via Traefik
    ports: []
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dts-core"
      - "traefik.http.routers.dts-platform-ui.rule=Host(`${HOST_PLATFORM_UI}`)"
      - "traefik.http.routers.dts-platform-ui.entrypoints=websecure"
      - "traefik.http.routers.dts-platform-ui.tls=true"
      - "traefik.http.services.dts-platform-ui.loadbalancer.server.port=80"
