dts:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dts-pg
      port: 5432
      user: biadmin
      password: Devops123@
      dbname: biadmin
      schema: public
      threads: 4
