-- PJM v4 MySQL test-source schema.
--
-- This is the raw source side for DTS JDBC/API ingestion. It intentionally
-- contains no `_dts_*` columns: DTS owns and appends those reserved landing
-- metadata columns.
--
-- Compatibility target: MySQL 5.7+ / 8.0+, InnoDB, utf8mb4.
-- Business dates, week numbers and amounts remain strings so both ingestion
-- paths exercise the same PostgreSQL STG parsing rules after landing.

CREATE DATABASE IF NOT EXISTS dts_pjm_test
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE dts_pjm_test;

CREATE TABLE IF NOT EXISTS ods_project_subject_domain_v2 (
  id                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classification        VARCHAR(32) NOT NULL COMMENT '数据密级：PUBLIC/INTERNAL/SECRET/CONFIDENTIAL',
  owner_dept            VARCHAR(64) NOT NULL COMMENT '所属部门编码',
  project_no            VARCHAR(128) NULL,
  subsystem             VARCHAR(255) NULL,
  node_task             TEXT NULL,
  plan_start_date       VARCHAR(64) NULL,
  plan_date             VARCHAR(64) NULL,
  plan_week             VARCHAR(64) NULL,
  deliverable           TEXT NULL,
  node_type             VARCHAR(255) NULL,
  owner                 VARCHAR(255) NULL,
  dept                  VARCHAR(255) NULL,
  dept_leader           VARCHAR(255) NULL,
  completion_status     VARCHAR(255) NULL,
  collab_dept           VARCHAR(255) NULL,
  supervisor_dept       VARCHAR(255) NULL,
  delay_expected_date   VARCHAR(64) NULL,
  incomplete_reason     TEXT NULL,
  risk_level            VARCHAR(255) NULL,
  risk_content          TEXT NULL,
  delay_impact          TEXT NULL,
  actual_start_date     VARCHAR(64) NULL,
  actual_date           VARCHAR(64) NULL,
  actual_week           VARCHAR(64) NULL,
  institute_leader      VARCHAR(255) NULL,
  `source`              VARCHAR(255) NULL,
  original_plan_date    VARCHAR(64) NULL,
  delay_days_changed    VARCHAR(64) NULL,
  delay_days_unchanged  VARCHAR(64) NULL,
  delay_applied         VARCHAR(255) NULL,
  project_manager       VARCHAR(255) NULL,
  last_update_time      VARCHAR(64) NULL,
  last_update_week      VARCHAR(64) NULL,
  filled_by             VARCHAR(255) NULL,
  highlight             TEXT NULL,
  PRIMARY KEY (id),
  KEY idx_ods_project_subject_domain_v2_project_no (project_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_progress_measure_v2 (
  id                         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classification             VARCHAR(32) NOT NULL COMMENT '数据密级：PUBLIC/INTERNAL/SECRET/CONFIDENTIAL',
  owner_dept                 VARCHAR(64) NOT NULL COMMENT '所属部门编码',
  project_no                 VARCHAR(128) NULL,
  subsystem                  VARCHAR(255) NULL,
  node_task                  TEXT NULL,
  plan_date                  VARCHAR(64) NULL,
  plan_week                  VARCHAR(64) NULL,
  completion_status          VARCHAR(255) NULL,
  measure_category           VARCHAR(255) NULL,
  measure_title              TEXT NULL,
  follow_up_person           VARCHAR(255) NULL,
  main_recipient             VARCHAR(255) NULL,
  cc_recipient               VARCHAR(255) NULL,
  follow_up_date             VARCHAR(64) NULL,
  follow_up_week             VARCHAR(64) NULL,
  closure_status             VARCHAR(255) NULL,
  final_closure_date         VARCHAR(64) NULL,
  final_closure_week         VARCHAR(64) NULL,
  closure_deliverable_type   VARCHAR(255) NULL,
  closure_deliverable        TEXT NULL,
  risk_content               TEXT NULL,
  last_update_time           VARCHAR(64) NULL,
  last_update_week           VARCHAR(64) NULL,
  remark                     TEXT NULL,
  filled_by                  VARCHAR(255) NULL,
  PRIMARY KEY (id),
  KEY idx_ods_progress_measure_v2_project_no (project_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_quality_issue_v2 (
  id                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classification        VARCHAR(32) NOT NULL COMMENT '数据密级：PUBLIC/INTERNAL/SECRET/CONFIDENTIAL',
  owner_dept            VARCHAR(64) NOT NULL COMMENT '所属部门编码',
  project_no            VARCHAR(128) NULL,
  subsystem             VARCHAR(255) NULL,
  issue_name            TEXT NULL,
  dept                  VARCHAR(255) NULL,
  team_leader           VARCHAR(255) NULL,
  dept_leader           VARCHAR(255) NULL,
  issue_date            VARCHAR(64) NULL,
  issue_week            VARCHAR(64) NULL,
  issue_summary         TEXT NULL,
  issue_category        VARCHAR(255) NULL,
  zero_plan             VARCHAR(255) NULL,
  zero_plan_synced      VARCHAR(255) NULL,
  new_plan_count        VARCHAR(64) NULL,
  `status`              VARCHAR(255) NULL,
  current_progress      TEXT NULL,
  zero_complete_date    VARCHAR(64) NULL,
  zero_complete_week    VARCHAR(64) NULL,
  last_update_time      VARCHAR(64) NULL,
  last_update_week      VARCHAR(64) NULL,
  project_manager       VARCHAR(255) NULL,
  filled_by             VARCHAR(255) NULL,
  PRIMARY KEY (id),
  KEY idx_ods_quality_issue_v2_project_no (project_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_quality_measure_v2 (
  id                         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classification             VARCHAR(32) NOT NULL COMMENT '数据密级：PUBLIC/INTERNAL/SECRET/CONFIDENTIAL',
  owner_dept                 VARCHAR(64) NOT NULL COMMENT '所属部门编码',
  project_no                 VARCHAR(128) NULL,
  subsystem                  VARCHAR(255) NULL,
  issue_name                 TEXT NULL,
  dept                       VARCHAR(255) NULL,
  team_leader                VARCHAR(255) NULL,
  dept_leader                VARCHAR(255) NULL,
  issue_date                 VARCHAR(64) NULL,
  issue_week                 VARCHAR(64) NULL,
  issue_summary              TEXT NULL,
  issue_category             VARCHAR(255) NULL,
  zero_plan                  VARCHAR(255) NULL,
  zero_plan_synced           VARCHAR(255) NULL,
  new_plan_count             VARCHAR(64) NULL,
  `status`                   VARCHAR(255) NULL,
  current_progress           TEXT NULL,
  project_manager            VARCHAR(255) NULL,
  measure_category           VARCHAR(255) NULL,
  measure_title              TEXT NULL,
  follow_up_person           VARCHAR(255) NULL,
  main_recipient             VARCHAR(255) NULL,
  cc_recipient               VARCHAR(255) NULL,
  follow_up_date             VARCHAR(64) NULL,
  follow_up_week             VARCHAR(64) NULL,
  closure_status             VARCHAR(255) NULL,
  final_closure_date         VARCHAR(64) NULL,
  final_closure_week         VARCHAR(64) NULL,
  closure_deliverable_type   VARCHAR(255) NULL,
  closure_deliverable        TEXT NULL,
  risk_content               TEXT NULL,
  last_update_time           VARCHAR(64) NULL,
  last_update_week           VARCHAR(64) NULL,
  remark                     TEXT NULL,
  filled_by                  VARCHAR(255) NULL,
  PRIMARY KEY (id),
  KEY idx_ods_quality_measure_v2_project_no (project_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_tech_state_v2 (
  id                       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classification           VARCHAR(32) NOT NULL COMMENT '数据密级：PUBLIC/INTERNAL/SECRET/CONFIDENTIAL',
  owner_dept               VARCHAR(64) NOT NULL COMMENT '所属部门编码',
  project_no               VARCHAR(128) NULL,
  tech_state_name          TEXT NULL,
  change_item              TEXT NULL,
  owner                    VARCHAR(255) NULL,
  dept                     VARCHAR(255) NULL,
  dept_leader              VARCHAR(255) NULL,
  change_submit_time       VARCHAR(64) NULL,
  change_submit_week       VARCHAR(64) NULL,
  completion_signature     VARCHAR(255) NULL,
  signature_closure_date   VARCHAR(64) NULL,
  signature_closure_week   VARCHAR(64) NULL,
  change_reason            TEXT NULL,
  change_category          VARCHAR(255) NULL,
  plan_file_closure_date   VARCHAR(64) NULL,
  plan_file_closure_week   VARCHAR(64) NULL,
  plan_reform_date         VARCHAR(64) NULL,
  plan_reform_week         VARCHAR(64) NULL,
  plan_synced              VARCHAR(255) NULL,
  new_plan_count           VARCHAR(64) NULL,
  review_situation         TEXT NULL,
  affected_files           TEXT NULL,
  affected_objects         TEXT NULL,
  file_signature_status    VARCHAR(255) NULL,
  file_signature_date      VARCHAR(64) NULL,
  file_signature_week      VARCHAR(64) NULL,
  reform_status            VARCHAR(255) NULL,
  reform_date              VARCHAR(64) NULL,
  reform_week              VARCHAR(64) NULL,
  project_manager          VARCHAR(255) NULL,
  last_update_time         VARCHAR(64) NULL,
  last_update_week         VARCHAR(64) NULL,
  filled_by                VARCHAR(255) NULL,
  remark                   TEXT NULL,
  PRIMARY KEY (id),
  KEY idx_ods_tech_state_v2_project_no (project_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_tech_state_measure_v2 (
  id                         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classification             VARCHAR(32) NOT NULL COMMENT '数据密级：PUBLIC/INTERNAL/SECRET/CONFIDENTIAL',
  owner_dept                 VARCHAR(64) NOT NULL COMMENT '所属部门编码',
  project_no                 VARCHAR(128) NULL,
  tech_state_name            TEXT NULL,
  change_item                TEXT NULL,
  owner                      VARCHAR(255) NULL,
  dept                       VARCHAR(255) NULL,
  dept_leader                VARCHAR(255) NULL,
  change_submit_time         VARCHAR(64) NULL,
  change_submit_week         VARCHAR(64) NULL,
  completion_signature       VARCHAR(255) NULL,
  signature_closure_date     VARCHAR(64) NULL,
  signature_closure_week     VARCHAR(64) NULL,
  change_reason              TEXT NULL,
  change_category            VARCHAR(255) NULL,
  plan_file_closure_date     VARCHAR(64) NULL,
  plan_file_closure_week     VARCHAR(64) NULL,
  plan_reform_date           VARCHAR(64) NULL,
  plan_reform_week           VARCHAR(64) NULL,
  plan_synced                VARCHAR(255) NULL,
  new_plan_count             VARCHAR(64) NULL,
  affected_files             TEXT NULL,
  affected_objects           TEXT NULL,
  file_signature_status      VARCHAR(255) NULL,
  reform_status              VARCHAR(255) NULL,
  project_manager            VARCHAR(255) NULL,
  measure_category           VARCHAR(255) NULL,
  measure_title              TEXT NULL,
  follow_up_person           VARCHAR(255) NULL,
  main_recipient             VARCHAR(255) NULL,
  cc_recipient               VARCHAR(255) NULL,
  follow_up_date             VARCHAR(64) NULL,
  follow_up_week             VARCHAR(64) NULL,
  closure_status             VARCHAR(255) NULL,
  final_closure_date         VARCHAR(64) NULL,
  final_closure_week         VARCHAR(64) NULL,
  closure_deliverable_type   VARCHAR(255) NULL,
  closure_deliverable        TEXT NULL,
  risk_content               TEXT NULL,
  last_update_time           VARCHAR(64) NULL,
  last_update_week           VARCHAR(64) NULL,
  remark                     TEXT NULL,
  filled_by                  VARCHAR(255) NULL,
  PRIMARY KEY (id),
  KEY idx_ods_tech_state_measure_v2_project_no (project_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_risk_info_v2 (
  id                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classification        VARCHAR(32) NOT NULL COMMENT '数据密级：PUBLIC/INTERNAL/SECRET/CONFIDENTIAL',
  owner_dept            VARCHAR(64) NOT NULL COMMENT '所属部门编码',
  project_no            VARCHAR(128) NULL,
  risk_name             TEXT NULL,
  subsystem             VARCHAR(255) NULL,
  belonging_unit        VARCHAR(255) NULL,
  risk_description      TEXT NULL,
  risk_submit_time      VARCHAR(64) NULL,
  risk_submit_week      VARCHAR(64) NULL,
  risk_phase            VARCHAR(255) NULL,
  risk_category         VARCHAR(255) NULL,
  risk_level            VARCHAR(255) NULL,
  impact_scope          TEXT NULL,
  response_measure      TEXT NULL,
  final_release_time    VARCHAR(64) NULL,
  final_release_week    VARCHAR(64) NULL,
  monthly_control_plan  TEXT NULL,
  weekly_release_plan   TEXT NULL,
  release_plan_synced   VARCHAR(255) NULL,
  new_plan_count        VARCHAR(64) NULL,
  progress_stat_time    VARCHAR(64) NULL,
  progress_stat_week    VARCHAR(64) NULL,
  progress_situation    TEXT NULL,
  response_owner        VARCHAR(255) NULL,
  control_owner         VARCHAR(255) NULL,
  dept                  VARCHAR(255) NULL,
  risk_status           VARCHAR(255) NULL,
  risk_release_date     VARCHAR(64) NULL,
  risk_release_week     VARCHAR(64) NULL,
  remark                TEXT NULL,
  last_update_time      VARCHAR(64) NULL,
  last_update_week      VARCHAR(64) NULL,
  filled_by             VARCHAR(255) NULL,
  PRIMARY KEY (id),
  KEY idx_ods_risk_info_v2_project_no (project_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_risk_measure_v2 (
  id                         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classification             VARCHAR(32) NOT NULL COMMENT '数据密级：PUBLIC/INTERNAL/SECRET/CONFIDENTIAL',
  owner_dept                 VARCHAR(64) NOT NULL COMMENT '所属部门编码',
  project_no                 VARCHAR(128) NULL,
  risk_name                  TEXT NULL,
  subsystem                  VARCHAR(255) NULL,
  belonging_unit             VARCHAR(255) NULL,
  risk_description           TEXT NULL,
  risk_submit_time           VARCHAR(64) NULL,
  risk_submit_week           VARCHAR(64) NULL,
  risk_phase                 VARCHAR(255) NULL,
  risk_category              VARCHAR(255) NULL,
  risk_level                 VARCHAR(255) NULL,
  impact_scope               TEXT NULL,
  response_measure           TEXT NULL,
  final_release_time         VARCHAR(64) NULL,
  monthly_control_plan       TEXT NULL,
  weekly_release_plan        TEXT NULL,
  release_plan_synced        VARCHAR(255) NULL,
  new_plan_count             VARCHAR(64) NULL,
  progress_stat_time         VARCHAR(64) NULL,
  progress_stat_week         VARCHAR(64) NULL,
  progress_situation         TEXT NULL,
  response_owner             VARCHAR(255) NULL,
  control_owner              VARCHAR(255) NULL,
  dept                       VARCHAR(255) NULL,
  risk_status                VARCHAR(255) NULL,
  project_manager            VARCHAR(255) NULL,
  measure_category           VARCHAR(255) NULL,
  measure_title              TEXT NULL,
  follow_up_person           VARCHAR(255) NULL,
  main_recipient             VARCHAR(255) NULL,
  cc_recipient               VARCHAR(255) NULL,
  follow_up_date             VARCHAR(64) NULL,
  follow_up_week             VARCHAR(64) NULL,
  closure_status             VARCHAR(255) NULL,
  final_closure_date         VARCHAR(64) NULL,
  final_closure_week         VARCHAR(64) NULL,
  closure_deliverable_type   VARCHAR(255) NULL,
  closure_deliverable        TEXT NULL,
  risk_content               TEXT NULL,
  last_update_time           VARCHAR(64) NULL,
  last_update_week           VARCHAR(64) NULL,
  remark                     TEXT NULL,
  filled_by                  VARCHAR(255) NULL,
  PRIMARY KEY (id),
  KEY idx_ods_risk_measure_v2_project_no (project_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_material_info_v2 (
  id                         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classification             VARCHAR(32) NOT NULL COMMENT '数据密级：PUBLIC/INTERNAL/SECRET/CONFIDENTIAL',
  owner_dept                 VARCHAR(64) NOT NULL COMMENT '所属部门编码',
  project_no                 VARCHAR(128) NULL,
  subsystem                  VARCHAR(255) NULL,
  pbs_no                     VARCHAR(128) NULL,
  pbs_name                   VARCHAR(255) NULL,
  self_or_outsource          VARCHAR(255) NULL,
  supplier_name              VARCHAR(255) NULL,
  is_long_cycle              VARCHAR(255) NULL,
  contract_negotiation_date  VARCHAR(64) NULL,
  contract_negotiation_week  VARCHAR(64) NULL,
  contract_delivery_date     VARCHAR(64) NULL,
  contract_delivery_week     VARCHAR(64) NULL,
  actual_delivery_date       VARCHAR(64) NULL,
  actual_delivery_week       VARCHAR(64) NULL,
  plan_inspect_date          VARCHAR(64) NULL,
  plan_inspect_week          VARCHAR(64) NULL,
  complete_inspect_date      VARCHAR(64) NULL,
  complete_inspect_week      VARCHAR(64) NULL,
  install_date               VARCHAR(64) NULL,
  install_week               VARCHAR(64) NULL,
  dept_owner                 VARCHAR(255) NULL,
  control_dept_owner         VARCHAR(255) NULL,
  weekly_progress            TEXT NULL,
  affects_major_node         VARCHAR(255) NULL,
  risk_level                 VARCHAR(255) NULL,
  risk_content               TEXT NULL,
  delay_impact               TEXT NULL,
  last_update_time           VARCHAR(64) NULL,
  last_update_week           VARCHAR(64) NULL,
  remark                     TEXT NULL,
  PRIMARY KEY (id),
  KEY idx_ods_material_info_v2_project_no (project_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ods_budget_v2 (
  id                       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classification           VARCHAR(32) NOT NULL COMMENT '数据密级：PUBLIC/INTERNAL/SECRET/CONFIDENTIAL',
  owner_dept               VARCHAR(64) NOT NULL COMMENT '所属部门编码',
  project_no               VARCHAR(128) NULL,
  budget_no                VARCHAR(128) NULL,
  subtopic                 TEXT NULL,
  research_lab             VARCHAR(255) NULL,
  budget_amount_adjusted   VARCHAR(64) NULL,
  prepaid_amount           VARCHAR(64) NULL,
  book_cost_amount         VARCHAR(64) NULL,
  payable_amount           VARCHAR(64) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_ods_budget_v2_budget_no (budget_no),
  KEY idx_ods_budget_v2_project_no (project_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
