import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const pageUrl = new URL("./ModelSpecDetailPage.tsx", import.meta.url);
const logicalUrl = new URL("./components/ModelSpecLogicalDesignStage.tsx", import.meta.url);
const implementationUrl = new URL("./components/ModelSpecImplementationStage.tsx", import.meta.url);
const physicalUrl = new URL("./components/ModelSpecPhysicalAssetStage.tsx", import.meta.url);
const read = (url: URL) => readFileSync(url, "utf8");

test("three-stage detail isolates logical design, canonical implementation and physical evidence", () => {
	for (const url of [pageUrl, logicalUrl, implementationUrl, physicalUrl]) assert.equal(existsSync(url), true, `${url.pathname} is missing`);
	const page = read(pageUrl);
	const logical = read(logicalUrl);
	const implementation = read(implementationUrl);
	const physical = read(physicalUrl);

	assert.doesNotMatch(page, /ModelSpecEditorFields/);
	assert.match(page, /ModelSpecLogicalDesignStage/);
	assert.match(page, /ModelSpecImplementationStage/);
	assert.match(page, /ModelSpecPhysicalAssetStage/);
	assert.match(logical, /ModelSpecFieldsTab/);
	assert.match(logical, /ModelSpecStandardsTab/);
	assert.match(logical, /ModelSpecDependencyPanel/);
	assert.match(logical, /grainStatement|grainKeysText/);
	assert.match(logical, /factShape|timeSemanticsType|dimensionRefIds/);
	assert.match(logical, /dimensionScdType/);
	assert.doesNotMatch(logical, /sourceBindingId|saveModelImplementation/);
	assert.match(implementation, /inputMode.*PHYSICAL_ASSET/s);
	assert.match(implementation, /model\.modelType === "DIMENSION"/);
	assert.match(implementation, /model\.modelType === "FACT"/);
	assert.doesNotMatch(implementation, /CONTROLLED_SEED/);
	assert.match(implementation, /name="inputIds"/);
	assert.match(implementation, /mode="multiple".*inputOptions/s);
	assert.match(implementation, /settings\.joins/);
	assert.match(implementation, /src_0、src_1/);
	assert.match(implementation, /inputIndex: index \+ 1/);
	assert.match(implementation, /input\.resolvedVersion/);
	assert.match(implementation, /input\.checksum/);
	assert.match(implementation, /generatedImplementationIdentity/);
	assert.match(implementation, /自动生成并保持稳定，无需人工维护/);
	assert.doesNotMatch(implementation, /name="projectKey"|name="dbtUniqueId"/);
	assert.match(implementation, /fieldMappings|deduplicateBy|castType|ownership/);
	assert.doesNotMatch(implementation, /Input\.TextArea|JSON\.parse/);
	assert.match(implementation, /persistedDraft/);
	assert.match(implementation, /ModelImplementationCasToken/);
	assert.match(implementation, /resolvePhysicalAssetImplementationInputs/);
	assert.match(implementation, /resolveUpstreamModelImplementationInputs/);
	assert.match(implementation, /isUpstreamModelImplementationPinned/);
	assert.match(implementation, /persistedUpstreamInputs/);
	assert.match(implementation, /incompletePersistedIds/);
	assert.match(implementation, /缺少完整实现 pin/);
	assert.match(implementation, /adoptedCurrentPinIdSet/);
	assert.match(implementation, /adoptCurrentPins/);
	assert.match(implementation, />\s*采用当前版本\s*</);
	assert.match(implementation, /已固定/);
	assert.match(implementation, /待固定/);
	assert.match(implementation, /采用当前实现 \/ 升级引用/);
	assert.match(implementation, /普通保存会原样保留 modelSpec 与 implementation 六元 pin/);
	assert.match(implementation, /修复 Landing 来源/);
	assert.match(implementation, /系统管理.*ephemeral.*无物理表/s);
	assert.match(physical, /physicalAssetRef/);
	assert.match(physical, /compile|编译/);
	assert.match(physical, /血缘时间线/);
});

test("source and physical failures stay local while conflict and readonly preserve the current stage", () => {
	const page = read(pageUrl);
	const implementation = read(implementationUrl);
	const physical = read(physicalUrl);

	assert.doesNotMatch(page, /sourceVerificationPending/);
	assert.doesNotMatch(page, /disabled=\{sourceLoading\}/);
	assert.match(page, /activeStage !== "implementation"/);
	assert.match(page, /activeStage === "physical"/);
	assert.match(page, /setPhysicalError/);
	assert.match(page, /setPhysicalTimeline\(null\)/);
	assert.match(page, /Form\.useWatch\(\[\], \{ form, preserve: true \}\)/);
	assert.match(page, /form\.resetFields\(\)/);
	assert.match(page, /implementationUpstreamOptions/);
	assert.match(implementation, /response\?\.status === 409/);
	assert.match(implementation, /MODEL_IMPLEMENTATION_REVISION_CONFLICT/);
	assert.match(implementation, /getModelLifecycle/);
	assert.match(implementation, /rebaseImplementationCas/);
	assert.match(implementation, /setImplementationCas\(latest\)/);
	assert.match(implementation, /加载最新实现并保留当前输入/);
	assert.match(implementation, /operationRequestRef/);
	assert.doesNotMatch(implementation, /changeStage\(/);
	assert.match(page, /readOnly=\{!canEdit\}/);
	assert.match(page, /retryModelReleaseRegistration/);
	assert.match(physical, /latestRelease\.status === "PARTIAL".*latestRelease\.status === "PENDING"/s);
	assert.match(page, /max-\[390px\]:grid-cols-1/);
});
