import type { ComponentCategory } from './types';

export const componentLibrary: ComponentCategory[] = [
    {
        name: '图表',
        icon: '📊',
        items: [
            {
                type: 'line-chart',
                name: '折线图',
                icon: '📈',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    title: '折线图',
                    xAxisData: ['一月', '二月', '三月', '四月', '五月', '六月'],
                    series: [
                        { name: '系列1', data: [120, 200, 150, 80, 70, 110] },
                    ],
                },
            },
            {
                type: 'bar-chart',
                name: '柱状图',
                icon: '📊',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    title: '柱状图',
                    xAxisData: ['一月', '二月', '三月', '四月', '五月', '六月'],
                    series: [
                        { name: '系列1', data: [120, 200, 150, 80, 70, 110] },
                    ],
                },
            },
            {
                type: 'pie-chart',
                name: '饼图',
                icon: '🥧',
                defaultWidth: 350,
                defaultHeight: 300,
                defaultConfig: {
                    title: '饼图',
                    data: [
                        { name: '类别A', value: 335 },
                        { name: '类别B', value: 310 },
                        { name: '类别C', value: 234 },
                        { name: '类别D', value: 135 },
                        { name: '类别E', value: 154 },
                    ],
                },
            },
            {
                type: 'gauge-chart',
                name: '仪表盘',
                icon: '🎯',
                defaultWidth: 300,
                defaultHeight: 300,
                defaultConfig: {
                    title: '完成率',
                    value: 75,
                    min: 0,
                    max: 100,
                },
            },
            {
                type: 'gantt-chart',
                name: '甘特图',
                icon: '📊',
                defaultWidth: 600,
                defaultHeight: 300,
                defaultConfig: {
                    title: '甘特图',
                    tasks: [
                        { name: '任务A', type: '一般节点', planDate: '2026-01-01', actualDate: '2026-01-15', isCompleted: true, isOverdue: false, isIncomplete: false, delayDays: 0, riskLevel: '低', owner: '张三' },
                        { name: '任务B', type: '里程碑节点', planDate: '2026-02-01', actualDate: null, isCompleted: false, isOverdue: false, isIncomplete: true, delayDays: null, riskLevel: '高', owner: '李四' },
                    ],
                },
            },
            {
                type: 'radar-chart',
                name: '雷达图',
                icon: '🕸️',
                defaultWidth: 350,
                defaultHeight: 300,
                defaultConfig: {
                    title: '雷达图',
                    indicator: [
                        { name: '销售', max: 6500 },
                        { name: '管理', max: 16000 },
                        { name: '技术', max: 30000 },
                        { name: '客服', max: 38000 },
                        { name: '研发', max: 52000 },
                    ],
                    data: [4300, 10000, 28000, 35000, 50000],
                },
            },
            {
                type: 'funnel-chart',
                name: '漏斗图',
                icon: '🔽',
                defaultWidth: 350,
                defaultHeight: 300,
                defaultConfig: {
                    title: '漏斗图',
                    data: [
                        { name: '访问', value: 100 },
                        { name: '咨询', value: 80 },
                        { name: '订单', value: 60 },
                        { name: '点击', value: 40 },
                        { name: '展现', value: 20 },
                    ],
                },
            },
            {
                type: 'scatter-chart',
                name: '散点图',
                icon: '⚫',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    title: '散点图',
                    data: [
                        [10, 8.04], [8, 6.95], [13, 7.58], [9, 8.81], [11, 8.33],
                        [14, 9.96], [6, 7.24], [4, 4.26], [12, 10.84], [7, 4.82],
                    ],
                },
            },
            {
                type: 'bar-chart',
                name: '水平条形图',
                icon: '📶',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    title: '水平条形图',
                    horizontal: true,
                    xAxisData: ['产品A', '产品B', '产品C', '产品D', '产品E'],
                    series: [
                        { name: '销量', data: [120, 200, 150, 80, 70] },
                    ],
                },
            },
            {
                type: 'bar-chart',
                name: '堆叠柱状图',
                icon: '🏗️',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    title: '堆叠柱状图',
                    stackMode: 'stack',
                    xAxisData: ['一月', '二月', '三月', '四月', '五月', '六月'],
                    series: [
                        { name: '产品A', data: [120, 200, 150, 80, 70, 110] },
                        { name: '产品B', data: [80, 120, 100, 60, 50, 90] },
                    ],
                },
            },
            {
                type: 'line-chart',
                name: '堆叠面积图',
                icon: '🏔️',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    title: '堆叠面积图',
                    stackMode: 'stack',
                    xAxisData: ['一月', '二月', '三月', '四月', '五月', '六月'],
                    series: [
                        { name: '线上', data: [120, 200, 150, 80, 70, 110] },
                        { name: '线下', data: [80, 120, 100, 60, 50, 90] },
                    ],
                },
            },
            {
                type: 'combo-chart',
                name: '组合图',
                icon: '📉',
                defaultWidth: 480,
                defaultHeight: 320,
                defaultConfig: {
                    title: '组合图',
                    xAxisData: ['一月', '二月', '三月', '四月', '五月', '六月'],
                    series: [
                        { name: '销售额', type: 'bar', yAxisIndex: 0, data: [120, 200, 150, 80, 70, 110] },
                        { name: '增长率', type: 'line', yAxisIndex: 1, data: [12, 18, 14, 8, 6, 10] },
                    ],
                    yAxis: [
                        { name: '销售额' },
                        { name: '增长率(%)' },
                    ],
                },
            },
            {
                type: 'treemap-chart',
                name: '矩形树图',
                icon: '🟩',
                defaultWidth: 420,
                defaultHeight: 320,
                defaultConfig: {
                    title: '矩形树图',
                    data: [
                        { name: '技术部', value: 40, children: [{ name: '前端', value: 18 }, { name: '后端', value: 15 }, { name: '测试', value: 7 }] },
                        { name: '产品部', value: 30, children: [{ name: '设计', value: 12 }, { name: '产品', value: 10 }, { name: '运营', value: 8 }] },
                        { name: '市场部', value: 20, children: [{ name: '品牌', value: 12 }, { name: '渠道', value: 8 }] },
                    ],
                },
            },
            {
                type: 'sunburst-chart',
                name: '旭日图',
                icon: '🌅',
                defaultWidth: 400,
                defaultHeight: 340,
                defaultConfig: {
                    title: '旭日图',
                    data: [
                        { name: '技术部', children: [{ name: '前端', value: 18 }, { name: '后端', value: 15 }, { name: '测试', value: 7 }] },
                        { name: '产品部', children: [{ name: '设计', value: 12 }, { name: '产品', value: 10 }, { name: '运营', value: 8 }] },
                        { name: '市场部', children: [{ name: '品牌', value: 12 }, { name: '渠道', value: 8 }] },
                    ],
                },
            },
            {
                type: 'wordcloud-chart',
                name: '词云图',
                icon: '☁️',
                defaultWidth: 420,
                defaultHeight: 300,
                defaultConfig: {
                    title: '词云图',
                    data: [
                        { name: '大数据', value: 100 },
                        { name: '人工智能', value: 85 },
                        { name: '云计算', value: 72 },
                        { name: '物联网', value: 65 },
                        { name: '区块链', value: 55 },
                        { name: '数字化', value: 50 },
                        { name: '智能制造', value: 45 },
                        { name: '数据治理', value: 40 },
                        { name: '可视化', value: 38 },
                        { name: '机器学习', value: 35 },
                        { name: '深度学习', value: 32 },
                        { name: '数据分析', value: 30 },
                        { name: '自然语言', value: 28 },
                        { name: '知识图谱', value: 25 },
                        { name: '边缘计算', value: 22 },
                    ],
                    shape: 'circle',
                    fontSizeRange: [14, 60],
                    rotationRange: [-45, 45],
                },
            },
            {
                type: 'waterfall-chart',
                name: '瀑布图',
                icon: '🏞️',
                defaultWidth: 480,
                defaultHeight: 320,
                defaultConfig: {
                    title: '瀑布图',
                    data: [
                        { name: '期初余额', value: 1000, isTotal: true },
                        { name: '销售收入', value: 500 },
                        { name: '服务收入', value: 200 },
                        { name: '人力成本', value: -300 },
                        { name: '运营支出', value: -150 },
                        { name: '税费', value: -80 },
                        { name: '期末余额', value: 1170, isTotal: true },
                    ],
                },
            },
            {
                type: 'map-chart',
                name: '区域地图',
                icon: '🗺️',
                defaultWidth: 520,
                defaultHeight: 320,
                defaultConfig: {
                    title: '区域分布',
                    mapScope: 'china',
                    usePresetGeoJson: true,
                    enableRegionDrill: true,
                    regionVariableKey: 'region_name',
                    regionCodeVariableKey: 'region_code',
                    regions: [
                        {
                            name: '北京市',
                            code: '110000',
                            value: 120,
                            children: [
                                { name: '东城区', code: '110101', value: 40 },
                                { name: '西城区', code: '110102', value: 25 },
                                { name: '朝阳区', code: '110105', value: 55 },
                            ],
                        },
                        {
                            name: '上海市',
                            code: '310000',
                            value: 180,
                            children: [
                                { name: '黄浦区', code: '310101', value: 70 },
                                { name: '徐汇区', code: '310104', value: 60 },
                                { name: '浦东新区', code: '310115', value: 50 },
                            ],
                        },
                        {
                            name: '广东省',
                            code: '440000',
                            value: 140,
                            children: [
                                { name: '广州市', code: '440100', value: 90 },
                                { name: '深圳市', code: '440300', value: 30 },
                                { name: '佛山市', code: '440600', value: 20 },
                            ],
                        },
                    ],
                },
            },
            {
                type: 'map-chart',
                name: '气泡地图',
                icon: '🔵',
                defaultWidth: 520,
                defaultHeight: 320,
                defaultConfig: {
                    title: '气泡地图',
                    mapScope: 'china',
                    mapMode: 'bubble',
                    usePresetGeoJson: true,
                    scatterData: [
                        { name: '北京', value: [116.46, 39.92, 260] },
                        { name: '上海', value: [121.48, 31.22, 180] },
                        { name: '广州', value: [113.23, 23.16, 140] },
                        { name: '深圳', value: [114.07, 22.62, 120] },
                        { name: '成都', value: [104.06, 30.67, 95] },
                        { name: '杭州', value: [120.19, 30.26, 88] },
                    ],
                    bubbleSizeRange: [8, 40],
                },
            },
            {
                type: 'map-chart',
                name: '流向地图',
                icon: '✈️',
                defaultWidth: 520,
                defaultHeight: 320,
                defaultConfig: {
                    title: '流向地图',
                    mapScope: 'china',
                    mapMode: 'flow',
                    usePresetGeoJson: true,
                    showFlowEffect: true,
                    flowData: [
                        { from: { name: '北京', coord: [116.46, 39.92] }, to: { name: '上海', coord: [121.48, 31.22] }, value: 100 },
                        { from: { name: '北京', coord: [116.46, 39.92] }, to: { name: '广州', coord: [113.23, 23.16] }, value: 80 },
                        { from: { name: '上海', coord: [121.48, 31.22] }, to: { name: '成都', coord: [104.06, 30.67] }, value: 60 },
                        { from: { name: '广州', coord: [113.23, 23.16] }, to: { name: '杭州', coord: [120.19, 30.26] }, value: 45 },
                    ],
                },
            },
            {
                type: 'map-chart',
                name: '热力地图',
                icon: '🔥',
                defaultWidth: 520,
                defaultHeight: 320,
                defaultConfig: {
                    title: '热力地图',
                    mapScope: 'china',
                    mapMode: 'heatmap',
                    usePresetGeoJson: true,
                    heatmapData: [
                        [116.46, 39.92, 100], [121.48, 31.22, 85], [113.23, 23.16, 72],
                        [114.07, 22.62, 68], [104.06, 30.67, 55], [120.19, 30.26, 50],
                        [108.95, 34.27, 42], [106.55, 29.56, 38], [118.78, 32.04, 35],
                        [117.00, 36.65, 30], [113.65, 34.76, 28], [114.30, 30.60, 25],
                    ],
                    heatmapRadius: 20,
                },
            },
            {
                type: 'map-chart',
                name: '散点地图',
                icon: '📍',
                defaultWidth: 520,
                defaultHeight: 320,
                defaultConfig: {
                    title: '散点地图',
                    mapScope: 'china',
                    mapMode: 'scatter',
                    usePresetGeoJson: true,
                    scatterData: [
                        { name: '北京', value: [116.46, 39.92, 1] },
                        { name: '上海', value: [121.48, 31.22, 1] },
                        { name: '广州', value: [113.23, 23.16, 1] },
                        { name: '深圳', value: [114.07, 22.62, 1] },
                        { name: '成都', value: [104.06, 30.67, 1] },
                        { name: '武汉', value: [114.30, 30.60, 1] },
                        { name: '杭州', value: [120.19, 30.26, 1] },
                        { name: '南京', value: [118.78, 32.04, 1] },
                    ],
                    bubbleSizeRange: [6, 6],
                },
            },
            {
                type: 'sankey-chart',
                name: '桑基图',
                icon: '🌊',
                defaultWidth: 520,
                defaultHeight: 360,
                defaultConfig: {
                    title: '桑基图',
                    nodes: [
                        { name: '来源A' }, { name: '来源B' }, { name: '来源C' },
                        { name: '中间1' }, { name: '中间2' },
                        { name: '目标X' }, { name: '目标Y' },
                    ],
                    links: [
                        { source: '来源A', target: '中间1', value: 30 },
                        { source: '来源A', target: '中间2', value: 20 },
                        { source: '来源B', target: '中间1', value: 25 },
                        { source: '来源C', target: '中间2', value: 35 },
                        { source: '中间1', target: '目标X', value: 40 },
                        { source: '中间1', target: '目标Y', value: 15 },
                        { source: '中间2', target: '目标X', value: 20 },
                        { source: '中间2', target: '目标Y', value: 35 },
                    ],
                },
            },
            {
                type: 'heatmap-chart',
                name: '热力图',
                icon: '🟥',
                defaultWidth: 480,
                defaultHeight: 360,
                defaultConfig: {
                    title: '热力图',
                    xAxisData: ['周一', '周二', '周三', '周四', '周五'],
                    yAxisData: ['早上', '下午', '晚上'],
                    data: [
                        [0, 0, 5], [1, 0, 7], [2, 0, 3], [3, 0, 8], [4, 0, 2],
                        [0, 1, 9], [1, 1, 4], [2, 1, 6], [3, 1, 3], [4, 1, 7],
                        [0, 2, 2], [1, 2, 8], [2, 2, 5], [3, 2, 1], [4, 2, 9],
                    ],
                },
            },
            {
                type: 'graph-chart',
                name: '关系图',
                icon: '🔗',
                defaultWidth: 480,
                defaultHeight: 400,
                defaultConfig: {
                    title: '关系图',
                    nodes: [
                        { name: '节点A', value: 10 },
                        { name: '节点B', value: 8 },
                        { name: '节点C', value: 6 },
                        { name: '节点D', value: 4 },
                    ],
                    links: [
                        { source: '节点A', target: '节点B' },
                        { source: '节点A', target: '节点C' },
                        { source: '节点B', target: '节点D' },
                        { source: '节点C', target: '节点D' },
                    ],
                },
            },
            {
                type: 'candlestick-chart',
                name: 'K线图',
                icon: '📉',
                defaultWidth: 520,
                defaultHeight: 340,
                defaultConfig: {
                    title: 'K线图',
                    xAxisData: ['2026-01', '2026-02', '2026-03', '2026-04', '2026-05', '2026-06'],
                    data: [
                        [20, 34, 10, 38],
                        [40, 35, 30, 50],
                        [31, 38, 33, 44],
                        [38, 15, 5, 42],
                        [20, 30, 18, 35],
                        [25, 42, 22, 48],
                    ],
                },
            },
            {
                type: 'boxplot-chart',
                name: '箱线图',
                icon: '📦',
                defaultWidth: 420,
                defaultHeight: 320,
                defaultConfig: {
                    title: '箱线图',
                    xAxisData: ['类别A', '类别B', '类别C'],
                    data: [
                        [850, 940, 955, 980, 1070],
                        [760, 800, 845, 885, 960],
                        [520, 600, 620, 660, 740],
                    ],
                },
            },
            {
                type: 'parallel-chart',
                name: '平行坐标',
                icon: '📐',
                defaultWidth: 520,
                defaultHeight: 340,
                defaultConfig: {
                    title: '平行坐标',
                    dimensions: ['指标A', '指标B', '指标C', '指标D'],
                    data: [
                        [1, 55, 9, 56],
                        [2, 25, 11, 21],
                        [3, 56, 7, 63],
                        [4, 33, 7, 43],
                    ],
                },
            },
            {
                type: 'calendar-chart',
                name: '日历热力图',
                icon: '📅',
                defaultWidth: 520,
                defaultHeight: 220,
                defaultConfig: {
                    title: '日历热力图',
                    range: '2026',
                    data: [
                        ['2026-01-01', 120], ['2026-02-14', 200], ['2026-03-08', 150],
                        ['2026-04-01', 80], ['2026-05-01', 260], ['2026-06-15', 180],
                    ],
                },
            },
            {
                type: 'tree-chart',
                name: '树图',
                icon: '🌳',
                defaultWidth: 480,
                defaultHeight: 400,
                defaultConfig: {
                    title: '树图',
                    data: {
                        name: '根节点',
                        children: [
                            { name: '分支A', children: [{ name: '叶子1' }, { name: '叶子2' }] },
                            { name: '分支B', children: [{ name: '叶子3' }, { name: '叶子4' }] },
                        ],
                    },
                },
            },
            {
                type: 'themeRiver-chart',
                name: '主题河流',
                icon: '🏞️',
                defaultWidth: 520,
                defaultHeight: 300,
                defaultConfig: {
                    title: '主题河流',
                    data: [
                        ['2026/01', 10, '系列A'], ['2026/02', 20, '系列A'], ['2026/03', 30, '系列A'],
                        ['2026/01', 20, '系列B'], ['2026/02', 15, '系列B'], ['2026/03', 25, '系列B'],
                        ['2026/01', 15, '系列C'], ['2026/02', 25, '系列C'], ['2026/03', 10, '系列C'],
                    ],
                },
            },
            {
                type: 'pictorialBar-chart',
                name: '象形柱图',
                icon: '🏛️',
                defaultWidth: 420,
                defaultHeight: 320,
                defaultConfig: {
                    title: '象形柱图',
                    xAxisData: ['类别A', '类别B', '类别C', '类别D'],
                    data: [120, 200, 150, 80],
                    symbol: 'roundRect',
                },
            },
        ],
    },
    {
        name: '边框',
        icon: '🔲',
        items: [
            {
                type: 'border-box',
                name: '边框1',
                icon: '🔲',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 1,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框2',
                icon: '🔳',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 2,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框3',
                icon: '🔲',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 3,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框4',
                icon: '🔳',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 4,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框5',
                icon: '🔲',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 5,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框6',
                icon: '🔳',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 6,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框7',
                icon: '🔲',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 7,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框8',
                icon: '🔳',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 8,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
        ],
    },
    {
        name: '装饰',
        icon: '✨',
        items: [
            {
                type: 'decoration',
                name: '装饰1',
                icon: '💠',
                defaultWidth: 200,
                defaultHeight: 60,
                defaultConfig: {
                    decorationType: 1,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰2',
                icon: '💎',
                defaultWidth: 200,
                defaultHeight: 60,
                defaultConfig: {
                    decorationType: 2,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰3',
                icon: '✨',
                defaultWidth: 250,
                defaultHeight: 40,
                defaultConfig: {
                    decorationType: 3,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰4',
                icon: '⭐',
                defaultWidth: 200,
                defaultHeight: 60,
                defaultConfig: {
                    decorationType: 4,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰5',
                icon: '🌟',
                defaultWidth: 300,
                defaultHeight: 50,
                defaultConfig: {
                    decorationType: 5,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰6',
                icon: '💫',
                defaultWidth: 300,
                defaultHeight: 40,
                defaultConfig: {
                    decorationType: 6,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰8',
                icon: '🔷',
                defaultWidth: 300,
                defaultHeight: 60,
                defaultConfig: {
                    decorationType: 8,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰10',
                icon: '🔶',
                defaultWidth: 200,
                defaultHeight: 60,
                defaultConfig: {
                    decorationType: 10,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
        ],
    },
    {
        name: '数据展示',
        icon: '📋',
        items: [
            {
                type: 'number-card',
                name: '指标卡',
                icon: '🔢',
                defaultWidth: 200,
                defaultHeight: 120,
                defaultConfig: {
                    title: '总销售额',
                    value: 128456,
                    prefix: '¥',
                    suffix: '',
                    precision: 0,
                },
            },
            {
                // 收编入 table 组件的 renderMode='scroll' 模式，不再暴露独立 scroll-board 入口。
                // 历史大屏中 type='scroll-board' 的组件仍然兼容渲染（ComponentRenderer/TableRenderer 保留分支）。
                type: 'table',
                name: '轮播表',
                icon: '📜',
                defaultWidth: 400,
                defaultHeight: 250,
                defaultConfig: {
                    renderMode: 'scroll',
                    header: ['列1', '列2', '列3'],
                    data: [
                        ['行1-1', '行1-2', '行1-3'],
                        ['行2-1', '行2-2', '行2-3'],
                        ['行3-1', '行3-2', '行3-3'],
                        ['行4-1', '行4-2', '行4-3'],
                        ['行5-1', '行5-2', '行5-3'],
                    ],
                    rowNum: 5,
                    headerBGC: '#00BAFF',
                    oddRowBGC: '#0A2732',
                    evenRowBGC: '#003B51',
                    waitTime: 2000,
                },
            },
            {
                type: 'table',
                name: '数据表',
                icon: '🗂️',
                defaultWidth: 480,
                defaultHeight: 280,
                defaultConfig: {
                    header: ['列1', '列2', '列3'],
                    data: [
                        ['行1-1', '行1-2', '行1-3'],
                        ['行2-1', '行2-2', '行2-3'],
                        ['行3-1', '行3-2', '行3-3'],
                    ],
                    enableSort: true,
                    enablePagination: true,
                    pageSize: 10,
                    freezeHeader: true,
                    freezeFirstColumn: false,
                    conditionalFormatting: [],
                    headerColor: '#e5e7eb',
                    headerBackground: '#64748b',
                    bodyColor: '#d1d5db',
                    bodyBackground: 'transparent',
                    borderColor: '#94a3b8',
                    fontSize: 13,
                },
            },
            {
                type: 'scroll-ranking',
                name: '排行榜',
                icon: '🏆',
                defaultWidth: 300,
                defaultHeight: 250,
                defaultConfig: {
                    data: [
                        { name: '周口', value: 55 },
                        { name: '南阳', value: 120 },
                        { name: '西峡', value: 78 },
                        { name: '驻马店', value: 66 },
                        { name: '新乡', value: 80 },
                    ],
                    rowNum: 5,
                    waitTime: 2000,
                },
            },
            {
                type: 'water-level',
                name: '水位图',
                icon: '💧',
                defaultWidth: 200,
                defaultHeight: 200,
                defaultConfig: {
                    value: 65,
                    shape: 'round',
                },
            },
            {
                type: 'digital-flop',
                name: '数字翻牌',
                icon: '🔄',
                defaultWidth: 200,
                defaultHeight: 80,
                defaultConfig: {
                    number: [100],
                    content: '{nt}',
                    style: {
                        fontSize: 30,
                        fill: '#3de7c9',
                    },
                },
            },
            {
                type: 'percent-pond',
                name: '进度池',
                icon: '📊',
                defaultWidth: 200,
                defaultHeight: 100,
                defaultConfig: {
                    value: 66,
                    borderWidth: 3,
                    borderRadius: 5,
                    colors: ['#3de7c9', '#00baff'],
                },
            },
            {
                type: 'progress-bar',
                name: '进度条',
                icon: '📏',
                defaultWidth: 300,
                defaultHeight: 40,
                defaultConfig: {
                    value: 75,
                    showLabel: true,
                },
            },
        ],
    },
    {
        name: '文本',
        icon: '📝',
        items: [
            {
                type: 'title',
                name: '标题',
                icon: '🔤',
                defaultWidth: 300,
                defaultHeight: 60,
                defaultConfig: {
                    text: '大屏标题',
                    fontSize: 32,
                    fontWeight: 'bold',
                    color: '#ffffff',
                    textAlign: 'center',
                },
            },
            {
                type: 'datetime',
                name: '日期时间',
                icon: '🕐',
                defaultWidth: 200,
                defaultHeight: 40,
                defaultConfig: {
                    format: 'YYYY-MM-DD HH:mm:ss',
                    fontSize: 16,
                    color: '#ffffff',
                },
            },
            {
                type: 'markdown-text',
                name: 'Markdown',
                icon: '📄',
                defaultWidth: 420,
                defaultHeight: 220,
                defaultConfig: {
                    markdown: '# 标题\n\n- 要点 1\n- 要点 2\n\n[查看详情](https://example.com)',
                    fontSize: 14,
                    color: '#e2e8f0',
                    lineHeight: 1.6,
                },
            },
            {
                type: 'richtext',
                name: '富文本',
                icon: '📝',
                defaultWidth: 420,
                defaultHeight: 220,
                defaultConfig: {
                    content: '<h2 style="color:#e2e8f0">标题</h2><p style="color:#94a3b8">在此编辑内容，支持<strong>粗体</strong>、<em>斜体</em>、<u>下划线</u>等格式。</p>',
                    padding: 12,
                    verticalAlign: 'top',
                    overflow: 'hidden',
                },
            },
            {
                type: 'marquee',
                name: '跑马灯',
                icon: '📢',
                defaultWidth: 420,
                defaultHeight: 56,
                defaultConfig: {
                    text: 'DTS 实时播报：数据接入稳定，任务运行正常，模型服务在线。',
                    speed: 40,
                    color: '#e2e8f0',
                    fontSize: 15,
                    backgroundColor: 'rgba(15,23,42,0.45)',
                },
            },
            {
                type: 'countdown',
                name: '倒计时',
                icon: '⏳',
                defaultWidth: 320,
                defaultHeight: 88,
                defaultConfig: {
                    title: '发布倒计时',
                    targetTime: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
                    targetVariableKey: '',
                    showDays: true,
                    color: '#e2e8f0',
                    accentColor: '#22d3ee',
                },
            },
            {
                type: 'carousel',
                name: '轮播卡片',
                icon: '🧭',
                defaultWidth: 420,
                defaultHeight: 160,
                defaultConfig: {
                    title: '业务轮播',
                    itemSourceMode: 'auto',
                    items: [
                        '设备在线率 99.2%',
                        '昨日新增告警 6 条',
                        '当日产线节拍达成 98.7%',
                    ],
                    intervalSeconds: 4,
                    autoPlay: true,
                    dataItemField: '',
                    showDots: true,
                    showControls: true,
                    pauseOnHover: true,
                    color: '#e2e8f0',
                    titleColor: '#94a3b8',
                    fontSize: 24,
                    backgroundColor: 'rgba(15,23,42,0.5)',
                },
            },
            {
                type: 'tab-switcher',
                name: 'Tab切换',
                icon: '🗂️',
                defaultWidth: 420,
                defaultHeight: 52,
                defaultConfig: {
                    label: '维度切换',
                    variableKey: 'tabKey',
                    options: [
                        { label: '总览', value: 'overview' },
                        { label: '产线', value: 'line' },
                        { label: '设备', value: 'device' },
                    ],
                    optionSourceMode: 'manual',
                    dataOptionLabelField: '',
                    dataOptionValueField: '',
                    dataOptionMax: 100,
                    defaultValue: 'overview',
                    compact: false,
                    inactiveTextColor: '#94a3b8',
                    inactiveBackgroundColor: '#0f172a',
                    activeTextColor: '#0f172a',
                    activeBackgroundColor: '#38bdf8',
                },
            },
        ],
    },
    {
        name: '企业组件',
        icon: '🏢',
        items: [
            {
                type: 'section-panel',
                name: '区域面板',
                icon: '📐',
                defaultWidth: 480,
                defaultHeight: 340,
                defaultConfig: {
                    title: '数据概览',
                    titleIcon: '',
                    titleAlign: 'left',
                    showHeader: true,
                    headerHeight: 36,
                    headerBackground: 'transparent',
                    borderStyle: 'solid',
                    borderColor: ['rgba(148, 163, 184, 0.2)'],
                    borderWidth: 1,
                    borderRadius: 12,
                    backgroundColor: 'rgba(30, 41, 59, 0.85)',
                    backdropBlur: 0,
                    shadow: 'subtle',
                    padding: 16,
                },
            },
            {
                type: 'section-panel',
                name: '渐变边框面板',
                icon: '🔲',
                defaultWidth: 480,
                defaultHeight: 340,
                defaultConfig: {
                    title: '趋势分析',
                    titleIcon: '📈',
                    titleAlign: 'left',
                    showHeader: true,
                    headerHeight: 36,
                    headerBackground: 'transparent',
                    borderStyle: 'gradient',
                    borderColor: ['#3b82f6', '#06b6d4'],
                    borderWidth: 1,
                    borderRadius: 12,
                    backgroundColor: 'rgba(30, 41, 59, 0.85)',
                    backdropBlur: 4,
                    shadow: 'medium',
                    padding: 16,
                },
            },
            {
                type: 'section-panel',
                name: '发光面板',
                icon: '✨',
                defaultWidth: 480,
                defaultHeight: 340,
                defaultConfig: {
                    title: '核心指标',
                    titleIcon: '🎯',
                    titleAlign: 'left',
                    showHeader: true,
                    headerHeight: 36,
                    headerBackground: 'transparent',
                    borderStyle: 'glow',
                    borderColor: ['#3b82f6'],
                    borderWidth: 1,
                    borderRadius: 12,
                    backgroundColor: 'rgba(15, 23, 42, 0.9)',
                    backdropBlur: 8,
                    shadow: 'strong',
                    padding: 16,
                },
            },
            {
                type: 'stat-card',
                name: '统计卡片',
                icon: '📊',
                defaultWidth: 240,
                defaultHeight: 100,
                defaultConfig: {
                    title: '总访问量',
                    value: '128,430',
                    suffix: '次',
                    trend: 'up',
                    trendValue: '+12.5%',
                    icon: '📈',
                    accentColor: '#3b82f6',
                    showAccentBar: true,
                    borderRadius: 10,
                    shadow: 'subtle',
                },
            },
            {
                type: 'stat-card',
                name: '成功指标卡',
                icon: '✅',
                defaultWidth: 240,
                defaultHeight: 100,
                defaultConfig: {
                    title: '完成率',
                    value: '96.8',
                    suffix: '%',
                    trend: 'up',
                    trendValue: '+3.2%',
                    icon: '✅',
                    accentColor: '#059669',
                    showAccentBar: true,
                    borderRadius: 10,
                    shadow: 'subtle',
                },
            },
            {
                type: 'stat-card',
                name: '预警指标卡',
                icon: '⚠️',
                defaultWidth: 240,
                defaultHeight: 100,
                defaultConfig: {
                    title: '超期任务',
                    value: '7',
                    suffix: '项',
                    trend: 'down',
                    trendValue: '-2',
                    icon: '⚠️',
                    accentColor: '#dc2626',
                    showAccentBar: true,
                    borderRadius: 10,
                    shadow: 'subtle',
                },
            },
            {
                type: 'divider',
                name: '水平分隔线',
                icon: '━',
                defaultWidth: 400,
                defaultHeight: 20,
                defaultConfig: {
                    direction: 'horizontal',
                    lineStyle: 'solid',
                    lineColor: 'rgba(148, 163, 184, 0.3)',
                    lineWidth: 1,
                },
            },
            {
                type: 'divider',
                name: '渐变分隔线',
                icon: '🌈',
                defaultWidth: 400,
                defaultHeight: 20,
                defaultConfig: {
                    direction: 'horizontal',
                    lineStyle: 'gradient',
                    lineColor: 'rgba(148, 163, 184, 0.3)',
                    lineWidth: 2,
                    gradientColors: ['transparent', '#3b82f6', 'transparent'],
                },
            },
            {
                type: 'divider',
                name: '垂直分隔线',
                icon: '┃',
                defaultWidth: 20,
                defaultHeight: 300,
                defaultConfig: {
                    direction: 'vertical',
                    lineStyle: 'solid',
                    lineColor: 'rgba(148, 163, 184, 0.3)',
                    lineWidth: 1,
                },
            },
        ],
    },
    {
        name: '形状容器',
        icon: '⬛',
        items: [
            {
                type: 'shape',
                name: '基础形状',
                icon: '🔷',
                defaultWidth: 240,
                defaultHeight: 140,
                defaultConfig: {
                    shapeType: 'rect',
                    fillColor: 'rgba(59, 130, 246, 0.2)',
                    borderColor: '#60a5fa',
                    borderWidth: 2,
                    radius: 8,
                },
            },
            {
                type: 'container',
                name: '容器框',
                icon: '🗂️',
                defaultWidth: 520,
                defaultHeight: 320,
                defaultConfig: {
                    title: '业务容器',
                    backgroundColor: 'rgba(15, 23, 42, 0.35)',
                    borderColor: 'rgba(148, 163, 184, 0.35)',
                    borderWidth: 1,
                    radius: 10,
                    titleColor: '#e2e8f0',
                    padding: 12,
                },
            },
        ],
    },
    {
        name: '筛选器',
        icon: '🎛️',
        items: [
            {
                type: 'filter-input',
                name: '输入筛选',
                icon: '⌨️',
                defaultWidth: 260,
                defaultHeight: 54,
                defaultConfig: {
                    label: '关键词',
                    variableKey: 'keyword',
                    placeholder: '请输入关键词',
                    debounceMs: 300,
                },
            },
            {
                type: 'filter-select',
                name: '下拉筛选',
                icon: '🔽',
                defaultWidth: 260,
                defaultHeight: 54,
                defaultConfig: {
                    label: '地区',
                    variableKey: 'region',
                    options: ['华北', '华东', '华南'],
                    optionSourceMode: 'manual',
                    dataOptionLabelField: '',
                    dataOptionValueField: '',
                    dataOptionMax: 200,
                    placeholder: '请选择地区',
                },
            },
            {
                type: 'filter-date-range',
                name: '日期筛选',
                icon: '📅',
                defaultWidth: 320,
                defaultHeight: 72,
                defaultConfig: {
                    label: '日期区间',
                    startKey: 'startDate',
                    endKey: 'endDate',
                },
            },
        ],
    },
    {
        name: '媒体',
        icon: '🖼️',
        items: [
            {
                type: 'image',
                name: '图片',
                icon: '🖼️',
                defaultWidth: 300,
                defaultHeight: 200,
                defaultConfig: {
                    src: '',
                    fit: 'cover',
                },
            },
            {
                type: 'video',
                name: '视频',
                icon: '🎬',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    src: '',
                    autoplay: true,
                    loop: true,
                    muted: true,
                },
            },
            {
                type: 'iframe',
                name: 'iframe',
                icon: '🌐',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    src: '',
                },
            },
        ],
    },
    {
        name: '3D 可视化',
        icon: '🌐',
        items: [
            {
                type: 'globe-chart',
                name: '3D 地球',
                icon: '🌍',
                defaultWidth: 600,
                defaultHeight: 600,
                defaultConfig: {
                    baseTexture: 'earth-blue',
                    autoRotate: true,
                    rotateSpeed: 2,
                    scatterData: [],
                    flowData: [],
                },
            },
            {
                type: 'bar3d-chart',
                name: '3D 柱状图',
                icon: '📊',
                defaultWidth: 500,
                defaultHeight: 400,
                defaultConfig: {
                    xAxisData: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                    yAxisData: ['A', 'B', 'C'],
                    data: [[0, 0, 5], [1, 0, 3], [2, 0, 8], [0, 1, 4], [1, 1, 6]],
                    colorRange: ['#3b82f6', '#ef4444'],
                    viewAngle: 25,
                },
            },
            {
                type: 'scatter3d-chart',
                name: '3D 散点图',
                icon: '🫧',
                defaultWidth: 500,
                defaultHeight: 400,
                defaultConfig: {
                    data: [[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 4, 6], [3, 6, 9]],
                    pointSize: 8,
                    colorField: 'z',
                    colorRange: ['#3b82f6', '#ef4444'],
                },
            },
        ],
    },
];

