import assert from 'node:assert/strict';
import test from 'node:test';
import { getTemplateById } from './screenTemplates';

test('project management command center template registers five-page Java-backed demo screen', () => {
    const template = getTemplateById('project-management-command-center');

    assert.ok(template);
    assert.equal(template?.id, 'project-management-command-center');
    assert.equal(template?.name, '项目运营管理大屏');
    assert.equal(template?.config.name, '项目运营管理大屏');
    assert.equal(template?.config.width, 1920);
    assert.equal(template?.config.height, 1080);
    assert.equal(template?.config.theme, 'glacier');
    assert.equal(template?.config.backgroundColor, '#eef5fb');
    assert.equal(template?.config.pages?.length, 5);
    assert.equal(template?.config.carouselConfig?.enabled, true);
    assert.equal(template?.config.carouselConfig?.autoPlay, false);
    assert.deepEqual(
        (template?.config.globalVariables ?? []).map((item) => item.key),
        ['majorProjectId', 'dateFrom', 'dateTo', 'deptId', 'riskLevel'],
    );

    const overviewPage = template?.config.pages?.[0];
    const executionPage = template?.config.pages?.[1];
    const riskPage = template?.config.pages?.[2];
    const treePage = template?.config.pages?.[3];
    const comparePage = template?.config.pages?.[4];

    assert.ok(overviewPage);
    assert.ok(executionPage);
    assert.ok(riskPage);
    assert.ok(treePage);
    assert.ok(comparePage);

    const overviewCard = overviewPage?.components.find((item) => item.id === 'pmcc-ov-kpi-total');
    const overviewPanel = overviewPage?.components.find((item) => item.id === 'pmcc-overview-bg-top');
    const overviewFilter = overviewPage?.components.find((item) => item.id === 'pmcc-major-0');
    const overviewChart = overviewPage?.components.find((item) => item.id === 'pmcc-overview-weekly');
    const overviewRanking = overviewPage?.components.find((item) => item.id === 'pmcc-overview-ranking');
    const overviewCompletionRing = overviewPage?.components.find((item) => item.id === 'pmcc-overview-completion-ring');
    const overviewRateKpi = overviewPage?.components.find((item) => item.id === 'pmcc-ov-kpi-rate');
    const overviewOnTimeKpi = overviewPage?.components.find((item) => item.id === 'pmcc-ov-kpi-ontime');
    const overviewOverdueKpi = overviewPage?.components.find((item) => item.id === 'pmcc-ov-kpi-overdue');
    const overviewMilestoneKpi = overviewPage?.components.find((item) => item.id === 'pmcc-ov-kpi-milestone-rate');
    const overviewRadar = overviewPage?.components.find((item) => item.id === 'pmcc-overview-health-radar');
    const overviewSpotlight = overviewPage?.components.find((item) => item.id === 'pmcc-overview-spotlight');
    const overviewTable = overviewPage?.components.find((item) => item.id === 'pmcc-overview-alerts');
    const executionCard = executionPage?.components.find((item) => item.id === 'pmcc-ex-kpi-high');
    const executionMajorKpi = executionPage?.components.find((item) => item.id === 'pmcc-ex-kpi-major');
    const executionImportantKpi = executionPage?.components.find((item) => item.id === 'pmcc-ex-kpi-important');
    const executionMilestoneOnTimeKpi = executionPage?.components.find((item) => item.id === 'pmcc-ex-kpi-ms-ontime');
    const executionMilestoneOverdueKpi = executionPage?.components.find((item) => item.id === 'pmcc-ex-kpi-ms-overdue');
    const executionPendingKpi = executionPage?.components.find((item) => item.id === 'pmcc-ex-kpi-ms-pending');
    const executionMilestoneRateKpi = executionPage?.components.find((item) => item.id === 'pmcc-ex-kpi-ms-rate');
    const executionGantt = executionPage?.components.find((item) => item.id === 'pmcc-execution-gantt');
    const executionWorkload = executionPage?.components.find((item) => item.id === 'pmcc-execution-workload');
    const executionMilestoneRing = executionPage?.components.find((item) => item.id === 'pmcc-execution-milestone-ring');
    const executionStage = executionPage?.components.find((item) => item.id === 'pmcc-execution-stage');
    const executionSummaryCard = executionPage?.components.find((item) => item.id === 'pmcc-execution-summary-overdue');
    const executionSummaryTotal = executionPage?.components.find((item) => item.id === 'pmcc-execution-summary-total');
    const executionDueList = executionPage?.components.find((item) => item.id === 'pmcc-execution-due-list');
    const executionMilestones = executionPage?.components.find((item) => item.id === 'pmcc-execution-milestones');
    const riskCard = riskPage?.components.find((item) => item.id === 'pmcc-rk-kpi-abnormal');
    const riskChangedKpi = riskPage?.components.find((item) => item.id === 'pmcc-rk-kpi-chg');
    const riskOverdueRateKpi = riskPage?.components.find((item) => item.id === 'pmcc-rk-kpi-ovrate');
    const riskBreakdown = riskPage?.components.find((item) => item.id === 'pmcc-risk-breakdown');
    const riskReasons = riskPage?.components.find((item) => item.id === 'pmcc-risk-reasons');
    const riskWeekly = riskPage?.components.find((item) => item.id === 'pmcc-risk-weekly');
    const riskGovernHigh = riskPage?.components.find((item) => item.id === 'pmcc-risk-govern-highrisk');
    const riskGovernChanged = riskPage?.components.find((item) => item.id === 'pmcc-risk-govern-changed');
    const riskMatrix = riskPage?.components.find((item) => item.id === 'pmcc-risk-matrix');
    const riskDelayedProjects = riskPage?.components.find((item) => item.id === 'pmcc-risk-delayed-projects');
    const treeSummaryCard = treePage?.components.find((item) => item.id === 'pmcc-tree-summary-total');
    const treeSummaryHealth = treePage?.components.find((item) => item.id === 'pmcc-tree-summary-health');
    const treeProjectsTable = treePage?.components.find((item) => item.id === 'pmcc-tree-projects');
    const treeSubprojectsTable = treePage?.components.find((item) => item.id === 'pmcc-tree-subprojects');
    const treeNodesTable = treePage?.components.find((item) => item.id === 'pmcc-tree-focus-nodes');
    const compareCard = comparePage?.components.find((item) => item.id === 'pmcc-cmp-summary-total');
    const compareTable = comparePage?.components.find((item) => item.id === 'pmcc-cmp-dim1-table');
    const mismatchTable = comparePage?.components.find((item) => item.id === 'pmcc-cmp-mismatch-top');
    const overviewRadarFieldMapping = overviewRadar?.config._fieldMapping as
        | {
              dimension?: string;
              measures?: string[];
          }
        | undefined;
    const overviewChartSeries = overviewChart?.config.series as Array<{ field?: string }> | undefined;

    assert.equal(overviewPage?.backgroundColor, '#eef5fb');
    assert.equal(overviewPanel?.config.fillColor, 'rgba(255, 255, 255, 0.94)');
    assert.equal(overviewPanel?.config.borderColor, 'rgba(148, 163, 184, 0.24)');
    assert.equal(overviewFilter?.config.inputBackground, 'rgba(255, 255, 255, 0.96)');
    assert.equal(overviewFilter?.config.inputBorderColor, 'rgba(148, 163, 184, 0.42)');
    assert.equal(overviewFilter?.config.inputTextColor, '#16324f');
    assert.equal(overviewCard?.config.backgroundColor, '#ffffff');
    assert.equal(overviewCard?.config.titleColor, '#5b7088');
    assert.equal(overviewCard?.config.valueColor, '#16324f');
    assert.deepEqual(overviewChartSeries?.map((item) => item.field), ['completionRate', 'delayedNodes', 'highRiskNodes']);
    assert.deepEqual(overviewChart?.config.seriesColors, ['#3b82f6', '#38bdf8', '#f4b740']);
    assert.equal(overviewTable?.config.headerBackground, 'rgba(219, 234, 254, 0.96)');
    assert.equal(overviewTable?.config.bodyColor, '#35526b');

    assert.equal(overviewCard?.dataSource?.type, 'api');
    assert.equal(overviewCard?.dataSource?.apiConfig?.url, '/analytics/api/project-cockpit/screen/overview');
    assert.equal(overviewCard?.dataSource?.apiConfig?.responsePath, 'kpis.0');
    assert.equal(overviewCard?.dataSource?.apiConfig?.params?.majorProjectId, '{{majorProjectId}}');
    assert.equal(overviewFilter?.dataSource?.apiConfig?.params?.majorProjectId, '{{majorProjectId}}');
    assert.equal(overviewCard?.actions?.[0]?.type, 'jump-url');
    assert.equal(overviewCard?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=overview&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=completion');
    assert.equal(overviewChart?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=overview&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=completion');
    assert.equal(overviewRanking?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=tree&majorProjectId={{data.majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}');
    assert.equal(overviewCompletionRing?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=overview&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=completion');
    assert.equal(overviewRateKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=overview&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=completion');
    assert.equal(overviewOnTimeKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=overview&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=completion');
    assert.equal(overviewOverdueKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=overview&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=completion');
    assert.equal(overviewMilestoneKpi?.dataSource?.apiConfig?.url, '/analytics/api/project-cockpit/screen/execution');
    assert.equal(overviewMilestoneKpi?.dataSource?.apiConfig?.responsePath, 'milestoneKpis.3');
    assert.equal(overviewMilestoneKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=milestone');
    assert.equal(overviewRadar?.dataSource?.apiConfig?.responsePath, 'healthRadar');
    assert.equal(overviewRadarFieldMapping?.dimension, 'name');
    assert.deepEqual(overviewRadarFieldMapping?.measures, ['score']);
    assert.equal(overviewRadar?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=overview&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=completion');
    assert.equal(overviewSpotlight?.dataSource?.apiConfig?.responsePath, 'spotlight');
    assert.equal(overviewTable?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=overview&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=overdue');

    assert.equal(executionCard?.dataSource?.apiConfig?.url, '/analytics/api/project-cockpit/screen/execution');
    assert.equal(executionCard?.dataSource?.apiConfig?.responsePath, 'incompleteKpis.0');
    assert.equal(executionCard?.actions?.[0]?.type, 'jump-url');
    assert.equal(executionCard?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=high-risk');
    assert.equal(executionMajorKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=overdue');
    assert.equal(executionImportantKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=overdue');
    assert.equal(executionMilestoneOnTimeKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=milestone');
    assert.equal(executionMilestoneOverdueKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=milestone');
    assert.equal(executionPendingKpi?.dataSource?.apiConfig?.responsePath, 'milestoneKpis.2');
    assert.equal(executionPendingKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=milestone');
    assert.equal(executionMilestoneRateKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=milestone');
    assert.equal(executionGantt?.config.renderMode, 'board');
    assert.equal(executionGantt?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{data.majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{data.dept}}&riskLevel={{riskLevel}}&drillTarget=overdue');
    assert.equal(executionWorkload?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{name}}&riskLevel={{riskLevel}}&drillTarget=overdue');
    assert.equal(executionMilestoneRing?.dataSource?.apiConfig?.responsePath, 'milestoneBreakdown');
    assert.equal(executionMilestoneRing?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=milestone');
    assert.equal(executionStage?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}');
    assert.equal(executionSummaryCard?.dataSource?.apiConfig?.responsePath, 'executionSummary');
    assert.equal(executionSummaryCard?.config.valueField, 'overdueCount');
    assert.equal(executionSummaryCard?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=overdue');
    assert.equal(executionSummaryTotal?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}');
    assert.equal(executionDueList?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{dept}}&riskLevel={{riskLevel}}&drillTarget=overdue');
    assert.equal(executionMilestones?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=execution&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=milestone');

    assert.equal(riskCard?.dataSource?.apiConfig?.url, '/analytics/api/project-cockpit/screen/risk');
    assert.equal(riskCard?.dataSource?.apiConfig?.responsePath, 'changeKpis.0');
    assert.equal(riskCard?.actions?.[0]?.type, 'jump-url');
    assert.equal(riskCard?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=overdue');
    assert.equal(riskChangedKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}');
    assert.equal(riskOverdueRateKpi?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=overdue');
    assert.equal(riskBreakdown?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{name}}');
    assert.equal(riskReasons?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=delay-reason&drillReason={{name}}');
    assert.equal(riskWeekly?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=overdue');
    assert.equal(riskGovernHigh?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}&drillTarget=high-risk');
    assert.equal(riskGovernChanged?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}');
    assert.equal(riskMatrix?.dataSource?.apiConfig?.responsePath, 'delayReasonMatrix');
    assert.equal(riskMatrix?.config.renderMode, 'delay-reason-matrix');
    assert.deepEqual(riskMatrix?.config.fields, ['dept', 'technical', 'quality', 'change', 'coordination', 'supplier', 'test', 'archive', 'normal', 'total']);
    assert.equal(riskMatrix?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{dept}}&riskLevel={{riskLevel}}&drillTarget=delay-reason&drillDept={{dept}}&drillReason={{reason}}');
    assert.equal(riskDelayedProjects?.dataSource?.apiConfig?.responsePath, 'delayedProjects');
    assert.deepEqual(riskDelayedProjects?.config.fields, ['majorProjectName', 'subprojectName', 'nodeTask', 'riskLevel', 'delayDays', 'reason', 'dept']);
    assert.equal(riskDelayedProjects?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{dept}}&riskLevel={{riskLevel}}&drillTarget=delay-reason&drillReason={{reason}}');

    assert.equal(treePage?.name, '项目树与重点项目');
    assert.equal(treeSummaryCard?.dataSource?.apiConfig?.url, '/analytics/api/project-cockpit/screen/tree');
    assert.equal(treeSummaryCard?.dataSource?.apiConfig?.responsePath, 'summary');
    assert.equal(treeSummaryCard?.config.valueField, 'totalNodes');
    assert.equal(treeSummaryCard?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=tree&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}');
    assert.equal(treeSummaryHealth?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=tree&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}');
    assert.equal(treeProjectsTable?.dataSource?.apiConfig?.responsePath, 'focusProjects');
    assert.deepEqual(treeProjectsTable?.config.fields, ['name', 'progressRate', 'highRiskCount', 'delayDays', 'status']);
    assert.equal(treeProjectsTable?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=tree&majorProjectId={{id}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}');
    assert.equal(treeSubprojectsTable?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=tree&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{deptId}}&riskLevel={{riskLevel}}');
    assert.equal(treeNodesTable?.dataSource?.apiConfig?.responsePath, 'focusNodes');
    assert.equal(treeNodesTable?.actions?.[0]?.jumpUrlTemplate, '/analytics/project-cockpit?theme=risk&majorProjectId={{majorProjectId}}&dateFrom={{dateFrom}}&dateTo={{dateTo}}&deptId={{ownerDept}}&riskLevel={{riskLevel}}&drillTarget=delay-reason&drillReason={{reason}}');

    assert.equal(comparePage?.name, '指标对账');
    assert.equal(compareCard?.dataSource?.apiConfig?.url, '/analytics/api/project-cockpit/screen/metrics-compare');
    assert.equal(compareCard?.dataSource?.apiConfig?.responsePath, 'summary');
    assert.equal(compareCard?.config.valueField, 'metricTotal');
    assert.equal(compareTable?.dataSource?.apiConfig?.responsePath, 'groups.0.items');
    assert.deepEqual(compareTable?.config.fields, ['label', 'systemValue', 'excelValue', 'diffValue', 'diffRate', 'status']);
    assert.equal(mismatchTable?.dataSource?.apiConfig?.responsePath, 'mismatchTop');
    assert.deepEqual(mismatchTable?.config.fields, ['label', 'dimension', 'diffValue', 'diffRate', 'status']);
    assert.equal(template?.config.pages?.some((item) => item.name === '指标全览'), false);
    assert.equal(getTemplateById('project-management-cockpit'), undefined);
});
