package com.yuzhi.dts.platform.service.modeling;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;

import com.yuzhi.dts.platform.repository.modeling.ModelingSqlModelRepository;
import com.yuzhi.dts.platform.repository.service.InfraDataSourceRepository;
import com.yuzhi.dts.platform.service.etl.DbtConfigService;
import com.yuzhi.dts.platform.service.infra.AdminInfraClient;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class ModelFileServiceTest {

    @Mock
    private DbtConfigService dbtConfigService;

    @Mock
    private ModelingSqlModelRepository repo;

    @Mock
    private InfraDataSourceRepository dataSourceRepository;

    @Mock
    private AdminInfraClient adminInfraClient;

    @InjectMocks
    private ModelFileService service;

    @TempDir
    Path tempDir;

    @Test
    void deleteFileIfChangedShouldRemoveSqlCsvAndAutoGeneratedYamlOnly() throws Exception {
        when(dbtConfigService.resolveProjectDir()).thenReturn(tempDir.toString());

        Path sqlFile = tempDir.resolve("models/dwd/dwd_patent.sql");
        Path csvFile = tempDir.resolve("models/dwd/dwd_patent.csv");
        Path autoYmlFile = tempDir.resolve("models/dwd/dwd_patent.yml");
        Path manualYmlFile = tempDir.resolve("models/dwd/dwd_patent_manual.yml");
        Files.createDirectories(sqlFile.getParent());
        Files.writeString(sqlFile, "select 1\n", StandardCharsets.UTF_8);
        Files.writeString(csvFile, "id,name\n1,patent\n", StandardCharsets.UTF_8);
        Files.writeString(autoYmlFile, "# generated by dts-platform auto quality\nversion: 2\n", StandardCharsets.UTF_8);
        Files.writeString(manualYmlFile, "version: 2\nmodels: []\n", StandardCharsets.UTF_8);

        service.deleteFileIfChanged("models/dwd/dwd_patent.sql", null);

        assertThat(sqlFile).doesNotExist();
        assertThat(csvFile).doesNotExist();
        assertThat(autoYmlFile).doesNotExist();
        assertThat(manualYmlFile).exists();
    }

    @Test
    void copyWorkspaceCompanionFilesShouldDeleteLegacyPmOdsSourcesWhenPmSourcesIsImported() throws Exception {
        when(dbtConfigService.resolveProjectDir()).thenReturn(tempDir.toString());

        Path legacySource = tempDir.resolve("models/pm_ods_sources.yml");
        Files.createDirectories(legacySource.getParent());
        Files.writeString(
            legacySource,
            """
            version: 2
            sources:
              - name: "pm_ods"
            """,
            StandardCharsets.UTF_8
        );

        Path unzipRoot = tempDir.resolve("incoming");
        Path incomingSource = unzipRoot.resolve("models/pm_sources.yml");
        Files.createDirectories(incomingSource.getParent());
        Files.writeString(
            incomingSource,
            """
            version: 2
            sources:
              - name: "pm_ods"
                schema: "public"
                tables: []
            """,
            StandardCharsets.UTF_8
        );

        service.copyWorkspaceCompanionFiles(unzipRoot);

        assertThat(tempDir.resolve("models/pm_sources.yml")).exists();
        assertThat(legacySource).doesNotExist();
    }
}
