package com.yuzhi.dts.platform.service.modeling;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;

import com.yuzhi.dts.platform.domain.modeling.ModelingSqlModel;
import com.yuzhi.dts.platform.repository.modeling.ModelLifecycleRepository;
import com.yuzhi.dts.platform.repository.modeling.ModelingSqlModelRepository;
import com.yuzhi.dts.platform.repository.service.InfraDataSourceRepository;
import com.yuzhi.dts.platform.service.etl.DbtConfigService;
import com.yuzhi.dts.platform.service.infra.AdminInfraClient;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class ModelFileServiceTest {

    @Mock
    private DbtConfigService dbtConfigService;

    @Mock
    private ModelingSqlModelRepository repo;

    @Mock
    private InfraDataSourceRepository dataSourceRepository;

    @Mock
    private AdminInfraClient adminInfraClient;

    @Mock
    private ModelLifecycleRepository lifecycleRepository;

    @InjectMocks
    private ModelFileService service;

    @TempDir
    Path tempDir;

    @Test
    void boundAdvancedSqlFileCarriesCurrentImplementationPinAfterUserConfig() {
        java.util.UUID modelSpecId = java.util.UUID.fromString("30000000-0000-0000-0000-000000000001");
        java.util.UUID planId = java.util.UUID.fromString("10000000-0000-0000-0000-000000000001");
        ModelingSqlModel model = new ModelingSqlModel();
        model.setModelSpecId(modelSpecId);
        model.setPlanId(planId);
        model.setOwnerDept("tenant-a");
        model.setSqlText("{{ config(materialized='view') }}\nselect 1");
        when(lifecycleRepository.findImplementation("tenant-a", modelSpecId)).thenReturn(
            java.util.Optional.of(
                new ModelLifecycleContract.ImplementationView(
                    java.util.UUID.randomUUID(),
                    modelSpecId,
                    planId,
                    7,
                    "model-v7",
                    ModelSpecContract.ImplementationMode.DBT_MANAGED,
                    "dts",
                    "model.dts.orders",
                    "ACTIVE",
                    3,
                    "implementation-v3",
                    ModelLifecycleContract.InputMode.GENERATED,
                    java.util.List.of(new ModelLifecycleContract.GeneratedInput("SQL_WORKSPACE", java.util.Map.of())),
                    java.util.List.of(),
                    java.util.Map.of(),
                    "table"
                )
            )
        );

        String sql = service.buildSqlContent(model, null);

        assertThat(sql)
            .startsWith("{{ config(materialized='view') }}")
            .contains("'tenantId':'tenant-a'")
            .contains("'modelSpecId':'" + modelSpecId + "'")
            .contains("'revision':7")
            .contains("'implementationRevision':3")
            .contains("'implementationChecksum':'implementation-v3'")
            .contains("'projectKey':'dts'");
        assertThat(sql.lastIndexOf("'modelSpecId'")).isGreaterThan(sql.indexOf("select 1"));
    }

    @Test
    void deleteFileIfChangedShouldRemoveSqlCsvAndAutoGeneratedYamlOnly() throws Exception {
        when(dbtConfigService.resolveProjectDir()).thenReturn(tempDir.toString());

        Path sqlFile = tempDir.resolve("models/dwd/dwd_patent.sql");
        Path csvFile = tempDir.resolve("models/dwd/dwd_patent.csv");
        Path autoYmlFile = tempDir.resolve("models/dwd/dwd_patent.yml");
        Path manualYmlFile = tempDir.resolve("models/dwd/dwd_patent_manual.yml");
        Files.createDirectories(sqlFile.getParent());
        Files.writeString(sqlFile, "select 1\n", StandardCharsets.UTF_8);
        Files.writeString(csvFile, "id,name\n1,patent\n", StandardCharsets.UTF_8);
        Files.writeString(autoYmlFile, "# generated by dts-platform auto quality\nversion: 2\n", StandardCharsets.UTF_8);
        Files.writeString(manualYmlFile, "version: 2\nmodels: []\n", StandardCharsets.UTF_8);

        service.deleteFileIfChanged("models/dwd/dwd_patent.sql", null);

        assertThat(sqlFile).doesNotExist();
        assertThat(csvFile).doesNotExist();
        assertThat(autoYmlFile).doesNotExist();
        assertThat(manualYmlFile).exists();
    }

    @Test
    void copyWorkspaceCompanionFilesShouldDeleteLegacyPmOdsSourcesWhenPmSourcesIsImported() throws Exception {
        when(dbtConfigService.resolveProjectDir()).thenReturn(tempDir.toString());

        Path legacySource = tempDir.resolve("models/pm_ods_sources.yml");
        Files.createDirectories(legacySource.getParent());
        Files.writeString(
            legacySource,
            """
            version: 2
            sources:
              - name: "pm_ods"
            """,
            StandardCharsets.UTF_8
        );

        Path unzipRoot = tempDir.resolve("incoming");
        Path incomingSource = unzipRoot.resolve("models/pm_sources.yml");
        Files.createDirectories(incomingSource.getParent());
        Files.writeString(
            incomingSource,
            """
            version: 2
            sources:
              - name: "pm_ods"
                schema: "public"
                tables: []
            """,
            StandardCharsets.UTF_8
        );

        service.copyWorkspaceCompanionFiles(unzipRoot);

        assertThat(tempDir.resolve("models/pm_sources.yml")).exists();
        assertThat(legacySource).doesNotExist();
    }
}
