-- 报花业务单头明细
select
    cast(s.id as bigint) as order_id,
    cast(s.tenant_id as bigint) as tenant_id,
    cast(s.project_id as bigint) as project_id,
    cast(s.project_name as text) as project_name,
    cast(s.code as text) as order_code,
    cast(s.biz_type as integer) as order_type,
    cast(s.status as integer) as order_status,
    cast(s.apply_use_id as bigint) as apply_use_id,
    cast(s.apply_use_name as text) as apply_use_name,
    cast(s.apply_time as timestamp) as apply_time,
    cast(s.finish_time as timestamp) as finish_time,
    cast(s.curing_user_id as bigint) as curing_user_id,
    cast(s.curing_user_name as text) as curing_user_name,
    cast(s.biz_total_rent as numeric) as rent_change_amount,
    cast(s.biz_total_cost as numeric) as order_cost_amount,
    cast(s.total_amount as numeric) as sale_order_amount,
    cast(s.labor_cost as numeric) as labor_cost,
    cast(s.cleaning_fee as numeric) as cleaning_fee,
    cast(s.total_extra_cost as numeric) as total_extra_cost,
    cast(s.total_extra_price as numeric) as total_extra_price,
    cast(s.del_flag as text) as del_flag,
    cast(p.customer_id as bigint) as customer_id,
    cast(coalesce(s.start_lease_time, s.apply_time) as timestamp) as business_time,
    cast(coalesce(s.del_flag = '0' and s.status in (1,2,3,4,5), false) as boolean) as is_effective,
    cast(coalesce(s.del_flag = '0' and s.status = 5, false) as boolean) as is_finished,
    cast(s._dts_source_system as text) as dts_source_system,
    cast(s._dts_source_table as text) as dts_source_table,
    cast(s._dts_import_time as timestamp) as dts_import_time,
    cast(s._dts_batch_id as text) as dts_batch_id,
    cast(s._dts_execution_id as text) as dts_execution_id,
    cast(s._dts_task_id as text) as dts_task_id
from {{ source('public', 'ods_prst_flower_biz_info') }} s
left join {{ ref('prs_v2_dwd_project') }} p on s.project_id = p.project_id
