-- 月度结算单明细
select
    cast(s.id as bigint) as settlement_id,
    cast(s.project_id as bigint) as project_id,
    cast(s.project_name as text) as project_name,
    cast(s.contract_id as bigint) as contract_id,
    cast(s.department_id as bigint) as department_id,
    cast(s.settlement_year as integer) as settlement_year,
    cast(s.settlement_month as integer) as settlement_month,
    cast(s.year_and_month as text) as year_and_month,
    cast(s.status as integer) as settlement_status,
    cast(s.rent_type as integer) as rent_type,
    cast(s.start_time as timestamp) as start_time,
    cast(s.end_time as timestamp) as end_time,
    cast(s.receivable_total_amount as numeric) as receivable_before_discount,
    cast(s.folding_after_total_amount as numeric) as discounted_receivable,
    cast(s.net_receipt_total_amount as numeric) as current_rent_amount,
    cast(s.total_amount as numeric) as ledger_received_amount,
    cast(s.period_receivable_total_amount as numeric) as opening_receivable,
    cast(s.add_receivable_total_amount as numeric) as add_receivable,
    cast(s.cut_receivable_total_amount as numeric) as cut_receivable,
    cast(s.adjust_receivable_total_amount as numeric) as adjust_receivable,
    cast(s.sale_receipt_total_amount as numeric) as sale_bill_amount,
    cast(s.update_time as timestamp) as update_time,
    cast(p.tenant_id as bigint) as tenant_id,
    cast(p.customer_id as bigint) as customer_id,
    cast(case when s.settlement_year between 1900 and 9999 and s.settlement_month between 1 and 12 then make_date(s.settlement_year, s.settlement_month, 1) when trim(s.year_and_month) ~ '^[12][0-9]{3}-?(0[1-9]|1[0-2])$' then make_date(cast(substring(replace(trim(s.year_and_month), '-', ''), 1, 4) as integer), cast(substring(replace(trim(s.year_and_month), '-', ''), 5, 2) as integer), 1) else null end as date) as finance_month,
    cast(coalesce(s.status in (2,3,4,5), false) as boolean) as is_confirmed,
    cast(s._dts_source_system as text) as dts_source_system,
    cast(s._dts_source_table as text) as dts_source_table,
    cast(s._dts_import_time as timestamp) as dts_import_time,
    cast(s._dts_batch_id as text) as dts_batch_id,
    cast(s._dts_execution_id as text) as dts_execution_id,
    cast(s._dts_task_id as text) as dts_task_id
from {{ source('public', 'ods_prsa_month_accounting') }} s
left join {{ ref('prs_v2_dwd_project') }} p on s.project_id = p.project_id
