{{ config(materialized='view', tags=['project-management-v3', 'stg', 'risk-measure']) }}

SELECT
  o.id::bigint AS source_row_id,
  'ods_risk_measure_v2'::text AS source_table,
  COALESCE({{ nullif_placeholder("o._dts_source_system") }}, 'excel') AS source_system,
  o._dts_import_time AS imported_at,

  {{ nullif_placeholder("o.project_no") }} AS project_no,
  {{ nullif_placeholder("o.risk_name") }} AS risk_name,
  {{ nullif_placeholder("o.subsystem") }} AS subsystem,
  {{ nullif_placeholder("o.belonging_unit") }} AS belonging_unit,
  {{ nullif_placeholder("o.risk_description") }} AS risk_description,
  {{ nullif_placeholder("o.risk_phase") }} AS risk_phase,
  {{ nullif_placeholder("o.risk_category") }} AS risk_category,
  {{ nullif_placeholder("o.risk_level") }} AS risk_level,
  {{ nullif_placeholder("o.impact_scope") }} AS impact_scope,
  {{ nullif_placeholder("o.response_measure") }} AS response_measure,
  {{ nullif_placeholder("o.monthly_control_plan") }} AS monthly_control_plan,
  {{ nullif_placeholder("o.weekly_release_plan") }} AS weekly_release_plan,
  {{ nullif_placeholder("o.release_plan_synced") }} AS release_plan_synced,
  {{ parse_numeric_safe("o.new_plan_count") }}::int AS new_plan_count,
  {{ nullif_placeholder("o.progress_situation") }} AS progress_situation,
  {{ nullif_placeholder("o.response_owner") }} AS response_owner,
  {{ nullif_placeholder("o.control_owner") }} AS control_owner,
  {{ nullif_placeholder("o.dept") }} AS dept,
  {{ nullif_placeholder("o.risk_status") }} AS risk_status,
  {{ nullif_placeholder("o.project_manager") }} AS project_manager,
  {{ nullif_placeholder("o.measure_category") }} AS measure_category,
  {{ nullif_placeholder("o.measure_title") }} AS measure_title,
  {{ nullif_placeholder("o.follow_up_person") }} AS follow_up_person,
  {{ nullif_placeholder("o.main_recipient") }} AS main_recipient,
  {{ nullif_placeholder("o.cc_recipient") }} AS cc_recipient,
  {{ nullif_placeholder("o.closure_status") }} AS closure_status,
  {{ nullif_placeholder("o.closure_deliverable_type") }} AS closure_deliverable_type,
  {{ nullif_placeholder("o.closure_deliverable") }} AS closure_deliverable,
  {{ nullif_placeholder("o.risk_content") }} AS risk_content,
  {{ nullif_placeholder("o.remark") }} AS remark,
  {{ nullif_placeholder("o.filled_by") }} AS filled_by,

  {{ parse_date_safe("o.risk_submit_time") }} AS risk_submit_date,
  {{ parse_date_safe("o.final_release_time") }} AS final_release_date,
  {{ parse_date_safe("o.progress_stat_time") }} AS progress_stat_date,
  {{ parse_date_safe("o.follow_up_date") }} AS follow_up_date,
  {{ parse_date_safe("o.final_closure_date") }} AS final_closure_date,
  {{ parse_date_safe("o.last_update_time") }} AS last_update_time,
  {{ parse_numeric_safe("o.risk_submit_week") }}::int AS risk_submit_week,
  {{ parse_numeric_safe("o.progress_stat_week") }}::int AS progress_stat_week,
  {{ parse_numeric_safe("o.follow_up_week") }}::int AS follow_up_week,
  {{ parse_numeric_safe("o.final_closure_week") }}::int AS final_closure_week,
  {{ parse_numeric_safe("o.last_update_week") }}::int AS last_update_week
FROM {{ source('pm_ods_v2', 'risk_measure_v2') }} o
