# Minimal dynamic config to satisfy --providers.file.filename
# Keep lightweight; service-specific routers/middlewares are defined via labels.

http:
  middlewares:
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        frameDeny: false

tls:
  certificates:
    - certFile: /certs/server.crt
      keyFile: /certs/server.key
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
  stores:
    default:
      defaultCertificate:
        certFile: /certs/server.crt
        keyFile: /certs/server.key
