# Minimal dynamic config to satisfy --providers.file.filename
# Keep lightweight; service-specific routers/middlewares are defined via labels.

http:
  middlewares:
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        frameDeny: false
    # CORS middleware for APIs (auto-match any origin; rely on same-origin routing for safety)
    cors-allow:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "PATCH"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "*"
        addVaryHeader: true
        accessControlAllowCredentials: true
        # Auto-match any origin (works with allowCredentials=true since Traefik reflects the matched origin)
        accessControlAllowOriginListRegex:
          - "https?://.*"
        accessControlMaxAge: 86400

tls:
  certificates:
    - certFile: /certs/server.crt
      keyFile: /certs/server.key
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
  stores:
    default:
      defaultCertificate:
        certFile: /certs/server.crt
        keyFile: /certs/server.key
