package com.yuzhi.dts.platform.service.catalog;

import static org.assertj.core.api.Assertions.assertThat;

import com.yuzhi.dts.platform.domain.catalog.CatalogClassificationSnapshot;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
class CatalogGrantClassificationProjectionPostgresIT {

    @Container
    private static final PostgreSQLContainer<?> POSTGRES =
        new PostgreSQLContainer<>("postgres:17.6")
            .withDatabaseName("catalog_grant_projection_it")
            .withUsername("catalog_grant_projection_test")
            .withPassword("catalog_grant_projection_test");

    private JdbcTemplate jdbcTemplate;
    private CatalogGrantClassificationProjection projection;

    @BeforeEach
    void createSchema() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
            POSTGRES.getJdbcUrl(),
            POSTGRES.getUsername(),
            POSTGRES.getPassword()
        );
        jdbcTemplate = new JdbcTemplate(dataSource);
        projection = new CatalogGrantClassificationProjection(new NamedParameterJdbcTemplate(dataSource));

        jdbcTemplate.execute("drop table if exists catalog_lifecycle_event");
        jdbcTemplate.execute("drop table if exists asset_grant");
        jdbcTemplate.execute("drop table if exists catalog_dataset_grant");
        jdbcTemplate.execute("drop table if exists catalog_dataset");
        jdbcTemplate.execute(
            """
            create table catalog_dataset (
                id uuid primary key,
                source_id uuid,
                hive_database varchar(128),
                hive_table varchar(128),
                name varchar(128) not null
            )
            """
        );
        jdbcTemplate.execute(
            """
            create table catalog_dataset_grant (
                id uuid primary key,
                dataset_id uuid not null,
                valid_to timestamp,
                last_modified_by varchar(50),
                last_modified_date timestamp
            )
            """
        );
        jdbcTemplate.execute(
            """
            create table asset_grant (
                id bigint generated by default as identity primary key,
                asset_type varchar(32),
                asset_id varchar(64),
                valid_to timestamp,
                last_modified_by varchar(50),
                last_modified_date timestamp
            )
            """
        );
        jdbcTemplate.execute(
            """
            create table catalog_lifecycle_event (
                id uuid primary key,
                dataset_id uuid not null,
                stage varchar(32),
                event_type varchar(64),
                status varchar(32),
                request_source varchar(64),
                request_ref varchar(512),
                seal_id uuid,
                seal_version bigint,
                effective_level varchar(32),
                evidence_json jsonb,
                actor varchar(50),
                occurred_at timestamp,
                created_by varchar(50),
                created_date timestamp
            )
            """
        );
    }

    @Test
    void projectExpiresActiveGrantsUsingPostgresTimestampParameters() {
        UUID sourceId = UUID.randomUUID();
        UUID datasetId = UUID.randomUUID();
        jdbcTemplate.update(
            "insert into catalog_dataset (id, source_id, hive_database, hive_table, name) values (?, ?, ?, ?, ?)",
            datasetId,
            sourceId,
            "dts_pjm_test",
            "ods_budget_v2",
            "ods_budget_v2"
        );
        jdbcTemplate.update(
            "insert into catalog_dataset_grant (id, dataset_id) values (?, ?)",
            UUID.randomUUID(),
            datasetId
        );

        CatalogClassificationSnapshot snapshot = new CatalogClassificationSnapshot();
        snapshot.setId(UUID.randomUUID());
        snapshot.setSubjectType("ASSET");
        snapshot.setSubjectKey(
            "source:" + sourceId + "/schema:dts_pjm_test/table:ods_budget_v2"
        );
        snapshot.setAssetType("DATASET");
        snapshot.setEffectiveLevel("CONFIDENTIAL");
        snapshot.setRecordVersion(1L);

        projection.project(snapshot);

        assertThat(
            jdbcTemplate.queryForObject(
                "select valid_to is not null from catalog_dataset_grant where dataset_id=?",
                Boolean.class,
                datasetId
            )
        ).isTrue();
        assertThat(
            jdbcTemplate.queryForObject(
                "select count(*) from catalog_lifecycle_event where dataset_id=? and event_type='AUTHORIZATION_SUSPENDED'",
                Integer.class,
                datasetId
            )
        ).isEqualTo(1);
    }
}
