package com.yuzhi.dts.platform.service.modeling;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.yuzhi.dts.common.audit.AuditStage;
import com.yuzhi.dts.platform.domain.catalog.CatalogColumnSchema;
import com.yuzhi.dts.platform.domain.catalog.CatalogDataset;
import com.yuzhi.dts.platform.domain.catalog.CatalogTableSchema;
import com.yuzhi.dts.platform.domain.explore.QueryDatasetAsset;
import com.yuzhi.dts.platform.domain.infra.InfraOdsTableMapping;
import com.yuzhi.dts.platform.domain.modeling.ModelingPlan;
import com.yuzhi.dts.platform.domain.modeling.ModelingSqlModel;
import com.yuzhi.dts.platform.domain.service.InfraDataSource;
import com.yuzhi.dts.platform.repository.catalog.CatalogColumnSchemaRepository;
import com.yuzhi.dts.platform.repository.catalog.CatalogDatasetRepository;
import com.yuzhi.dts.platform.repository.catalog.CatalogTableSchemaRepository;
import com.yuzhi.dts.platform.repository.explore.QueryDatasetAssetRepository;
import com.yuzhi.dts.platform.repository.infra.InfraOdsTableMappingRepository;
import com.yuzhi.dts.platform.repository.modeling.ModelingPlanRepository;
import com.yuzhi.dts.platform.repository.modeling.ModelingSqlModelRepository;
import com.yuzhi.dts.platform.repository.service.InfraDataSourceRepository;
import com.yuzhi.dts.platform.repository.visualization.BiReportLinkRepository;
import com.yuzhi.dts.platform.security.DepartmentUtils;
import com.yuzhi.dts.platform.service.audit.AuditService;
import com.yuzhi.dts.platform.service.catalog.CatalogColumnSyncService;
import com.yuzhi.dts.platform.service.catalog.CatalogColumnSyncService.ColumnSpec;
import com.yuzhi.dts.platform.service.etl.DbtConfigService;
import com.yuzhi.dts.platform.service.security.OrganizationVisibilityService;
import jakarta.persistence.EntityNotFoundException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.nio.file.FileVisitOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.Comparator;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

@Service
@Transactional
public class ModelingSqlModelService {

    private static final Logger LOG = LoggerFactory.getLogger(ModelingSqlModelService.class);
    private static final Pattern MODEL_NAME_PATTERN = Pattern.compile("^[A-Za-z][A-Za-z0-9_]*$");
    private static final Pattern NON_SAFE = Pattern.compile("[^a-z0-9_]+");
    private static final Pattern DBT_TAGS_CONFIG_PATTERN = Pattern.compile("tags\\s*=\\s*\\[(.*?)]", Pattern.CASE_INSENSITIVE | Pattern.DOTALL);
    private static final Pattern DBT_TAG_LITERAL_PATTERN = Pattern.compile("['\\\"]([^'\\\"]+)['\\\"]");
    private static final String STATUS_ACTIVE = "ACTIVE";
    private static final String BIADMIN_NAME = "数仓 (biadmin)";
    private static final String AUTO_QUALITY_MARKER = "generated by dts-platform auto quality";

    private final ModelingSqlModelRepository repo;
    private final ModelingPlanRepository planRepo;
    private final InfraOdsTableMappingRepository odsTableMappingRepository;
    private final InfraDataSourceRepository dataSourceRepository;
    private final OrganizationVisibilityService organizationVisibilityService;
    private final DataStandardSecurity security;
    private final DbtConfigService dbtConfigService;
    private final CatalogDatasetRepository datasetRepository;
    private final CatalogTableSchemaRepository tableRepository;
    private final CatalogColumnSchemaRepository columnRepository;
    private final QueryDatasetAssetRepository queryDatasetAssetRepository;
    private final BiReportLinkRepository biReportLinkRepository;
    private final CatalogColumnSyncService columnSyncService;
    private final AuditService auditService;
    private final ObjectMapper objectMapper;

    public ModelingSqlModelService(
        ModelingSqlModelRepository repo,
        ModelingPlanRepository planRepo,
        InfraOdsTableMappingRepository odsTableMappingRepository,
        InfraDataSourceRepository dataSourceRepository,
        OrganizationVisibilityService organizationVisibilityService,
        DataStandardSecurity security,
        DbtConfigService dbtConfigService,
        CatalogDatasetRepository datasetRepository,
        CatalogTableSchemaRepository tableRepository,
        CatalogColumnSchemaRepository columnRepository,
        QueryDatasetAssetRepository queryDatasetAssetRepository,
        BiReportLinkRepository biReportLinkRepository,
        CatalogColumnSyncService columnSyncService,
        AuditService auditService,
        ObjectMapper objectMapper
    ) {
        this.repo = repo;
        this.planRepo = planRepo;
        this.odsTableMappingRepository = odsTableMappingRepository;
        this.dataSourceRepository = dataSourceRepository;
        this.organizationVisibilityService = organizationVisibilityService;
        this.security = security;
        this.dbtConfigService = dbtConfigService;
        this.datasetRepository = datasetRepository;
        this.tableRepository = tableRepository;
        this.columnRepository = columnRepository;
        this.queryDatasetAssetRepository = queryDatasetAssetRepository;
        this.biReportLinkRepository = biReportLinkRepository;
        this.columnSyncService = columnSyncService;
        this.auditService = auditService;
        this.objectMapper = objectMapper;
    }

    public List<SqlModelDto> list(UUID planId, String keyword, String activeDeptHeader) {
        syncWorkspaceModels(activeDeptHeader);
        String activeDept = security.resolveActiveDept(activeDeptHeader);
        boolean instituteScope = security.hasInstituteScope();
        List<ModelingSqlModel> models = planId == null ? repo.findAll() : repo.findByPlanId(planId);
        String kw = trimToNull(keyword);
        List<SqlModelDto> result = new ArrayList<>();
        for (ModelingSqlModel model : models) {
            if (!isOwnerDeptVisible(model != null ? model.getOwnerDept() : null, activeDept, instituteScope)) {
                continue;
            }
            if (kw != null && !matchKeyword(model, kw)) {
                continue;
            }
            result.add(toDto(model));
        }
        result.sort((a, b) -> String.valueOf(a.name()).compareToIgnoreCase(String.valueOf(b.name())));
        return result;
    }

    public SqlModelDto get(UUID id, String activeDeptHeader) {
        String activeDept = security.resolveActiveDept(activeDeptHeader);
        boolean instituteScope = security.hasInstituteScope();
        ModelingSqlModel model = repo.findById(id).orElseThrow(() -> new EntityNotFoundException("模型不存在"));
        if (!isOwnerDeptVisible(model.getOwnerDept(), activeDept, instituteScope)) {
            throw new IllegalArgumentException("当前账号无权访问该模型");
        }
        return toDto(model);
    }

    public SqlModelContractImpact getContractImpact(UUID id, String activeDeptHeader) {
        String activeDept = security.resolveActiveDept(activeDeptHeader);
        boolean instituteScope = security.hasInstituteScope();
        ModelingSqlModel model = repo.findById(id).orElseThrow(() -> new EntityNotFoundException("模型不存在"));
        if (!isOwnerDeptVisible(model.getOwnerDept(), activeDept, instituteScope)) {
            throw new IllegalArgumentException("当前账号无权访问该模型");
        }
        ContractMeta meta = extractContractMeta(model.getSemanticContract());
        int fieldCount = listColumns(id, activeDeptHeader).size();
        List<QueryDatasetAsset> allDatasets = queryDatasetAssetRepository.findByEnabledTrueOrderByLastModifiedDateDesc();
        List<QueryDatasetImpactItem> impactedDatasets = new ArrayList<>();
        Set<UUID> impactedDatasetIds = new LinkedHashSet<>();
        for (QueryDatasetAsset dataset : allDatasets) {
            if (dataset == null || dataset.getId() == null) {
                continue;
            }
            if (!referencesModel(dataset.getSqlText(), model.getName(), model.getAlias())) {
                continue;
            }
            impactedDatasetIds.add(dataset.getId());
            impactedDatasets.add(
                new QueryDatasetImpactItem(
                    dataset.getId(),
                    trimToNull(dataset.getName()),
                    trimToNull(dataset.getStatus()),
                    dataset.getPublishedVersion()
                )
            );
        }
        impactedDatasets.sort(
            Comparator.comparing(
                item -> defaultText(trimToNull(item.name()), item.id() != null ? item.id().toString() : ""),
                String.CASE_INSENSITIVE_ORDER
            )
        );

        List<ReportImpactItem> impactedReports = biReportLinkRepository
            .findAll()
            .stream()
            .filter(report -> report != null && report.getId() != null && report.getQueryDatasetId() != null)
            .filter(report -> impactedDatasetIds.contains(report.getQueryDatasetId()))
            .map(
                report ->
                    new ReportImpactItem(
                        report.getId(),
                        trimToNull(report.getTitle()),
                        trimToNull(report.getCode()),
                        report.getQueryDatasetId(),
                        report.isEnabled()
                    )
            )
            .sorted(
                Comparator.comparing(
                    item -> defaultText(trimToNull(item.title()), item.id() != null ? item.id().toString() : ""),
                    String.CASE_INSENSITIVE_ORDER
                )
            )
            .toList();

        return new SqlModelContractImpact(
            model.getId(),
            model.getName(),
            model.getContractVersion(),
            model.getContractUpdatedAt(),
            meta.metricCount(),
            meta.dimensionCount(),
            fieldCount,
            impactedDatasets.size(),
            impactedReports.size(),
            impactedDatasets,
            impactedReports
        );
    }

    public List<Map<String, Object>> listColumns(UUID id, String activeDeptHeader) {
        String activeDept = security.resolveActiveDept(activeDeptHeader);
        boolean instituteScope = security.hasInstituteScope();
        ModelingSqlModel model = repo.findById(id).orElseThrow(() -> new EntityNotFoundException("模型不存在"));
        if (!isOwnerDeptVisible(model.getOwnerDept(), activeDept, instituteScope)) {
            throw new IllegalArgumentException("当前账号无权访问该模型");
        }

        DbtConfigService.DbtConfigView view = dbtConfigService.loadConfig();
        String tableName = resolveModelTable(model);
        String schemaName = resolveModelSchema(model, view);
        if (StringUtils.hasText(tableName) && StringUtils.hasText(schemaName)) {
            CatalogDataset dataset = datasetRepository
                .findFirstByHiveDatabaseIgnoreCaseAndHiveTableIgnoreCase(schemaName, tableName)
                .orElse(null);
            if (dataset != null) {
                CatalogTableSchema table = tableRepository
                    .findFirstByDatasetAndNameIgnoreCase(dataset, tableName)
                    .orElse(null);
                if (table != null) {
                    List<CatalogColumnSchema> columns = columnRepository.findByTable(table);
                    return columns
                        .stream()
                        .map(this::toColumnPayload)
                        .toList();
                }
            }
        }

        String projectDir = view != null && view.config() != null ? view.config().projectDir() : null;
        List<ColumnSpec> specs = resolveCsvSpecs(model, projectDir);
        if (specs.isEmpty()) {
            return List.of();
        }
        List<Map<String, Object>> payload = new ArrayList<>();
        for (ColumnSpec spec : specs) {
            if (spec == null) {
                continue;
            }
            Map<String, Object> item = new LinkedHashMap<>();
            item.put("name", spec.name());
            item.put("dataType", spec.dataType());
            item.put("comment", spec.comment());
            item.put("status", CatalogColumnSyncService.STATUS_DRAFT);
            payload.add(item);
        }
        return payload;
    }

    public SqlModelDto create(SqlModelRequest request, String activeDeptHeader) {
        ensureWorkspaceWritable();
        ModelingSqlModel model = new ModelingSqlModel();
        apply(model, request, activeDeptHeader, true);
        ModelingSqlModel saved = repo.save(model);
        writeModelFile(saved);
        syncDraftColumns(saved);
        return toDto(saved);
    }

    public SqlModelDto importFromFiles(SqlModelRequest request, String sqlText, String csvText, String activeDeptHeader) {
        if (!StringUtils.hasText(sqlText)) {
            throw new IllegalArgumentException("SQL 内容不能为空");
        }
        SqlModelRequest normalized = new SqlModelRequest(
            request.planId(),
            request.name(),
            request.alias(),
            request.layer(),
            request.sourceDataSourceId(),
            request.schemaName(),
            request.materialized(),
            request.tags(),
            request.description(),
            sqlText,
            request.enabled(),
            request.status(),
            request.ownerDept(),
            request.semanticContract()
        );
        SqlModelDto dto = create(normalized, activeDeptHeader);
        if (StringUtils.hasText(csvText)) {
            writeCsvSidecar(dto.modelPath(), csvText);
            ModelingSqlModel saved = repo.findById(dto.id()).orElse(null);
            if (saved != null) {
                syncDraftColumns(saved);
            }
        }
        return dto;
    }

    public SqlModelOdsGenerateResult generateFromOds(SqlModelOdsGenerateRequest request, String activeDeptHeader) {
        if (request == null || request.planId() == null) {
            throw new IllegalArgumentException("请选择项目空间");
        }
        if (request.mappingIds() == null || request.mappingIds().isEmpty()) {
            throw new IllegalArgumentException("请至少选择一个 ODS 表");
        }

        boolean createDwd = request.createDwd() == null || request.createDwd();
        boolean createDws = request.createDws() == null || request.createDws();
        boolean createAds = request.createAds() == null || request.createAds();
        if (!createDwd && !createDws && !createAds) {
            throw new IllegalArgumentException("请至少选择一个分层（DWD/DWS/ADS）");
        }

        String activeDept = security.resolveActiveDept(activeDeptHeader);
        boolean instituteScope = security.hasInstituteScope();
        ensureWorkspaceWritable();
        resolvePlan(request.planId(), activeDeptHeader);
        UUID preferredSourceId = resolveUsableSourceId(request.sourceDataSourceId(), activeDeptHeader, "request");

        UUID fallbackSourceId = resolveFallbackSourceId(activeDeptHeader);

        Set<UUID> selectedIds = new LinkedHashSet<>(request.mappingIds());
        List<InfraOdsTableMapping> mappings = odsTableMappingRepository.findAllById(selectedIds)
            .stream()
            .filter(mapping -> mapping != null && Boolean.TRUE.equals(mapping.getEnabled()) && isOwnerDeptVisible(mapping.getOwnerDept(), activeDept, instituteScope))
            .sorted(
                Comparator.comparing((InfraOdsTableMapping m) -> defaultText(trimToNull(m.getOdsSchema()), "public"), String.CASE_INSENSITIVE_ORDER)
                    .thenComparing(m -> defaultText(trimToNull(m.getOdsTable()), ""))
            )
            .toList();

        if (mappings.isEmpty()) {
            throw new IllegalArgumentException("未找到可用的 ODS 表映射");
        }

        int created = 0;
        int updated = 0;
        List<String> createdModels = new ArrayList<>();
        List<String> updatedModels = new ArrayList<>();
        List<String> skipped = new ArrayList<>();
        int qualityTemplatesGenerated = 0;
        List<String> qualitySkipped = new ArrayList<>();
        boolean overwrite = request.overwriteExisting() == null || request.overwriteExisting();

        for (InfraOdsTableMapping mapping : mappings) {
            String odsSchema = defaultText(trimToNull(mapping.getOdsSchema()), "public");
            String odsTable = trimToNull(mapping.getOdsTable());
            if (!StringUtils.hasText(odsTable)) {
                skipped.add("mapping:" + mapping.getId() + " (ODS 表名为空)");
                continue;
            }
            if (!hasActiveOdsDataset(odsSchema, odsTable)) {
                skipped.add(odsSchema + "." + odsTable + " (ODS 映射已过期，请先重新采集)");
                continue;
            }
            UUID modelSourceId = preferredSourceId;
            if (modelSourceId == null) {
                modelSourceId = resolveUsableSourceId(mapping.getConnectionId(), activeDeptHeader, "mapping");
            }
            if (modelSourceId == null) {
                modelSourceId = resolveOdsDatasetSourceId(odsSchema, odsTable, activeDeptHeader);
            }
            if (modelSourceId == null) {
                modelSourceId = fallbackSourceId;
            }
            if (modelSourceId == null) {
                skipped.add(odsSchema + "." + odsTable + " (未找到可用来源数据源)");
                continue;
            }

            String entityToken = resolveEntityToken(mapping, odsTable);
            if (!StringUtils.hasText(entityToken)) {
                skipped.add(odsSchema + "." + odsTable + " (无法推断模型名)");
                continue;
            }

            String extraTags = mergeTags(trimToNull(request.tags()), trimToNull(mapping.getSystemCode()));
            String descriptionBase = trimToNull(mapping.getDescription());
            List<ColumnProfile> sourceColumns = resolveSourceColumnsForQuality(odsSchema, odsTable);
            try {
                GenerateLayerResult dwdResult = null;
                if (createDwd) {
                    dwdResult = upsertGeneratedModel(
                        request.planId(),
                        modelSourceId,
                        "dwd_" + entityToken,
                        "DWD",
                        request.schemaName(),
                        request.materialized(),
                        extraTags,
                        buildLayerDescription("DWD", odsSchema, odsTable, descriptionBase),
                        request.enabled(),
                        request.status(),
                        request.ownerDept(),
                        """
                        select
                          *
                        from {{ source('%s', '%s') }}
                        """.formatted(odsSchema, odsTable),
                        activeDeptHeader,
                        overwrite,
                        sourceColumns
                    );
                    created += dwdResult.created() ? 1 : 0;
                    updated += dwdResult.updated() ? 1 : 0;
                    if (dwdResult.created()) createdModels.add(dwdResult.modelName());
                    if (dwdResult.updated()) updatedModels.add(dwdResult.modelName());
                    if (dwdResult.skippedReason() != null) skipped.add(dwdResult.skippedReason());
                    if (dwdResult.qualityTemplateGenerated()) qualityTemplatesGenerated++;
                    if (dwdResult.qualityWarning() != null) qualitySkipped.add(dwdResult.qualityWarning());
                }

                GenerateLayerResult dwsResult = null;
                if (createDws) {
                    String dwdRef = dwdResult != null ? dwdResult.modelName() : "dwd_" + entityToken;
                    dwsResult = upsertGeneratedModel(
                        request.planId(),
                        modelSourceId,
                        "dws_" + entityToken,
                        "DWS",
                        request.schemaName(),
                        request.materialized(),
                        extraTags,
                        buildLayerDescription("DWS", odsSchema, odsTable, descriptionBase),
                        request.enabled(),
                        request.status(),
                        request.ownerDept(),
                        """
                        select
                          *
                        from {{ ref('%s') }}
                        """.formatted(dwdRef),
                        activeDeptHeader,
                        overwrite,
                        sourceColumns
                    );
                    created += dwsResult.created() ? 1 : 0;
                    updated += dwsResult.updated() ? 1 : 0;
                    if (dwsResult.created()) createdModels.add(dwsResult.modelName());
                    if (dwsResult.updated()) updatedModels.add(dwsResult.modelName());
                    if (dwsResult.skippedReason() != null) skipped.add(dwsResult.skippedReason());
                    if (dwsResult.qualityTemplateGenerated()) qualityTemplatesGenerated++;
                    if (dwsResult.qualityWarning() != null) qualitySkipped.add(dwsResult.qualityWarning());
                }

                if (createAds) {
                    String dwsRef = dwsResult != null ? dwsResult.modelName() : "dws_" + entityToken;
                    GenerateLayerResult adsResult = upsertGeneratedModel(
                        request.planId(),
                        modelSourceId,
                        "ads_" + entityToken,
                        "ADS",
                        request.schemaName(),
                        request.materialized(),
                        extraTags,
                        buildLayerDescription("ADS", odsSchema, odsTable, descriptionBase),
                        request.enabled(),
                        request.status(),
                        request.ownerDept(),
                        """
                        select
                          *
                        from {{ ref('%s') }}
                        """.formatted(dwsRef),
                        activeDeptHeader,
                        overwrite,
                        sourceColumns
                    );
                    created += adsResult.created() ? 1 : 0;
                    updated += adsResult.updated() ? 1 : 0;
                    if (adsResult.created()) createdModels.add(adsResult.modelName());
                    if (adsResult.updated()) updatedModels.add(adsResult.modelName());
                    if (adsResult.skippedReason() != null) skipped.add(adsResult.skippedReason());
                    if (adsResult.qualityTemplateGenerated()) qualityTemplatesGenerated++;
                    if (adsResult.qualityWarning() != null) qualitySkipped.add(adsResult.qualityWarning());
                }
            } catch (RuntimeException ex) {
                String reason = trimToNull(ex.getMessage());
                if (reason == null) {
                    reason = ex.getClass().getSimpleName();
                }
                skipped.add(odsSchema + "." + odsTable + " (生成失败: " + reason + ")");
                LOG.warn("[generate-from-ods] failed for {}.{}: {}", odsSchema, odsTable, reason);
            }
        }

        return new SqlModelOdsGenerateResult(
            mappings.size(),
            created,
            updated,
            createdModels,
            updatedModels,
            skipped,
            qualityTemplatesGenerated,
            qualitySkipped
        );
    }

    public SqlModelDto update(UUID id, SqlModelRequest request, String activeDeptHeader) {
        ensureWorkspaceWritable();
        ModelingSqlModel model = repo.findById(id).orElseThrow(() -> new EntityNotFoundException("模型不存在"));
        String oldPath = model.getModelPath();
        apply(model, request, activeDeptHeader, false);
        ModelingSqlModel saved = repo.save(model);
        writeModelFile(saved);
        deleteFileIfChanged(oldPath, saved.getModelPath());
        syncDraftColumns(saved);
        return toDto(saved);
    }

    private void syncDraftColumns(ModelingSqlModel model) {
        if (model == null) {
            return;
        }
        try {
            DbtConfigService.DbtConfigView view = dbtConfigService.loadConfig();
            String projectDir = view != null && view.config() != null ? view.config().projectDir() : null;
            List<ColumnSpec> specs = resolveCsvSpecs(model, projectDir);
            if (specs.isEmpty()) {
                return;
            }
            String tableName = resolveModelTable(model);
            String schemaName = resolveModelSchema(model, view);
            if (!StringUtils.hasText(tableName) || !StringUtils.hasText(schemaName)) {
                return;
            }
            CatalogDataset dataset = datasetRepository
                .findFirstByHiveDatabaseIgnoreCaseAndHiveTableIgnoreCase(schemaName, tableName)
                .orElse(null);
            if (dataset == null) {
                dataset = new CatalogDataset();
            }
            dataset.setName(defaultText(dataset.getName(), tableName));
            dataset.setHiveDatabase(defaultText(dataset.getHiveDatabase(), schemaName));
            dataset.setHiveTable(defaultText(dataset.getHiveTable(), tableName));
            if (!StringUtils.hasText(dataset.getWarehouseLayer()) && StringUtils.hasText(model.getLayer())) {
                dataset.setWarehouseLayer(normalizeLayer(model.getLayer()));
            }
            if (!StringUtils.hasText(dataset.getType())) {
                dataset.setType(resolveDatasetType(view));
            }
            if (!StringUtils.hasText(dataset.getDescription()) && StringUtils.hasText(model.getDescription())) {
                dataset.setDescription(model.getDescription());
            }
            if (!StringUtils.hasText(dataset.getOwnerDept()) && StringUtils.hasText(model.getOwnerDept())) {
                dataset.setOwnerDept(model.getOwnerDept());
            }
            CatalogDataset savedDataset = datasetRepository.save(dataset);

            CatalogTableSchema table = tableRepository
                .findFirstByDatasetAndNameIgnoreCase(savedDataset, tableName)
                .orElse(null);
            if (table == null) {
                table = new CatalogTableSchema();
                table.setDataset(savedDataset);
            }
            table.setName(tableName);
            CatalogTableSchema savedTable = tableRepository.save(table);

            int updated = columnSyncService.upsertColumns(savedTable, specs, CatalogColumnSyncService.STATUS_DRAFT);
            auditService.auditAction(
                "MODELING_COLUMN_SYNC",
                AuditStage.SUCCESS,
                savedDataset.getId() != null ? savedDataset.getId().toString() : "modeling",
                Map.of(
                    "summary",
                    "模型字段草稿同步",
                    "modelId",
                    model.getId() != null ? model.getId().toString() : null,
                    "schema",
                    schemaName,
                    "table",
                    tableName,
                    "columnCount",
                    updated
                )
            );
        } catch (Exception ex) {
            LOG.warn("[dbt-model] failed to sync draft columns: {}", ex.getMessage());
            auditService.auditAction(
                "MODELING_COLUMN_SYNC",
                AuditStage.FAIL,
                model.getId() != null ? model.getId().toString() : "modeling",
                Map.of("summary", "模型字段草稿同步失败", "error", ex.getMessage())
            );
        }
    }

    private List<ColumnSpec> resolveCsvSpecs(ModelingSqlModel model, String projectDir) {
        if (model == null || !StringUtils.hasText(model.getModelPath()) || !StringUtils.hasText(projectDir)) {
            return List.of();
        }
        Path projectPath = Path.of(projectDir).normalize();
        Path sqlPath = projectPath.resolve(model.getModelPath()).normalize();
        if (!sqlPath.startsWith(projectPath)) {
            return List.of();
        }
        String baseName = sqlPath.getFileName() != null ? sqlPath.getFileName().toString() : null;
        if (!StringUtils.hasText(baseName)) {
            return List.of();
        }
        String csvName = baseName.endsWith(".sql") ? baseName.substring(0, baseName.length() - 4) + ".csv" : baseName + ".csv";
        Path csvPath = sqlPath.resolveSibling(csvName);
        return columnSyncService.parseCsv(csvPath);
    }

    private String resolveModelSchema(ModelingSqlModel model, DbtConfigService.DbtConfigView view) {
        if (model != null && StringUtils.hasText(model.getSchemaName())) {
            return model.getSchemaName().trim();
        }
        if (view != null && view.config() != null && StringUtils.hasText(view.config().schema())) {
            return view.config().schema().trim();
        }
        return "public";
    }

    private String resolveModelTable(ModelingSqlModel model) {
        if (model == null) return null;
        if (StringUtils.hasText(model.getAlias())) {
            return model.getAlias().trim();
        }
        return StringUtils.hasText(model.getName()) ? model.getName().trim() : null;
    }

    private String resolveDatasetType(DbtConfigService.DbtConfigView view) {
        if (view != null && view.target() != null && StringUtils.hasText(view.target().type())) {
            return view.target().type().toUpperCase(Locale.ROOT);
        }
        return null;
    }

    public void delete(UUID id, String activeDeptHeader) {
        String activeDept = security.resolveActiveDept(activeDeptHeader);
        boolean instituteScope = security.hasInstituteScope();
        ModelingSqlModel model = repo.findById(id).orElseThrow(() -> new EntityNotFoundException("模型不存在"));
        if (!isOwnerDeptVisible(model.getOwnerDept(), activeDept, instituteScope)) {
            throw new IllegalArgumentException("当前账号无权删除该模型");
        }
        repo.delete(model);
        deleteFileIfChanged(model.getModelPath(), null);
    }

    private void apply(ModelingSqlModel model, SqlModelRequest request, String activeDeptHeader, boolean isCreate) {
        if (request == null) {
            throw new IllegalArgumentException("模型配置不能为空");
        }
        String name = trimToNull(request.name());
        if (!StringUtils.hasText(name)) {
            throw new IllegalArgumentException("模型名称不能为空");
        }
        if (!MODEL_NAME_PATTERN.matcher(name).matches()) {
            throw new IllegalArgumentException("模型名称仅允许字母/数字/下划线，且必须以字母开头");
        }
        String sql = request.sql();
        if (!StringUtils.hasText(sql)) {
            throw new IllegalArgumentException("SQL 内容不能为空");
        }
        UUID sourceId = request.sourceDataSourceId();
        if (sourceId == null) {
            sourceId = resolveFallbackSourceId(activeDeptHeader);
        }
        if (sourceId == null) {
            throw new IllegalArgumentException("来源数据源不存在，请先配置可用数据源");
        }

        ModelingPlan plan = resolvePlan(request.planId(), activeDeptHeader);
        InfraDataSource source = resolveSource(sourceId, activeDeptHeader);

        String activeDept = security.resolveActiveDept(activeDeptHeader);
        if (isCreate) {
            String ownerDept = trimToNull(request.ownerDept());
            if (ownerDept == null) {
                ownerDept = trimToNull(activeDept);
            }
            if (ownerDept == null && plan != null) {
                ownerDept = trimToNull(plan.getOwnerDept());
            }
            model.setOwnerDept(ownerDept);
        } else if (StringUtils.hasText(request.ownerDept())) {
            model.setOwnerDept(trimToNull(request.ownerDept()));
        }

        String sourceKey = source != null ? resolveSourceKey(source) : null;
        String sourceTag = StringUtils.hasText(sourceKey) ? sanitizeTag(sourceKey, slugify(sourceKey)) : null;
        String mergedTags = mergeTags(request.tags(), sourceTag);
        String dagSelector = resolveDagSelectorValue(mergedTags, sourceTag);
        String layer = trimToNull(request.layer());
        if (layer == null) {
            layer = inferLayer(name);
        }
        layer = normalizeLayer(layer);
        if (!StringUtils.hasText(layer)) {
            throw new IllegalArgumentException("请选择模型分层");
        }

        model.setPlanId(plan != null ? plan.getId() : null);
        model.setName(name);
        model.setAlias(trimToNull(request.alias()));
        model.setLayer(layer);
        model.setSourceDataSourceId(sourceId);
        model.setSchemaName(trimToNull(request.schemaName()));
        model.setMaterialized(defaultText(trimToNull(request.materialized()), "table"));
        model.setTags(mergedTags);
        model.setDagSelector(dagSelector);
        model.setDescription(trimToNull(request.description()));
        model.setSqlText(sql);
        model.setEnabled(request.enabled() == null ? Boolean.TRUE : request.enabled());
        model.setStatus(defaultText(trimToNull(request.status()), "DRAFT"));
        model.setModelPath(resolveModelPath(model, plan, name));
        if (isCreate || request.semanticContract() != null) {
            applySemanticContract(model, request.semanticContract());
        }
    }

    private ModelingPlan resolvePlan(UUID planId, String activeDeptHeader) {
        if (planId == null) {
            return null;
        }
        String activeDept = security.resolveActiveDept(activeDeptHeader);
        boolean instituteScope = security.hasInstituteScope();
        ModelingPlan plan = planRepo.findById(planId).orElseThrow(() -> new EntityNotFoundException("项目空间不存在"));
        if (!isOwnerDeptVisible(plan.getOwnerDept(), activeDept, instituteScope)) {
            throw new IllegalArgumentException("当前账号无权访问该项目空间");
        }
        return plan;
    }

    private InfraDataSource resolveSource(UUID sourceId, String activeDeptHeader) {
        InfraDataSource source = dataSourceRepository.findById(sourceId).orElseThrow(() -> new EntityNotFoundException("来源数据源不存在"));
        String activeDept = security.resolveActiveDept(activeDeptHeader);
        boolean instituteScope = security.hasInstituteScope();
        if (!isOwnerDeptVisible(source.getOwnerDept(), activeDept, instituteScope)) {
            throw new IllegalArgumentException("当前账号无权访问该数据源");
        }
        return source;
    }

    private UUID resolveUsableSourceId(UUID sourceId, String activeDeptHeader, String origin) {
        if (sourceId == null) {
            return null;
        }
        try {
            resolveSource(sourceId, activeDeptHeader);
            return sourceId;
        } catch (RuntimeException ex) {
            LOG.warn("[generate-from-ods] {} sourceDataSourceId {} not usable: {}", origin, sourceId, ex.getMessage());
            return null;
        }
    }

    private UUID resolveOdsDatasetSourceId(String schema, String table, String activeDeptHeader) {
        if (!StringUtils.hasText(schema) || !StringUtils.hasText(table)) {
            return null;
        }
        List<CatalogDataset> datasets = datasetRepository.findByHiveDatabaseIgnoreCaseAndHiveTableIgnoreCase(schema.trim(), table.trim());
        if (datasets == null || datasets.isEmpty()) {
            return null;
        }
        for (CatalogDataset dataset : datasets) {
            if (dataset == null || dataset.getSourceId() == null) {
                continue;
            }
            UUID usable = resolveUsableSourceId(dataset.getSourceId(), activeDeptHeader, "dataset");
            if (usable != null) {
                return usable;
            }
        }
        return null;
    }

    private UUID resolveFallbackSourceId(String activeDeptHeader) {
        List<InfraDataSource> candidates = dataSourceRepository.findByStatusIgnoreCase(STATUS_ACTIVE);
        if (candidates == null || candidates.isEmpty()) {
            candidates = dataSourceRepository.findAll();
        }
        UUID bestId = null;
        int bestScore = Integer.MIN_VALUE;
        for (InfraDataSource source : candidates) {
            if (source == null || source.getId() == null) {
                continue;
            }
            UUID usable = resolveUsableSourceId(source.getId(), activeDeptHeader, "fallback");
            if (usable == null) {
                continue;
            }
            int score = scoreSource(source);
            if (score > bestScore) {
                bestScore = score;
                bestId = usable;
            }
        }
        return bestId;
    }

    private int scoreSource(InfraDataSource source) {
        if (source == null) {
            return Integer.MIN_VALUE;
        }
        int score = 0;
        String name = trimToEmpty(source.getName()).toLowerCase(Locale.ROOT);
        String type = trimToEmpty(source.getType()).toLowerCase(Locale.ROOT);
        String jdbcUrl = trimToEmpty(source.getJdbcUrl()).toLowerCase(Locale.ROOT);
        String status = trimToEmpty(source.getStatus()).toLowerCase(Locale.ROOT);
        if (BIADMIN_NAME.equalsIgnoreCase(source.getName())) {
            score += 100;
        }
        if (name.contains("biadmin")) {
            score += 80;
        }
        if (jdbcUrl.contains("/biadmin")) {
            score += 70;
        }
        if ("postgres".equals(type) || "postgresql".equals(type)) {
            score += 50;
        } else if (StringUtils.hasText(type)) {
            score += 20;
        }
        if ("active".equals(status)) {
            score += 5;
        }
        if (StringUtils.hasText(jdbcUrl)) {
            score += 5;
        }
        return score;
    }

    private void applySemanticContract(ModelingSqlModel model, String rawSemanticContract) {
        String normalized = normalizeSemanticContract(rawSemanticContract);
        if (!StringUtils.hasText(normalized)) {
            model.setSemanticContract(null);
            model.setContractVersion(null);
            model.setContractUpdatedAt(null);
            return;
        }
        boolean changed = !normalized.equals(trimToNull(model.getSemanticContract()));
        model.setSemanticContract(normalized);
        if (changed || !StringUtils.hasText(model.getContractVersion())) {
            model.setContractVersion(computeContractVersion(normalized));
            model.setContractUpdatedAt(Instant.now());
        }
    }

    private String normalizeSemanticContract(String rawSemanticContract) {
        String text = trimToNull(rawSemanticContract);
        if (!StringUtils.hasText(text)) {
            return null;
        }
        try {
            Object parsed = objectMapper.readValue(text, Object.class);
            return objectMapper
                .copy()
                .configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true)
                .writeValueAsString(parsed);
        } catch (Exception ex) {
            throw new IllegalArgumentException("语义契约必须是合法 JSON 对象或数组");
        }
    }

    private String computeContractVersion(String normalizedContract) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(normalizedContract.getBytes(StandardCharsets.UTF_8));
            String hex = HexFormat.of().formatHex(hash);
            return "sc-" + hex.substring(0, 16);
        } catch (NoSuchAlgorithmException ex) {
            throw new IllegalStateException("无法计算契约版本", ex);
        }
    }

    private ContractMeta extractContractMeta(String semanticContract) {
        String normalized = trimToNull(semanticContract);
        if (!StringUtils.hasText(normalized)) {
            return new ContractMeta(0, 0);
        }
        try {
            Object parsed = objectMapper.readValue(normalized, Object.class);
            if (!(parsed instanceof Map<?, ?> map)) {
                return new ContractMeta(0, 0);
            }
            int metricCount = countContractNode(map.get("metrics"));
            int dimensionCount = countContractNode(map.get("dimensions"));
            return new ContractMeta(metricCount, dimensionCount);
        } catch (Exception ignored) {
            return new ContractMeta(0, 0);
        }
    }

    private int countContractNode(Object value) {
        if (value == null) {
            return 0;
        }
        if (value instanceof List<?> list) {
            return list.size();
        }
        if (value instanceof Map<?, ?> map) {
            return map.size();
        }
        return 0;
    }

    private boolean referencesModel(String sqlText, String modelName, String modelAlias) {
        String sql = trimToEmpty(sqlText).toLowerCase(Locale.ROOT);
        if (!StringUtils.hasText(sql)) {
            return false;
        }
        String name = trimToNull(modelName);
        String alias = trimToNull(modelAlias);
        if (StringUtils.hasText(name)) {
            String needle = name.toLowerCase(Locale.ROOT);
            if (
                sql.contains("ref('" + needle + "')") ||
                sql.contains("ref(\"" + needle + "\")") ||
                sql.contains(" " + needle + " ") ||
                sql.contains("." + needle)
            ) {
                return true;
            }
        }
        if (StringUtils.hasText(alias)) {
            String needle = alias.toLowerCase(Locale.ROOT);
            if (
                sql.contains("ref('" + needle + "')") ||
                sql.contains("ref(\"" + needle + "\")") ||
                sql.contains(" " + needle + " ") ||
                sql.contains("." + needle)
            ) {
                return true;
            }
        }
        return false;
    }

    private SqlModelDto toDto(ModelingSqlModel model) {
        if (model == null) return null;
        ModelingPlan plan = model.getPlanId() == null ? null : planRepo.findById(model.getPlanId()).orElse(null);
        InfraDataSource source = model.getSourceDataSourceId() == null
            ? null
            : dataSourceRepository.findById(model.getSourceDataSourceId()).orElse(null);
        String sourceKey = source != null ? resolveSourceKey(source) : null;
        String sourceTag = sanitizeTag(sourceKey, slugify(sourceKey));
        String dagSelector = defaultText(trimToNull(model.getDagSelector()), resolveDagSelectorValue(model.getTags(), sourceTag));
        ContractMeta meta = extractContractMeta(model.getSemanticContract());
        return new SqlModelDto(
            model.getId(),
            model.getPlanId(),
            plan != null ? plan.getName() : null,
            model.getName(),
            model.getAlias(),
            model.getLayer(),
            model.getSourceDataSourceId(),
            source != null ? source.getName() : null,
            sourceKey,
            dagSelector,
            model.getTags(),
            model.getMaterialized(),
            model.getSchemaName(),
            model.getDescription(),
            model.getSqlText(),
            model.getEnabled(),
            model.getModelPath(),
            model.getOwnerDept(),
            model.getStatus(),
            model.getSemanticContract(),
            model.getContractVersion(),
            model.getContractUpdatedAt(),
            meta.metricCount(),
            meta.dimensionCount(),
            model.getCreatedDate(),
            model.getLastModifiedDate()
        );
    }

    private String resolveModelPath(ModelingSqlModel model, ModelingPlan plan, String name) {
        String planSlug = plan == null ? null : slugify(plan.getName());
        if (!StringUtils.hasText(planSlug)) {
            planSlug = "default";
        }
        String fileName = slugify(name);
        if (!StringUtils.hasText(fileName)) {
            fileName = "model";
        }
        String layerDir = resolveLayerDir(model != null ? model.getLayer() : null);
        return "models/" + layerDir + "/" + planSlug + "/" + fileName + ".sql";
    }

    private void ensureWorkspaceWritable() {
        DbtConfigService.DbtConfigView view = dbtConfigService.loadConfig();
        if (view == null || view.workspaceStatus() == null || !view.workspaceStatus().ok()) {
            String message = view != null && view.workspaceStatus() != null
                ? view.workspaceStatus().message()
                : "dbt 工作区未配置";
            throw new IllegalArgumentException(message);
        }
    }

    private Map<String, Object> toColumnPayload(CatalogColumnSchema column) {
        Map<String, Object> item = new LinkedHashMap<>();
        if (column == null) {
            return item;
        }
        item.put("name", column.getName());
        item.put("dataType", column.getDataType());
        item.put("comment", column.getComment());
        item.put("status", column.getStatus());
        return item;
    }

    private void writeModelFile(ModelingSqlModel model) {
        if (model == null) return;
        DbtConfigService.DbtConfigView view = dbtConfigService.loadConfig();
        if (view == null || view.config() == null || !StringUtils.hasText(view.config().projectDir())) {
            throw new IllegalStateException("dbt projectDir 未配置，无法写入模型文件");
        }
        Path projectDir = Path.of(view.config().projectDir()).normalize();
        Path targetPath = projectDir.resolve(model.getModelPath()).normalize();
        if (!targetPath.startsWith(projectDir)) {
            throw new IllegalStateException("模型文件目标路径非法: " + targetPath);
        }
        try {
            Files.createDirectories(targetPath.getParent());
            String sourceTag = resolveSourceTag(model.getSourceDataSourceId());
            String content = buildSqlContent(model, sourceTag);
            Files.writeString(targetPath, content, StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        } catch (IOException ex) {
            throw new IllegalStateException("写入模型文件失败: " + ex.getMessage(), ex);
        }
    }

    private void writeCsvSidecar(String modelPath, String csvText) {
        if (!StringUtils.hasText(modelPath) || !StringUtils.hasText(csvText)) {
            return;
        }
        DbtConfigService.DbtConfigView view = dbtConfigService.loadConfig();
        if (view == null || view.config() == null || !StringUtils.hasText(view.config().projectDir())) {
            throw new IllegalStateException("dbt projectDir 未配置，无法写入 CSV 文件");
        }
        Path projectDir = Path.of(view.config().projectDir()).normalize();
        Path sqlPath = projectDir.resolve(modelPath).normalize();
        if (!sqlPath.startsWith(projectDir)) {
            throw new IllegalStateException("CSV 目标路径非法: " + sqlPath);
        }
        String baseName = sqlPath.getFileName().toString();
        String csvName = baseName.endsWith(".sql") ? baseName.substring(0, baseName.length() - 4) + ".csv" : baseName + ".csv";
        Path csvPath = sqlPath.resolveSibling(csvName);
        try {
            Files.createDirectories(csvPath.getParent());
            Files.writeString(csvPath, csvText.trim() + "\n", StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        } catch (IOException ex) {
            throw new IllegalStateException("写入 CSV 文件失败: " + ex.getMessage(), ex);
        }
    }

    private void deleteFileIfChanged(String oldPath, String newPath) {
        if (!StringUtils.hasText(oldPath)) {
            return;
        }
        if (StringUtils.hasText(newPath) && oldPath.equals(newPath)) {
            return;
        }
        DbtConfigService.DbtConfigView view = dbtConfigService.loadConfig();
        if (view == null || view.config() == null || !StringUtils.hasText(view.config().projectDir())) {
            return;
        }
        Path projectDir = Path.of(view.config().projectDir()).normalize();
        Path targetPath = projectDir.resolve(oldPath).normalize();
        if (!targetPath.startsWith(projectDir)) {
            return;
        }
        try {
            Files.deleteIfExists(targetPath);
        } catch (IOException ex) {
            LOG.warn("[dbt-model] failed to delete {}: {}", targetPath, ex.getMessage());
        }
    }

    private String buildSqlContent(ModelingSqlModel model, String sourceTag) {
        String body = trimToEmpty(model.getSqlText());
        // 如果用户的 SQL 已经包含 {{ config，不再自动添加
        if (body.contains("{{ config") || body.contains("{{config")) {
            return body + "\n";
        }
        String configLine = buildConfigLine(model, sourceTag);
        if (!StringUtils.hasText(configLine)) {
            return body + "\n";
        }
        return configLine + "\n\n" + body + "\n";
    }

    private String buildConfigLine(ModelingSqlModel model, String sourceTag) {
        List<String> configs = new ArrayList<>();
        if (StringUtils.hasText(model.getMaterialized())) {
            configs.add("materialized='" + model.getMaterialized() + "'");
        }
        if (StringUtils.hasText(model.getAlias())) {
            configs.add("alias='" + model.getAlias() + "'");
        }
        // 不自动添加 schema 参数，让 dbt 使用 profiles.yml 里配置的默认 schema
        // 避免生成 public_public 这样的拼接 schema 名
        String layerTag = sanitizeTag(normalizeLayer(model.getLayer()), null);
        List<String> tags = splitTags(model.getTags(), sourceTag, layerTag);
        if (!tags.isEmpty()) {
            String rendered = tags.stream().map(tag -> "'" + tag + "'").reduce((a, b) -> a + ", " + b).orElse("");
            configs.add("tags=[" + rendered + "]");
        }
        if (configs.isEmpty()) {
            return "";
        }
        return "{{ config(" + String.join(", ", configs) + ") }}";
    }

    private List<String> splitTags(String rawTags, String sourceTag, String layerTag) {
        Set<String> tags = new LinkedHashSet<>();
        if (StringUtils.hasText(rawTags)) {
            String[] parts = rawTags.split("[,;\\s]+");
            for (String part : parts) {
                String tag = sanitizeTag(part, null);
                if (StringUtils.hasText(tag)) {
                    tags.add(tag);
                }
            }
        }
        if (StringUtils.hasText(sourceTag)) {
            tags.add(sanitizeTag(sourceTag, null));
        }
        if (StringUtils.hasText(layerTag)) {
            tags.add(sanitizeTag(layerTag, null));
        }
        return new ArrayList<>(tags);
    }

    private String resolveSourceTag(UUID sourceId) {
        if (sourceId == null) return null;
        InfraDataSource source = dataSourceRepository.findById(sourceId).orElse(null);
        if (source == null) return null;
        return sanitizeTag(resolveSourceKey(source), slugify(source.getName()));
    }

    private boolean matchKeyword(ModelingSqlModel model, String keyword) {
        if (model == null || !StringUtils.hasText(keyword)) return false;
        String kw = keyword.toLowerCase(Locale.ROOT);
        return contains(model.getName(), kw) || contains(model.getDescription(), kw) || contains(model.getTags(), kw);
    }

    private boolean contains(String value, String keyword) {
        if (!StringUtils.hasText(value) || !StringUtils.hasText(keyword)) return false;
        return value.toLowerCase(Locale.ROOT).contains(keyword.trim().toLowerCase(Locale.ROOT));
    }

    private boolean isOwnerDeptVisible(String ownerDept, String activeDept, boolean instituteScope) {
        String trimmedOwner = trimToNull(ownerDept);
        if (trimmedOwner == null) return true;
        if (instituteScope) return true;
        if (organizationVisibilityService.isRoot(trimmedOwner)) return true;
        if (!StringUtils.hasText(activeDept)) return false;
        return DepartmentUtils.matches(trimmedOwner, activeDept);
    }

    private String resolveSourceKey(InfraDataSource source) {
        if (source == null) return null;
        Map<String, Object> props = parseProps(source.getProps());
        String key = firstText(props, "sourceSystem", "sourceName", "system", "app", "appCode", "name");
        if (StringUtils.hasText(key)) {
            return key;
        }
        return source.getName();
    }

    private Map<String, Object> parseProps(String raw) {
        if (!StringUtils.hasText(raw)) return Map.of();
        String trimmed = raw.trim();
        if (trimmed.startsWith("{")) {
            try {
                return objectMapper.readValue(trimmed, new TypeReference<>() {});
            } catch (Exception ignored) {}
        }
        return Map.of();
    }

    private String firstText(Map<String, Object> props, String... keys) {
        if (props == null) return null;
        for (String key : keys) {
            Object value = props.get(key);
            if (value != null) {
                String text = value.toString().trim();
                if (!text.isEmpty()) return text;
            }
        }
        return null;
    }

    private String slugify(String value) {
        if (!StringUtils.hasText(value)) return "model";
        String slug = NON_SAFE.matcher(value.trim().toLowerCase(Locale.ROOT)).replaceAll("_");
        slug = slug.replaceAll("^_+", "").replaceAll("_+$", "");
        return StringUtils.hasText(slug) ? slug : "model";
    }

    private String sanitizeTag(String value, String fallback) {
        if (!StringUtils.hasText(value)) return fallback;
        String tag = NON_SAFE.matcher(value.trim().toLowerCase(Locale.ROOT)).replaceAll("-");
        tag = tag.replaceAll("^-+", "").replaceAll("-+$", "");
        return StringUtils.hasText(tag) ? tag : fallback;
    }

    private String mergeTags(String rawTags, String sourceTag) {
        List<String> tags = splitTags(rawTags, sourceTag, null);
        if (tags.isEmpty()) return null;
        return String.join(",", tags);
    }

    private String resolveDagSelectorValue(String rawTags, String fallbackTag) {
        List<String> tags = splitTags(rawTags, fallbackTag, null);
        if (tags.isEmpty()) {
            return null;
        }
        return "tag:" + tags.get(0);
    }

    private String parseDbtTags(String sqlText) {
        if (!StringUtils.hasText(sqlText)) {
            return null;
        }
        Set<String> tags = new LinkedHashSet<>();
        Matcher configMatcher = DBT_TAGS_CONFIG_PATTERN.matcher(sqlText);
        while (configMatcher.find()) {
            Matcher literalMatcher = DBT_TAG_LITERAL_PATTERN.matcher(configMatcher.group(1));
            while (literalMatcher.find()) {
                String tag = sanitizeTag(literalMatcher.group(1), null);
                if (StringUtils.hasText(tag)) {
                    tags.add(tag);
                }
            }
        }
        return tags.isEmpty() ? null : String.join(",", tags);
    }

    private String inferLayer(String name) {
        if (!StringUtils.hasText(name)) return null;
        String normalized = name.trim().toLowerCase(Locale.ROOT);
        if (normalized.startsWith("ods_")) return "ODS";
        if (normalized.startsWith("dwd_")) return "DWD";
        if (normalized.startsWith("dws_")) return "DWS";
        if (normalized.startsWith("ads_")) return "ADS";
        return null;
    }

    private void syncWorkspaceModels(String activeDeptHeader) {
        DbtConfigService.DbtConfigView view = dbtConfigService.loadConfig();
        if (view == null || view.config() == null || !StringUtils.hasText(view.config().projectDir())) {
            return;
        }
        UUID sourceDataSourceId = resolveFallbackSourceId(activeDeptHeader);
        if (sourceDataSourceId == null) {
            return;
        }
        Path projectDir = Path.of(view.config().projectDir()).normalize();
        Path modelsDir = projectDir.resolve("models").normalize();
        if (!modelsDir.startsWith(projectDir) || !Files.isDirectory(modelsDir)) {
            return;
        }
        Map<String, ModelingSqlModel> existingByName = new LinkedHashMap<>();
        for (ModelingSqlModel existing : repo.findAll()) {
            if (existing == null || !StringUtils.hasText(existing.getName())) {
                continue;
            }
            existingByName.putIfAbsent(existing.getName().trim().toLowerCase(Locale.ROOT), existing);
        }
        try (var walk = Files.walk(modelsDir, FileVisitOption.FOLLOW_LINKS)) {
            walk
                .filter(Files::isRegularFile)
                .filter(path -> path.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".sql"))
                .sorted(Comparator.comparing(path -> path.toString().toLowerCase(Locale.ROOT)))
                .forEach(path -> upsertDiscoveredWorkspaceModel(projectDir, path, view.config(), sourceDataSourceId, existingByName));
        } catch (IOException ex) {
            LOG.warn("[dbt-model] failed to discover workspace models: {}", ex.getMessage());
        }
    }

    private void upsertDiscoveredWorkspaceModel(
        Path projectDir,
        Path sqlFile,
        DbtConfigService.DbtWorkspaceConfig config,
        UUID sourceDataSourceId,
        Map<String, ModelingSqlModel> existingByName
    ) {
        try {
            String fileName = sqlFile.getFileName() == null ? null : sqlFile.getFileName().toString();
            if (!StringUtils.hasText(fileName) || !fileName.toLowerCase(Locale.ROOT).endsWith(".sql")) {
                return;
            }
            String modelName = fileName.substring(0, fileName.length() - 4);
            if (!MODEL_NAME_PATTERN.matcher(modelName).matches()) {
                return;
            }
            String relativePath = projectDir.relativize(sqlFile).toString().replace('\\', '/');
            String sqlText = Files.readString(sqlFile, StandardCharsets.UTF_8);
            String layer = inferLayerFromPath(relativePath, modelName);
            String discoveredTags = parseDbtTags(sqlText);
            String discoveredDagSelector = resolveDagSelectorValue(discoveredTags, null);
            String key = modelName.toLowerCase(Locale.ROOT);
            ModelingSqlModel existing = existingByName.get(key);
            boolean changed = false;
            if (existing == null) {
                existing = new ModelingSqlModel();
                existing.setName(modelName);
                existing.setEnabled(Boolean.TRUE);
                existing.setStatus("DRAFT");
                existing.setSourceDataSourceId(sourceDataSourceId);
                existing.setSchemaName(trimToNull(config != null ? config.schema() : null));
                existing.setMaterialized("table");
                existing.setDescription("从 dbt 工作区自动发现");
                changed = true;
            }
            if (!relativePath.equals(trimToNull(existing.getModelPath()))) {
                existing.setModelPath(relativePath);
                changed = true;
            }
            if (!sqlText.equals(defaultText(existing.getSqlText(), ""))) {
                existing.setSqlText(sqlText);
                changed = true;
            }
            if (!StringUtils.hasText(existing.getLayer()) && StringUtils.hasText(layer)) {
                existing.setLayer(layer);
                changed = true;
            }
            if (StringUtils.hasText(discoveredTags) && !discoveredTags.equals(trimToNull(existing.getTags()))) {
                existing.setTags(discoveredTags);
                changed = true;
            }
            if (StringUtils.hasText(discoveredDagSelector) && !discoveredDagSelector.equals(trimToNull(existing.getDagSelector()))) {
                existing.setDagSelector(discoveredDagSelector);
                changed = true;
            }
            if (existing.getSourceDataSourceId() == null) {
                existing.setSourceDataSourceId(sourceDataSourceId);
                changed = true;
            }
            if (!StringUtils.hasText(existing.getMaterialized())) {
                existing.setMaterialized("table");
                changed = true;
            }
            if (changed) {
                ModelingSqlModel saved = repo.save(existing);
                existingByName.put(key, saved);
            }
        } catch (IOException ex) {
            LOG.warn("[dbt-model] failed to load sql file {}: {}", sqlFile, ex.getMessage());
        }
    }

    private String inferLayerFromPath(String relativePath, String modelName) {
        if (StringUtils.hasText(relativePath)) {
            String normalized = relativePath.replace('\\', '/').toLowerCase(Locale.ROOT);
            if (normalized.contains("/ods/")) return "ODS";
            if (normalized.contains("/dwd/")) return "DWD";
            if (normalized.contains("/dws/")) return "DWS";
            if (normalized.contains("/ads/")) return "ADS";
        }
        return inferLayer(modelName);
    }

    private String normalizeLayer(String layer) {
        if (!StringUtils.hasText(layer)) {
            return null;
        }
        String normalized = layer.trim().toUpperCase(Locale.ROOT);
        if ("ODS".equals(normalized) || "DWD".equals(normalized) || "DWS".equals(normalized) || "ADS".equals(normalized)) {
            return normalized;
        }
        return null;
    }

    private String resolveLayerDir(String layer) {
        String normalized = normalizeLayer(layer);
        if ("ODS".equals(normalized)) {
            return "ods";
        }
        if ("DWD".equals(normalized)) {
            return "dwd";
        }
        if ("DWS".equals(normalized)) {
            return "dws";
        }
        if ("ADS".equals(normalized)) {
            return "ads";
        }
        return "dwh";
    }

    private String trimToNull(String value) {
        if (!StringUtils.hasText(value)) return null;
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

    private String trimToEmpty(String value) {
        return value == null ? "" : value.trim();
    }

    private String defaultText(String value, String fallback) {
        return StringUtils.hasText(value) ? value : fallback;
    }

    private boolean hasActiveOdsDataset(String schema, String table) {
        if (!StringUtils.hasText(schema) || !StringUtils.hasText(table)) {
            return false;
        }
        boolean exists = datasetRepository.existsByHiveDatabaseIgnoreCaseAndHiveTableIgnoreCaseAndWarehouseLayerIgnoreCaseAndEnabledTrue(
            schema.trim(),
            table.trim(),
            "ODS"
        );
        if (!exists) {
            exists = datasetRepository.existsByHiveDatabaseIgnoreCaseAndHiveTableIgnoreCaseAndEnabledTrue(schema.trim(), table.trim());
        }
        return exists;
    }

    private String resolveEntityToken(InfraOdsTableMapping mapping, String odsTable) {
        String candidate = trimToNull(mapping != null ? mapping.getEntityCode() : null);
        if (!StringUtils.hasText(candidate)) {
            candidate = trimToNull(odsTable);
        }
        if (!StringUtils.hasText(candidate)) {
            return null;
        }
        String normalized = slugify(candidate);
        if (normalized.startsWith("ods_")) {
            normalized = normalized.substring(4);
        }
        normalized = normalized.replaceAll("^_+", "").replaceAll("_+$", "");
        return StringUtils.hasText(normalized) ? normalized : null;
    }

    private String buildLayerDescription(String layer, String odsSchema, String odsTable, String baseDescription) {
        String layerText = defaultText(layer, "DWD");
        String sourceText = odsSchema + "." + odsTable;
        if (StringUtils.hasText(baseDescription)) {
            return layerText + " 自动生成模型，来源 " + sourceText + "；" + baseDescription;
        }
        return layerText + " 自动生成模型，来源 " + sourceText;
    }

    private GenerateLayerResult upsertGeneratedModel(
        UUID planId,
        UUID sourceDataSourceId,
        String modelName,
        String layer,
        String schemaName,
        String materialized,
        String tags,
        String description,
        Boolean enabled,
        String status,
        String ownerDept,
        String sql,
        String activeDeptHeader,
        boolean overwrite,
        List<ColumnProfile> sourceColumns
    ) {
        if (sourceDataSourceId == null) {
            return new GenerateLayerResult(modelName, false, false, modelName + " (来源数据源不可用: 来源数据源不存在)", false, null);
        }
        ModelingSqlModel existing = repo.findFirstByPlanIdAndNameIgnoreCase(planId, modelName).orElse(null);
        if (existing != null && !overwrite) {
            return new GenerateLayerResult(modelName, false, false, modelName + " (已存在，未覆盖)", false, null);
        }
        SqlModelRequest payload = new SqlModelRequest(
            planId,
            modelName,
            null,
            layer,
            sourceDataSourceId,
            trimToNull(schemaName),
            defaultText(trimToNull(materialized), "table"),
            tags,
            description,
            sql,
            enabled,
            trimToNull(status),
            trimToNull(ownerDept),
            null
        );
        SqlModelDto dto;
        boolean created;
        boolean updated;
        if (existing == null) {
            dto = create(payload, activeDeptHeader);
            created = true;
            updated = false;
        } else {
            dto = update(existing.getId(), payload, activeDeptHeader);
            created = false;
            updated = true;
        }
        String qualityWarning = writeAutoQualityTemplate(dto, sourceColumns, planId);
        boolean qualityGenerated = qualityWarning == null;
        if (qualityWarning != null) {
            LOG.warn("[generate-from-ods] quality template skipped for {}: {}", modelName, qualityWarning);
        }
        return new GenerateLayerResult(modelName, created, updated, null, qualityGenerated, qualityWarning);
    }

    private List<ColumnProfile> resolveSourceColumnsForQuality(String schema, String table) {
        if (!StringUtils.hasText(schema) || !StringUtils.hasText(table)) {
            return List.of();
        }
        CatalogDataset dataset = datasetRepository.findFirstByHiveDatabaseIgnoreCaseAndHiveTableIgnoreCase(schema.trim(), table.trim()).orElse(null);
        if (dataset == null) {
            return List.of();
        }
        CatalogTableSchema catalogTable = tableRepository.findFirstByDatasetAndNameIgnoreCase(dataset, table.trim()).orElse(null);
        if (catalogTable == null) {
            List<CatalogTableSchema> tables = tableRepository.findByDataset(dataset);
            if (tables != null && !tables.isEmpty()) {
                catalogTable = tables.get(0);
            }
        }
        if (catalogTable == null) {
            return List.of();
        }
        List<CatalogColumnSchema> columns = columnRepository.findByTable(catalogTable);
        if (columns == null || columns.isEmpty()) {
            return List.of();
        }
        List<ColumnProfile> profiles = new ArrayList<>();
        for (CatalogColumnSchema column : columns) {
            if (column == null || !StringUtils.hasText(column.getName())) {
                continue;
            }
            profiles.add(
                new ColumnProfile(
                    column.getName().trim(),
                    trimToNull(column.getDataType()),
                    column.getNullable(),
                    trimToNull(column.getComment()),
                    column.getStandardId() != null ? column.getStandardId().toString() : null,
                    trimToNull(column.getStandardRule())
                )
            );
        }
        profiles.sort(Comparator.comparing(ColumnProfile::name, String.CASE_INSENSITIVE_ORDER));
        return profiles;
    }

    private String writeAutoQualityTemplate(SqlModelDto model, List<ColumnProfile> sourceColumns, UUID planId) {
        if (model == null || !StringUtils.hasText(model.modelPath()) || !StringUtils.hasText(model.name())) {
            return "模型信息不完整";
        }
        if (sourceColumns == null || sourceColumns.isEmpty()) {
            return model.name() + " (无法推断字段，跳过质量模板生成)";
        }
        DbtConfigService.DbtConfigView view = dbtConfigService.loadConfig();
        if (view == null || view.config() == null || !StringUtils.hasText(view.config().projectDir())) {
            return model.name() + " (dbt projectDir 未配置)";
        }
        Path projectDir = Path.of(view.config().projectDir()).normalize();
        Path sqlPath = projectDir.resolve(model.modelPath()).normalize();
        if (!sqlPath.startsWith(projectDir)) {
            return model.name() + " (模型路径不在项目目录内)";
        }
        String baseName = sqlPath.getFileName() == null ? null : sqlPath.getFileName().toString();
        if (!StringUtils.hasText(baseName)) {
            return model.name() + " (无法解析模型文件名)";
        }
        String ymlName = baseName.endsWith(".sql") ? baseName.substring(0, baseName.length() - 4) + ".yml" : baseName + ".yml";
        Path ymlPath = sqlPath.resolveSibling(ymlName).normalize();
        if (!ymlPath.startsWith(projectDir)) {
            return model.name() + " (质量模板路径非法)";
        }
        try {
            if (Files.exists(ymlPath)) {
                String existing = Files.readString(ymlPath, StandardCharsets.UTF_8);
                if (StringUtils.hasText(existing) && !existing.contains(AUTO_QUALITY_MARKER)) {
                    return model.name() + " (已存在手工 yml，未覆盖)";
                }
            }
            Files.createDirectories(ymlPath.getParent());
            String content = buildAutoQualityYaml(model, sourceColumns, planId);
            Files.writeString(ymlPath, content, StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
            return null;
        } catch (IOException ex) {
            return model.name() + " (写入质量模板失败: " + ex.getMessage() + ")";
        }
    }

    private String buildAutoQualityYaml(SqlModelDto model, List<ColumnProfile> sourceColumns, UUID planId) {
        String modelName = model.name();
        String pkColumn = detectPrimaryKey(modelName, sourceColumns);
        Map<String, String> relationTargets = inferRelationshipTargets(sourceColumns, pkColumn, planId);

        List<Map<String, Object>> columns = new ArrayList<>();
        for (ColumnProfile column : sourceColumns) {
            if (!StringUtils.hasText(column.name())) {
                continue;
            }
            List<Object> tests = new ArrayList<>();
            if (isNotNullColumn(column, pkColumn)) {
                tests.add("not_null");
            }
            if (StringUtils.hasText(pkColumn) && pkColumn.equalsIgnoreCase(column.name())) {
                tests.add("unique");
            }
            String relationModel = relationTargets.get(column.name().toLowerCase(Locale.ROOT));
            if (StringUtils.hasText(relationModel)) {
                Map<String, Object> relation = new LinkedHashMap<>();
                relation.put("to", "ref('" + relationModel + "')");
                relation.put("field", column.name());
                tests.add(Map.of("relationships", relation));
            }

            Map<String, Object> meta = new LinkedHashMap<>();
            if (StringUtils.hasText(column.dataType())) {
                meta.put("expected_data_type", column.dataType());
            }
            if (StringUtils.hasText(column.standardId())) {
                meta.put("standard_id", column.standardId());
            }
            if (StringUtils.hasText(column.standardRule())) {
                meta.put("standard_rule", column.standardRule());
            }

            Map<String, Object> columnYaml = new LinkedHashMap<>();
            columnYaml.put("name", column.name());
            columnYaml.put("description", defaultText(column.comment(), ""));
            if (!tests.isEmpty()) {
                columnYaml.put("tests", tests);
            }
            if (!meta.isEmpty()) {
                columnYaml.put("meta", meta);
            }
            columns.add(columnYaml);
        }

        Map<String, Object> modelMeta = new LinkedHashMap<>();
        modelMeta.put("auto_quality", true);
        modelMeta.put("generated_by", "dts-platform");
        modelMeta.put("generator_version", "v2");
        modelMeta.put("updated_at", Instant.now().toString());

        Map<String, Object> modelNode = new LinkedHashMap<>();
        modelNode.put("name", modelName);
        modelNode.put("description", defaultText(trimToNull(model.description()), model.layer() + " 自动生成模型"));
        modelNode.put("meta", modelMeta);
        modelNode.put("columns", columns);

        Map<String, Object> root = new LinkedHashMap<>();
        root.put("version", 2);
        root.put("models", List.of(modelNode));

        StringBuilder yaml = new StringBuilder();
        yaml.append("# ").append(AUTO_QUALITY_MARKER).append("\n");
        yaml.append("# generated_at: ").append(Instant.now().toString()).append("\n");
        yaml.append(AutoYamlWriter.toYaml(root));
        return yaml.toString();
    }

    private String detectPrimaryKey(String modelName, List<ColumnProfile> columns) {
        if (columns == null || columns.isEmpty()) {
            return null;
        }
        Set<String> names = new LinkedHashSet<>();
        for (ColumnProfile column : columns) {
            names.add(column.name().toLowerCase(Locale.ROOT));
        }
        String entity = modelName;
        if (StringUtils.hasText(entity)) {
            entity = entity.toLowerCase(Locale.ROOT);
            entity = entity.replaceFirst("^(ods_|dwd_|dws_|ads_)", "");
            String preferred = entity + "_id";
            if (names.contains(preferred)) {
                return preferred;
            }
        }
        if (names.contains("id")) {
            return "id";
        }
        for (ColumnProfile column : columns) {
            String name = column.name().toLowerCase(Locale.ROOT);
            if (name.endsWith("_id")) {
                return name;
            }
        }
        return null;
    }

    private Map<String, String> inferRelationshipTargets(List<ColumnProfile> columns, String pkColumn, UUID planId) {
        if (columns == null || columns.isEmpty() || planId == null) {
            return Map.of();
        }
        List<ModelingSqlModel> planModels = repo.findByPlanId(planId);
        if (planModels == null || planModels.isEmpty()) {
            return Map.of();
        }
        Set<String> modelNames = new LinkedHashSet<>();
        for (ModelingSqlModel model : planModels) {
            if (model != null && StringUtils.hasText(model.getName())) {
                modelNames.add(model.getName().trim().toLowerCase(Locale.ROOT));
            }
        }
        if (modelNames.isEmpty()) {
            return Map.of();
        }
        Map<String, String> relations = new LinkedHashMap<>();
        for (ColumnProfile column : columns) {
            String name = column.name().toLowerCase(Locale.ROOT);
            if (!name.endsWith("_id")) {
                continue;
            }
            if (StringUtils.hasText(pkColumn) && name.equalsIgnoreCase(pkColumn)) {
                continue;
            }
            String token = name.substring(0, name.length() - 3);
            if (!StringUtils.hasText(token)) {
                continue;
            }
            String target = findRelationshipTargetModel(token, modelNames);
            if (target != null) {
                relations.put(name, target);
            }
        }
        return relations;
    }

    private String findRelationshipTargetModel(String token, Set<String> modelNames) {
        List<String> candidates = List.of("dim_" + token, "dwd_" + token, "dws_" + token, "ads_" + token);
        for (String candidate : candidates) {
            if (modelNames.contains(candidate)) {
                return candidate;
            }
        }
        return null;
    }

    private boolean isNotNullColumn(ColumnProfile column, String pkColumn) {
        if (column == null || !StringUtils.hasText(column.name())) {
            return false;
        }
        String name = column.name().toLowerCase(Locale.ROOT);
        if (StringUtils.hasText(pkColumn) && pkColumn.equalsIgnoreCase(name)) {
            return true;
        }
        if ("source_system".equals(name) || "import_time".equals(name)) {
            return true;
        }
        return Boolean.FALSE.equals(column.nullable());
    }

    public record SqlModelOdsGenerateRequest(
        UUID planId,
        UUID sourceDataSourceId,
        List<UUID> mappingIds,
        String schemaName,
        String materialized,
        String tags,
        String ownerDept,
        Boolean enabled,
        String status,
        Boolean createDwd,
        Boolean createDws,
        Boolean createAds,
        Boolean overwriteExisting
    ) {}

    public record SqlModelOdsGenerateResult(
        int mappingsTotal,
        int modelsCreated,
        int modelsUpdated,
        List<String> createdModels,
        List<String> updatedModels,
        List<String> skipped,
        int qualityTemplatesGenerated,
        List<String> qualitySkipped
    ) {}

    private record GenerateLayerResult(
        String modelName,
        boolean created,
        boolean updated,
        String skippedReason,
        boolean qualityTemplateGenerated,
        String qualityWarning
    ) {}

    private record ColumnProfile(
        String name,
        String dataType,
        Boolean nullable,
        String comment,
        String standardId,
        String standardRule
    ) {}

    private static final class AutoYamlWriter {
        private static String toYaml(Map<String, Object> root) {
            StringBuilder sb = new StringBuilder();
            writeMap(sb, root, 0);
            return sb.toString();
        }

        @SuppressWarnings("unchecked")
        private static void writeMap(StringBuilder sb, Map<String, Object> map, int indent) {
            String prefix = " ".repeat(Math.max(0, indent));
            for (Map.Entry<String, Object> entry : map.entrySet()) {
                sb.append(prefix).append(entry.getKey()).append(":");
                Object value = entry.getValue();
                if (value instanceof Map<?, ?> nested) {
                    sb.append("\n");
                    writeMap(sb, (Map<String, Object>) nested, indent + 2);
                } else if (value instanceof List<?> list) {
                    sb.append("\n");
                    writeList(sb, list, indent + 2);
                } else {
                    sb.append(" ").append(scalar(value)).append("\n");
                }
            }
        }

        @SuppressWarnings("unchecked")
        private static void writeList(StringBuilder sb, List<?> list, int indent) {
            String prefix = " ".repeat(Math.max(0, indent));
            for (Object item : list) {
                sb.append(prefix).append("-");
                if (item instanceof Map<?, ?> nested) {
                    sb.append("\n");
                    writeMap(sb, (Map<String, Object>) nested, indent + 2);
                } else if (item instanceof List<?> nestedList) {
                    sb.append("\n");
                    writeList(sb, nestedList, indent + 2);
                } else {
                    sb.append(" ").append(scalar(item)).append("\n");
                }
            }
        }

        private static String scalar(Object value) {
            if (value == null) {
                return "\"\"";
            }
            if (value instanceof Number || value instanceof Boolean) {
                return value.toString();
            }
            String text = String.valueOf(value);
            if (text.isEmpty()) {
                return "\"\"";
            }
            if (text.startsWith("ref('") && text.endsWith("')")) {
                return text;
            }
            String escaped = text.replace("\"", "\\\"");
            return "\"" + escaped + "\"";
        }
    }

    public record SqlModelRequest(
        UUID planId,
        String name,
        String alias,
        String layer,
        UUID sourceDataSourceId,
        String schemaName,
        String materialized,
        String tags,
        String description,
        String sql,
        Boolean enabled,
        String status,
        String ownerDept,
        String semanticContract
    ) {}

    public record SqlModelDto(
        UUID id,
        UUID planId,
        String planName,
        String name,
        String alias,
        String layer,
        UUID sourceDataSourceId,
        String sourceDataSourceName,
        String sourceSystem,
        String dagSelector,
        String tags,
        String materialized,
        String schemaName,
        String description,
        String sql,
        Boolean enabled,
        String modelPath,
        String ownerDept,
        String status,
        String semanticContract,
        String contractVersion,
        Instant contractUpdatedAt,
        int metricCount,
        int dimensionCount,
        Instant createdDate,
        Instant lastModifiedDate
    ) {}

    public record SqlModelContractImpact(
        UUID modelId,
        String modelName,
        String contractVersion,
        Instant contractUpdatedAt,
        int metricCount,
        int dimensionCount,
        int fieldCount,
        int impactedDatasetCount,
        int impactedReportCount,
        List<QueryDatasetImpactItem> impactedDatasets,
        List<ReportImpactItem> impactedReports
    ) {}

    public record QueryDatasetImpactItem(
        UUID id,
        String name,
        String status,
        Integer publishedVersion
    ) {}

    public record ReportImpactItem(
        UUID id,
        String title,
        String code,
        UUID queryDatasetId,
        boolean enabled
    ) {}

    private record ContractMeta(int metricCount, int dimensionCount) {}

    // ── Batch import records ──────────────────────────────────────────

    public record BatchImportResult(
        int total,
        int imported,
        int skipped,
        int failed,
        List<BatchImportDetail> details
    ) {}

    public record BatchImportDetail(
        String name,
        String layer,
        String status,    // "imported" | "skipped" | "validation_failed" | "write_failed"
        String message
    ) {}

    // ── Batch import from ZIP archive ─────────────────────────────────

    public BatchImportResult batchImportFromArchive(
        UUID planId,
        UUID defaultSourceDataSourceId,
        boolean skipExisting,
        Path archivePath,
        String activeDept
    ) {
        ensureWorkspaceWritable();
        Path tempDir = null;
        try {
            tempDir = Files.createTempDirectory("batch-import-unzip-");
            unzip(archivePath, tempDir);

            // Find the first .tsv file
            Path tsvFile = null;
            try (var stream = Files.walk(tempDir)) {
                tsvFile = stream
                    .filter(p -> p.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".tsv"))
                    .findFirst()
                    .orElse(null);
            }
            if (tsvFile == null) {
                throw new IllegalArgumentException("ZIP 压缩包中未找到 .tsv 清单文件");
            }

            Path tsvDir = tsvFile.getParent();
            List<String> lines = Files.readAllLines(tsvFile, StandardCharsets.UTF_8);
            List<BatchImportDetail> details = new ArrayList<>();
            int imported = 0;
            int skipped = 0;
            int failed = 0;

            for (String line : lines) {
                if (!StringUtils.hasText(line)) continue;
                String[] cols = line.split("\t", -1);
                if (cols.length == 0 || !StringUtils.hasText(cols[0])) continue;
                // Skip header row
                if ("name".equalsIgnoreCase(cols[0].trim())) continue;

                String name = cols[0].trim();
                String layer = cols.length > 1 ? cols[1].trim() : "";
                String sqlPath = cols.length > 2 ? cols[2].trim() : "";
                String sourceDataSourceIdStr = cols.length > 3 ? cols[3].trim() : "";
                String alias = cols.length > 4 ? cols[4].trim() : "";
                String schemaName = cols.length > 5 ? cols[5].trim() : "";
                String materialized = cols.length > 6 ? cols[6].trim() : "";
                String tags = cols.length > 7 ? cols[7].trim() : "";
                String status = cols.length > 8 ? cols[8].trim() : "";
                String enabledStr = cols.length > 9 ? cols[9].trim() : "";
                String ownerDept = cols.length > 10 ? cols[10].trim() : "";
                String description = cols.length > 11 ? cols[11].trim() : "";
                String csvPath = cols.length > 12 ? cols[12].trim() : "";

                try {
                    String validationError = validateBatchImportEntry(name, layer, sqlPath, materialized);
                    if (validationError != null) {
                        details.add(new BatchImportDetail(name, layer, "validation_failed", validationError));
                        failed++;
                        continue;
                    }

                    // Skip existing check
                    if (skipExisting && repo.findFirstByPlanIdAndNameIgnoreCase(planId, name).isPresent()) {
                        details.add(new BatchImportDetail(name, layer, "skipped", "同名模型已存在"));
                        skipped++;
                        continue;
                    }

                    // Resolve SQL file
                    Path sqlFile = resolveSidecarFile(tsvDir, tempDir, sqlPath, name, ".sql");
                    if (sqlFile == null || !Files.isRegularFile(sqlFile)) {
                        details.add(new BatchImportDetail(name, layer, "validation_failed", "找不到 SQL 文件: " + sqlPath));
                        failed++;
                        continue;
                    }
                    String sqlText = Files.readString(sqlFile, StandardCharsets.UTF_8);

                    // Resolve CSV file (optional)
                    String csvText = null;
                    if (StringUtils.hasText(csvPath)) {
                        Path csvFile = resolveSidecarFile(tsvDir, tempDir, csvPath, name, ".csv");
                        if (csvFile != null && Files.isRegularFile(csvFile)) {
                            csvText = Files.readString(csvFile, StandardCharsets.UTF_8);
                        }
                    }

                    // Resolve source data source id
                    UUID sourceId = defaultSourceDataSourceId;
                    if (StringUtils.hasText(sourceDataSourceIdStr)) {
                        try {
                            sourceId = UUID.fromString(sourceDataSourceIdStr);
                        } catch (IllegalArgumentException ignored) {
                            // use default
                        }
                    }

                    // Parse enabled
                    Boolean enabled = null;
                    if (StringUtils.hasText(enabledStr)) {
                        enabled = "true".equalsIgnoreCase(enabledStr) || "1".equals(enabledStr);
                    }

                    SqlModelRequest request = new SqlModelRequest(
                        planId,
                        name,
                        StringUtils.hasText(alias) ? alias : null,
                        layer,
                        sourceId,
                        StringUtils.hasText(schemaName) ? schemaName : null,
                        StringUtils.hasText(materialized) ? materialized : null,
                        StringUtils.hasText(tags) ? tags : null,
                        StringUtils.hasText(description) ? description : null,
                        sqlText,
                        enabled,
                        StringUtils.hasText(status) ? status : null,
                        StringUtils.hasText(ownerDept) ? ownerDept : null,
                        null
                    );
                    importFromFiles(request, sqlText, csvText, activeDept);
                    details.add(new BatchImportDetail(name, layer, "imported", null));
                    imported++;
                } catch (IllegalArgumentException ex) {
                    LOG.warn("[batch-import] validation failed for model '{}': {}", name, ex.getMessage());
                    details.add(new BatchImportDetail(name, layer, "validation_failed", ex.getMessage()));
                    failed++;
                } catch (Exception ex) {
                    LOG.warn("[batch-import] failed to import model '{}': {}", name, ex.getMessage(), ex);
                    details.add(new BatchImportDetail(name, layer, "write_failed", ex.getMessage()));
                    failed++;
                }
            }

            int total = imported + skipped + failed;
            return new BatchImportResult(total, imported, skipped, failed, details);
        } catch (IOException ex) {
            throw new RuntimeException("批量导入失败: " + ex.getMessage(), ex);
        } finally {
            if (tempDir != null) {
                try {
                    deleteRecursively(tempDir);
                } catch (IOException ignored) {
                    LOG.warn("[batch-import] failed to clean up temp dir: {}", tempDir);
                }
            }
        }
    }

    private String validateBatchImportEntry(String name, String layer, String sqlPath, String materialized) {
        if (!StringUtils.hasText(name)) {
            return "模型名称不能为空";
        }
        if (!MODEL_NAME_PATTERN.matcher(name).matches()) {
            return "模型名称仅允许字母/数字/下划线，且必须以字母开头";
        }
        if (!StringUtils.hasText(layer)) {
            return "模型分层不能为空";
        }
        if (!StringUtils.hasText(normalizeLayer(trimToNull(layer)))) {
            return "非法模型分层: " + layer;
        }
        if (!StringUtils.hasText(sqlPath)) {
            return "SQL 文件路径不能为空";
        }
        if (StringUtils.hasText(materialized)) {
            String normalized = materialized.trim().toLowerCase(Locale.ROOT);
            if (!Set.of("table", "view", "incremental").contains(normalized)) {
                return "非法物化方式: " + materialized;
            }
        }
        return null;
    }

    private Path resolveSidecarFile(Path tsvDir, Path unzipRoot, String relativePath, String modelName, String extension) {
        if (StringUtils.hasText(relativePath)) {
            Path resolved = tsvDir.resolve(relativePath).normalize();
            if (Files.isRegularFile(resolved)) return resolved;
            // Also try from unzip root
            resolved = unzipRoot.resolve(relativePath).normalize();
            if (Files.isRegularFile(resolved)) return resolved;
        }
        // Fallback: look for <name><extension> in unzip root
        Path fallback = unzipRoot.resolve(modelName + extension);
        if (Files.isRegularFile(fallback)) return fallback;
        // Also try in tsvDir
        fallback = tsvDir.resolve(modelName + extension);
        if (Files.isRegularFile(fallback)) return fallback;
        return null;
    }

    private void unzip(Path zipPath, Path destDir) throws IOException {
        try (var zis = new java.util.zip.ZipInputStream(Files.newInputStream(zipPath), StandardCharsets.UTF_8)) {
            java.util.zip.ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                Path target = destDir.resolve(entry.getName()).normalize();
                if (!target.startsWith(destDir)) {
                    throw new IOException("ZIP entry outside target dir: " + entry.getName());
                }
                if (entry.isDirectory()) {
                    Files.createDirectories(target);
                } else {
                    Files.createDirectories(target.getParent());
                    Files.copy(zis, target);
                }
                zis.closeEntry();
            }
        }
    }

    private void deleteRecursively(Path dir) throws IOException {
        if (dir == null || !Files.exists(dir)) return;
        try (var walk = Files.walk(dir)) {
            walk.sorted(Comparator.reverseOrder())
                .forEach(p -> {
                    try {
                        Files.deleteIfExists(p);
                    } catch (IOException ignored) {}
                });
        }
    }
}
