package com.yuzhi.dts.platform.service.modeling;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;

/** Deterministic compiler from the modeling contract to dbt project artifacts. */
public final class ModelingDbtCompiler {

    private ModelingDbtCompiler() {}

    public record CompiledArtifacts(String outputDirectory, Map<String, String> files) {}

    public static final class CompileException extends IllegalArgumentException {

        public CompileException(String message) {
            super(message);
        }
    }

    public static CompiledArtifacts compile(ModelingVNextContract.ModelSpec model) {
        validate(model);
        String name = model.name().trim();
        String layer = model.layer().name().toLowerCase();
        String outputDirectory = "models/" + layer + "/" + name + "/v" + model.revision();
        List<String> columns = selectedColumns(model);
        String sql = renderSql(model, columns);
        String schema = renderSchema(model, columns);
        String tests = renderTests(model);
        String docs = renderDocs(model, columns);
        return new CompiledArtifacts(
            outputDirectory,
            Map.of(
                name + ".sql", sql,
                name + ".yml", schema,
                name + ".tests.yml", tests,
                name + ".md", docs
            )
        );
    }

    private static void validate(ModelingVNextContract.ModelSpec model) {
        if (model == null) throw new CompileException("MODEL_REQUIRED");
        if (isBlank(model.name())) throw new CompileException("MODEL_NAME_REQUIRED");
        if (model.revision() < 1) throw new CompileException("REVISION_INVALID");
        if (model.grain() == null || isBlank(model.grain().statement()) || model.grain().keys() == null || model.grain().keys().stream().noneMatch(ModelingDbtCompiler::notBlank)) {
            throw new CompileException("GRAIN_REQUIRED");
        }
        if (model.sourceRefs() == null || model.sourceRefs().isEmpty()) throw new CompileException("SOURCE_REQUIRED");
        for (ModelingVNextContract.SourceRef source : model.sourceRefs()) {
            if (source == null || isBlank(source.ref()) || source.layer() == null) throw new CompileException("SOURCE_REFERENCE_INVALID");
            if (model.layer() != ModelingVNextContract.Layer.ODS && source.layer().ordinal() > model.layer().ordinal()) {
                throw new CompileException("SOURCE_LAYER_INVALID");
            }
        }
    }

    private static List<String> selectedColumns(ModelingVNextContract.ModelSpec model) {
        Set<String> columns = new LinkedHashSet<>();
        addNonBlank(columns, model.grain().keys());
        if (model.standardBindings() != null) {
            addNonBlank(columns, model.standardBindings().stream().filter(Objects::nonNull).map(ModelingVNextContract.StandardBinding::fieldName).toList());
        }
        addNonBlank(columns, model.dimensions());
        addNonBlank(columns, model.metrics());
        return List.copyOf(columns);
    }

    private static String renderSql(ModelingVNextContract.ModelSpec model, List<String> columns) {
        String sources = model.sourceRefs().stream().map(ModelingDbtCompiler::renderSource).collect(Collectors.joining("\n"));
        String select = columns.stream().map(column -> "    " + column).collect(Collectors.joining(",\n"));
        String from = model.sourceRefs().get(0).kind().equalsIgnoreCase("DBT_MODEL")
            ? "from {{ ref('" + model.sourceRefs().get(0).ref() + "') }}"
            : "from {{ source('" + sourceNamespace(model.sourceRefs().get(0)) + "', '" + sourceName(model.sourceRefs().get(0)) + "') }}";
        return "-- generated by DTS modeling vNext, revision " + model.revision() + "\n" + sources + "\nselect\n" + select + "\n" + from + "\n";
    }

    private static String renderSource(ModelingVNextContract.SourceRef source) {
        if (source.kind().equalsIgnoreCase("DBT_MODEL")) return "-- source: ref(" + source.ref() + ")";
        return "-- source: " + source.ref();
    }

    private static String renderSchema(ModelingVNextContract.ModelSpec model, List<String> columns) {
        StringBuilder yaml = new StringBuilder("version: 2\nmodels:\n  - name: ").append(model.name()).append("\n    description: \"").append(escape(model.grain().statement())).append("\"\n    columns:\n");
        for (String column : columns) {
            String standard = model.standardBindings() == null
                ? null
                : model.standardBindings().stream().filter(binding -> binding != null && column.equals(binding.fieldName())).map(ModelingVNextContract.StandardBinding::standardElementId).filter(ModelingDbtCompiler::notBlank).findFirst().orElse(null);
            yaml.append("      - name: ").append(column).append("\n        description: \"").append(escape(standard == null ? "模型字段" : "数据标准 " + standard)).append("\"\n");
            if (model.grain().keys().stream().anyMatch(key -> column.equals(key))) {
                yaml.append("        tests:\n          - not_null\n");
            }
        }
        return yaml.toString();
    }

    private static String renderTests(ModelingVNextContract.ModelSpec model) {
        String key = model.grain().keys().stream().filter(ModelingDbtCompiler::notBlank).findFirst().orElseThrow();
        return "version: 2\nmodels:\n  - name: " + model.name() + "\n    tests:\n      - unique:\n          column_name: " + key + "\n    columns:\n      - name: " + key + "\n        tests:\n          - not_null\n";
    }

    private static String renderDocs(ModelingVNextContract.ModelSpec model, List<String> columns) {
        return "# " + model.name() + "\n\n- 分层：" + model.layer() + "\n- 模型类型：" + model.modelType() + "\n- 业务粒度：" + model.grain().statement() + "\n- 字段：" + String.join(", ", columns) + "\n";
    }

    private static String sourceNamespace(ModelingVNextContract.SourceRef source) {
        String ref = source.ref();
        int separator = ref.indexOf('.');
        return separator > 0 ? ref.substring(0, separator) : "ods";
    }

    private static String sourceName(ModelingVNextContract.SourceRef source) {
        String ref = source.ref();
        int separator = ref.indexOf('.');
        return separator > 0 ? ref.substring(separator + 1) : ref;
    }

    private static void addNonBlank(Set<String> target, List<String> values) {
        if (values != null) values.stream().filter(ModelingDbtCompiler::notBlank).map(String::trim).forEach(target::add);
    }

    private static String escape(String value) {
        return value == null ? "" : value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static boolean notBlank(String value) {
        return !isBlank(value);
    }

    private static boolean isBlank(String value) {
        return value == null || value.isBlank();
    }
}
