package com.yuzhi.dts.platform.service.modeling;

import com.yuzhi.dts.platform.domain.modeling.ModelingSqlModel;
import com.yuzhi.dts.platform.domain.service.InfraDataSource;
import com.yuzhi.dts.platform.repository.modeling.ModelingSqlModelRepository;
import com.yuzhi.dts.platform.repository.service.InfraDataSourceRepository;
import com.yuzhi.dts.platform.service.etl.DbtConfigService;
import com.yuzhi.dts.platform.service.infra.AdminInfraClient;
import com.yuzhi.dts.platform.service.modeling.ModelingSqlModelService.SqlModelDto;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.FileVisitOption;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

/**
 * Handles all file-system I/O for dbt SQL model files:
 * writing/reading model SQL files, CSV sidecars, auto-quality YAML templates,
 * ZIP archive extraction, and path resolution with security checks.
 */
@Service
public class ModelFileService {

    private static final Logger LOG = LoggerFactory.getLogger(ModelFileService.class);
    private static final String AUTO_QUALITY_MARKER = "generated by dts-platform auto quality";
    private static final long MAX_ZIP_ENTRY_SIZE = 50 * 1024 * 1024; // 50 MB per file
    private static final long MAX_ZIP_TOTAL_SIZE = 200 * 1024 * 1024; // 200 MB total
    private static final int MAX_ZIP_ENTRIES = 2000;

    private final DbtConfigService dbtConfigService;
    private final ModelingSqlModelRepository repo;
    private final InfraDataSourceRepository dataSourceRepository;
    private final AdminInfraClient adminInfraClient;

    public ModelFileService(
        DbtConfigService dbtConfigService,
        ModelingSqlModelRepository repo,
        InfraDataSourceRepository dataSourceRepository,
        AdminInfraClient adminInfraClient
    ) {
        this.dbtConfigService = dbtConfigService;
        this.repo = repo;
        this.dataSourceRepository = dataSourceRepository;
        this.adminInfraClient = adminInfraClient;
    }

    public void writeModelFile(ModelingSqlModel model) {
        if (model == null) return;
        String projectDirStr = dbtConfigService.resolveProjectDir();
        if (!StringUtils.hasText(projectDirStr)) {
            throw new IllegalStateException("dbt projectDir 未配置，无法写入模型文件");
        }
        Path projectDir = Path.of(projectDirStr).normalize();
        Path targetPath = projectDir.resolve(model.getModelPath()).normalize();
        if (!targetPath.startsWith(projectDir)) {
            throw new IllegalStateException("模型文件目标路径非法: " + targetPath);
        }
        try {
            Files.createDirectories(targetPath.getParent());
            String sourceTag = resolveSourceTag(model.getSourceDataSourceId());
            String content = buildSqlContent(model, sourceTag);
            Files.writeString(targetPath, content, StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        } catch (IOException ex) {
            throw new IllegalStateException("写入模型文件失败: " + ex.getMessage(), ex);
        }
    }

    public void writeCsvSidecar(String modelPath, String csvText) {
        if (!StringUtils.hasText(modelPath) || !StringUtils.hasText(csvText)) {
            return;
        }
        String projectDirStr = dbtConfigService.resolveProjectDir();
        if (!StringUtils.hasText(projectDirStr)) {
            throw new IllegalStateException("dbt projectDir 未配置，无法写入 CSV 文件");
        }
        Path projectDir = Path.of(projectDirStr).normalize();
        Path sqlPath = projectDir.resolve(modelPath).normalize();
        if (!sqlPath.startsWith(projectDir)) {
            throw new IllegalStateException("CSV 目标路径非法: " + sqlPath);
        }
        String baseName = sqlPath.getFileName().toString();
        String csvName = baseName.endsWith(".sql") ? baseName.substring(0, baseName.length() - 4) + ".csv" : baseName + ".csv";
        Path csvPath = sqlPath.resolveSibling(csvName);
        try {
            Files.createDirectories(csvPath.getParent());
            Files.writeString(csvPath, csvText.trim() + "\n", StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        } catch (IOException ex) {
            throw new IllegalStateException("写入 CSV 文件失败: " + ex.getMessage(), ex);
        }
    }

    public void deleteFileIfChanged(String oldPath, String newPath) {
        if (!StringUtils.hasText(oldPath)) {
            return;
        }
        if (StringUtils.hasText(newPath) && oldPath.equals(newPath)) {
            return;
        }
        String projectDirStr = dbtConfigService.resolveProjectDir();
        if (!StringUtils.hasText(projectDirStr)) {
            return;
        }
        Path projectDir = Path.of(projectDirStr).normalize();
        Path targetPath = projectDir.resolve(oldPath).normalize();
        if (!targetPath.startsWith(projectDir)) {
            return;
        }
        try {
            Files.deleteIfExists(targetPath);
            deleteCompanionFile(targetPath.resolveSibling(replaceExtension(targetPath.getFileName(), ".csv")), false);
            deleteCompanionFile(targetPath.resolveSibling(replaceExtension(targetPath.getFileName(), ".yml")), true);
        } catch (IOException ex) {
            LOG.warn("[dbt-model] failed to delete {}: {}", targetPath, ex.getMessage());
        }
    }

    public boolean canDeleteModelPathAfterRemoving(String modelPath, Set<UUID> removingIds) {
        String normalizedPath = trimToNull(modelPath);
        if (!StringUtils.hasText(normalizedPath)) {
            return false;
        }
        return repo
            .findByModelPathIn(List.of(normalizedPath))
            .stream()
            .filter(model -> model != null && StringUtils.hasText(model.getModelPath()))
            .filter(model -> normalizedPath.equals(model.getModelPath()))
            .filter(model -> model.getId() == null || removingIds == null || !removingIds.contains(model.getId()))
            .findAny()
            .isEmpty();
    }

    /**
     * Write auto-quality YAML template for a generated model.
     * Returns null on success, or a warning message if skipped.
     */
    public String writeAutoQualityTemplate(SqlModelDto model, List<ColumnProfile> sourceColumns, UUID planId) {
        if (model == null || !StringUtils.hasText(model.modelPath()) || !StringUtils.hasText(model.name())) {
            return "模型信息不完整";
        }
        if (sourceColumns == null || sourceColumns.isEmpty()) {
            return model.name() + " (无法推断字段，跳过质量模板生成)";
        }
        String projectDirStr = dbtConfigService.resolveProjectDir();
        if (!StringUtils.hasText(projectDirStr)) {
            return model.name() + " (dbt projectDir 未配置)";
        }
        Path projectDir = Path.of(projectDirStr).normalize();
        Path sqlPath = projectDir.resolve(model.modelPath()).normalize();
        if (!sqlPath.startsWith(projectDir)) {
            return model.name() + " (模型路径不在项目目录内)";
        }
        String baseName = sqlPath.getFileName() == null ? null : sqlPath.getFileName().toString();
        if (!StringUtils.hasText(baseName)) {
            return model.name() + " (无法解析模型文件名)";
        }
        String ymlName = baseName.endsWith(".sql") ? baseName.substring(0, baseName.length() - 4) + ".yml" : baseName + ".yml";
        Path ymlPath = sqlPath.resolveSibling(ymlName).normalize();
        if (!ymlPath.startsWith(projectDir)) {
            return model.name() + " (质量模板路径非法)";
        }
        try {
            if (Files.exists(ymlPath)) {
                String existing = Files.readString(ymlPath, StandardCharsets.UTF_8);
                if (StringUtils.hasText(existing) && !existing.contains(AUTO_QUALITY_MARKER)) {
                    return model.name() + " (已存在手工 yml，未覆盖)";
                }
            }
            Files.createDirectories(ymlPath.getParent());
            String content = buildAutoQualityYaml(model, sourceColumns, planId);
            Files.writeString(ymlPath, content, StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
            return null;
        } catch (IOException ex) {
            return model.name() + " (写入质量模板失败: " + ex.getMessage() + ")";
        }
    }

    // ── ZIP operations ─────────────────────────────────────────────────

    public void unzip(Path zipPath, Path destDir) throws IOException {
        try (var zis = new java.util.zip.ZipInputStream(Files.newInputStream(zipPath), StandardCharsets.UTF_8)) {
            java.util.zip.ZipEntry entry;
            long totalSize = 0;
            int entryCount = 0;
            while ((entry = zis.getNextEntry()) != null) {
                if (++entryCount > MAX_ZIP_ENTRIES) {
                    throw new IOException("ZIP archive contains too many entries (max " + MAX_ZIP_ENTRIES + ")");
                }
                String entryName = entry.getName();
                if (entryName.contains("..") || entryName.startsWith("/")) {
                    throw new IOException("ZIP entry has suspicious path: " + entryName);
                }
                Path target = destDir.resolve(entryName).normalize();
                if (!target.startsWith(destDir)) {
                    throw new IOException("ZIP entry outside target dir: " + entryName);
                }
                if (entry.isDirectory()) {
                    Files.createDirectories(target);
                } else {
                    long entrySize = entry.getSize();
                    if (entrySize > MAX_ZIP_ENTRY_SIZE) {
                        throw new IOException("ZIP entry too large: " + entryName + " (" + entrySize + " bytes)");
                    }
                    Files.createDirectories(target.getParent());
                    try (var out = Files.newOutputStream(target)) {
                        byte[] buf = new byte[8192];
                        long written = 0;
                        int len;
                        while ((len = zis.read(buf)) > 0) {
                            written += len;
                            if (written > MAX_ZIP_ENTRY_SIZE) {
                                throw new IOException("ZIP entry exceeds size limit during extraction: " + entryName);
                            }
                            out.write(buf, 0, len);
                        }
                        totalSize += written;
                    }
                    if (totalSize > MAX_ZIP_TOTAL_SIZE) {
                        throw new IOException("ZIP archive total extraction size exceeds limit (" + MAX_ZIP_TOTAL_SIZE / (1024 * 1024) + " MB)");
                    }
                    if (Files.isSymbolicLink(target)) {
                        Files.deleteIfExists(target);
                        throw new IOException("ZIP entry resolved to symlink: " + entryName);
                    }
                }
                zis.closeEntry();
            }
        }
    }

    public void deleteRecursively(Path dir) throws IOException {
        if (dir == null || !Files.exists(dir)) return;
        try (var walk = Files.walk(dir)) {
            walk.sorted(Comparator.reverseOrder())
                .forEach(p -> {
                    try {
                        Files.deleteIfExists(p);
                    } catch (IOException ignored) {}
                });
        }
    }

    public Path resolveSidecarFile(Path tsvDir, Path unzipRoot, String relativePath, String modelName, String extension) {
        if (StringUtils.hasText(relativePath)) {
            Path resolved = tsvDir.resolve(relativePath).normalize();
            if (Files.isRegularFile(resolved)) return resolved;
            resolved = unzipRoot.resolve(relativePath).normalize();
            if (Files.isRegularFile(resolved)) return resolved;
        }
        Path fallback = unzipRoot.resolve(modelName + extension);
        if (Files.isRegularFile(fallback)) return fallback;
        fallback = tsvDir.resolve(modelName + extension);
        if (Files.isRegularFile(fallback)) return fallback;
        return null;
    }

    public void copyWorkspaceCompanionFiles(Path unzipRoot) throws IOException {
        String projectDirStr = dbtConfigService.resolveProjectDir();
        if (!StringUtils.hasText(projectDirStr)) {
            return;
        }
        Path projectDir = Path.of(projectDirStr).normalize();
        if (!Files.exists(projectDir)) {
            return;
        }
        try (var walk = Files.walk(unzipRoot)) {
            for (Path file : walk.filter(Files::isRegularFile).toList()) {
                String relative = resolveCompanionWorkspacePath(unzipRoot.relativize(file));
                if (!StringUtils.hasText(relative)) {
                    continue;
                }
                Path target = projectDir.resolve(relative).normalize();
                if (!target.startsWith(projectDir)) {
                    throw new IOException("companion file outside workspace: " + relative);
                }
                Files.createDirectories(target.getParent());
                Files.copy(file, target, StandardCopyOption.REPLACE_EXISTING);
            }
        }
    }

    // ── Internal helpers ───────────────────────────────────────────────

    private String resolveCompanionWorkspacePath(Path relativePath) {
        if (relativePath == null) {
            return null;
        }
        String normalized = relativePath.toString().replace('\\', '/');
        String lower = normalized.toLowerCase(Locale.ROOT);
        int modelsIndex = lower.indexOf("models/");
        if (modelsIndex >= 0 && (lower.endsWith(".yml") || lower.endsWith(".yaml"))) {
            return normalized.substring(modelsIndex);
        }
        int macrosIndex = lower.indexOf("macros/");
        if (macrosIndex >= 0 && lower.endsWith(".sql")) {
            return normalized.substring(macrosIndex);
        }
        int seedsIndex = lower.indexOf("seeds/");
        if (seedsIndex >= 0 && (lower.endsWith(".csv") || lower.endsWith(".tsv"))) {
            return normalized.substring(seedsIndex);
        }
        return null;
    }

    private void deleteCompanionFile(Path path, boolean autoGeneratedOnly) {
        if (path == null || !Files.exists(path)) {
            return;
        }
        try {
            if (autoGeneratedOnly) {
                String content = Files.readString(path, StandardCharsets.UTF_8);
                if (!StringUtils.hasText(content) || !content.contains(AUTO_QUALITY_MARKER)) {
                    return;
                }
            }
            Files.deleteIfExists(path);
        } catch (IOException ex) {
            LOG.warn("[dbt-model] failed to delete companion file {}: {}", path, ex.getMessage());
        }
    }

    private Path replaceExtension(Path fileName, String replacement) {
        if (fileName == null) {
            return null;
        }
        String baseName = fileName.toString();
        int dotIndex = baseName.lastIndexOf('.');
        String stem = dotIndex >= 0 ? baseName.substring(0, dotIndex) : baseName;
        return Path.of(stem + replacement);
    }

    String buildSqlContent(ModelingSqlModel model, String sourceTag) {
        String body = trimToEmpty(model.getSqlText());
        if (body.contains("{{ config") || body.contains("{{config")) {
            return body + "\n";
        }
        String configLine = buildConfigLine(model, sourceTag);
        if (!StringUtils.hasText(configLine)) {
            return body + "\n";
        }
        return configLine + "\n\n" + body + "\n";
    }

    private String buildConfigLine(ModelingSqlModel model, String sourceTag) {
        List<String> configs = new ArrayList<>();
        if (StringUtils.hasText(model.getMaterialized())) {
            configs.add("materialized='" + model.getMaterialized() + "'");
        }
        if (StringUtils.hasText(model.getAlias())) {
            configs.add("alias='" + model.getAlias() + "'");
        }
        String layerTag = ModelingSqlModelService.sanitizeTag(ModelingSqlModelService.normalizeLayer(model.getLayer()), null);
        List<String> tags = ModelingSqlModelService.splitTags(model.getTags(), sourceTag, layerTag);
        if (!tags.isEmpty()) {
            String rendered = tags.stream().map(tag -> "'" + tag + "'").reduce((a, b) -> a + ", " + b).orElse("");
            configs.add("tags=[" + rendered + "]");
        }
        if (configs.isEmpty()) {
            return "";
        }
        return "{{ config(" + String.join(", ", configs) + ") }}";
    }

    private String resolveSourceTag(UUID sourceId) {
        if (sourceId == null) return null;
        InfraDataSource source = resolveSourceEntity(sourceId).orElse(null);
        if (source == null) return null;
        return ModelingSqlModelService.sanitizeTag(ModelingSqlModelService.resolveSourceKey(source), ModelingSqlModelService.slugify(source.getName()));
    }

    private Optional<InfraDataSource> resolveSourceEntity(UUID sourceId) {
        if (sourceId == null) {
            return Optional.empty();
        }
        InfraDataSource local = dataSourceRepository.findById(sourceId).orElse(null);
        if (local != null) {
            return Optional.of(local);
        }
        return adminInfraClient.fetchDefaultDataLake().filter(lake -> sourceId.equals(lake.getId())).map(ModelingSqlModelService::toVirtualSource);
    }

    private String buildAutoQualityYaml(SqlModelDto model, List<ColumnProfile> sourceColumns, UUID planId) {
        String modelName = model.name();
        String pkColumn = detectPrimaryKey(modelName, sourceColumns);
        Map<String, String> relationTargets = inferRelationshipTargets(sourceColumns, pkColumn, planId);

        List<Map<String, Object>> columns = new ArrayList<>();
        for (ColumnProfile column : sourceColumns) {
            if (!StringUtils.hasText(column.name())) {
                continue;
            }
            List<Object> tests = new ArrayList<>();
            if (isNotNullColumn(column, pkColumn)) {
                tests.add("not_null");
            }
            if (StringUtils.hasText(pkColumn) && pkColumn.equalsIgnoreCase(column.name())) {
                tests.add("unique");
            }
            String relationModel = relationTargets.get(column.name().toLowerCase(Locale.ROOT));
            if (StringUtils.hasText(relationModel)) {
                Map<String, Object> relation = new LinkedHashMap<>();
                relation.put("to", "ref('" + relationModel + "')");
                relation.put("field", column.name());
                tests.add(Map.of("relationships", relation));
            }

            Map<String, Object> meta = new LinkedHashMap<>();
            if (StringUtils.hasText(column.dataType())) {
                meta.put("expected_data_type", column.dataType());
            }
            if (StringUtils.hasText(column.standardId())) {
                meta.put("standard_id", column.standardId());
            }
            if (StringUtils.hasText(column.standardRule())) {
                meta.put("standard_rule", column.standardRule());
            }

            Map<String, Object> columnYaml = new LinkedHashMap<>();
            columnYaml.put("name", column.name());
            columnYaml.put("description", defaultText(column.comment(), ""));
            if (!tests.isEmpty()) {
                columnYaml.put("tests", tests);
            }
            if (!meta.isEmpty()) {
                columnYaml.put("meta", meta);
            }
            columns.add(columnYaml);
        }

        Map<String, Object> modelMeta = new LinkedHashMap<>();
        modelMeta.put("auto_quality", true);
        modelMeta.put("generated_by", "dts-platform");
        modelMeta.put("generator_version", "v2");
        modelMeta.put("updated_at", Instant.now().toString());

        Map<String, Object> modelNode = new LinkedHashMap<>();
        modelNode.put("name", modelName);
        modelNode.put("description", defaultText(trimToNull(model.description()), model.layer() + " 自动生成模型"));
        modelNode.put("meta", modelMeta);
        modelNode.put("columns", columns);

        Map<String, Object> root = new LinkedHashMap<>();
        root.put("version", 2);
        root.put("models", List.of(modelNode));

        StringBuilder yaml = new StringBuilder();
        yaml.append("# ").append(AUTO_QUALITY_MARKER).append("\n");
        yaml.append("# generated_at: ").append(Instant.now().toString()).append("\n");
        yaml.append(AutoYamlWriter.toYaml(root));
        return yaml.toString();
    }

    private String detectPrimaryKey(String modelName, List<ColumnProfile> columns) {
        if (columns == null || columns.isEmpty()) {
            return null;
        }
        Set<String> names = new LinkedHashSet<>();
        for (ColumnProfile column : columns) {
            names.add(column.name().toLowerCase(Locale.ROOT));
        }
        String entity = modelName;
        if (StringUtils.hasText(entity)) {
            entity = entity.toLowerCase(Locale.ROOT);
            entity = entity.replaceFirst("^(ods_|dwd_|dws_|ads_)", "");
            String preferred = entity + "_id";
            if (names.contains(preferred)) {
                return preferred;
            }
        }
        if (names.contains("id")) {
            return "id";
        }
        for (ColumnProfile column : columns) {
            String name = column.name().toLowerCase(Locale.ROOT);
            if (name.endsWith("_id")) {
                return name;
            }
        }
        return null;
    }

    private Map<String, String> inferRelationshipTargets(List<ColumnProfile> columns, String pkColumn, UUID planId) {
        if (columns == null || columns.isEmpty() || planId == null) {
            return Map.of();
        }
        List<com.yuzhi.dts.platform.domain.modeling.ModelingSqlModel> planModels = repo.findByPlanId(planId);
        if (planModels == null || planModels.isEmpty()) {
            return Map.of();
        }
        Set<String> modelNames = new LinkedHashSet<>();
        for (com.yuzhi.dts.platform.domain.modeling.ModelingSqlModel m : planModels) {
            if (m != null && StringUtils.hasText(m.getName())) {
                modelNames.add(m.getName().trim().toLowerCase(Locale.ROOT));
            }
        }
        if (modelNames.isEmpty()) {
            return Map.of();
        }
        Map<String, String> relations = new LinkedHashMap<>();
        for (ColumnProfile column : columns) {
            String name = column.name().toLowerCase(Locale.ROOT);
            if (!name.endsWith("_id")) {
                continue;
            }
            if (StringUtils.hasText(pkColumn) && name.equalsIgnoreCase(pkColumn)) {
                continue;
            }
            String token = name.substring(0, name.length() - 3);
            if (!StringUtils.hasText(token)) {
                continue;
            }
            String target = findRelationshipTargetModel(token, modelNames);
            if (target != null) {
                relations.put(name, target);
            }
        }
        return relations;
    }

    private String findRelationshipTargetModel(String token, Set<String> modelNames) {
        List<String> candidates = List.of("dim_" + token, "dwd_" + token, "dws_" + token, "ads_" + token);
        for (String candidate : candidates) {
            if (modelNames.contains(candidate)) {
                return candidate;
            }
        }
        return null;
    }

    private boolean isNotNullColumn(ColumnProfile column, String pkColumn) {
        if (column == null || !StringUtils.hasText(column.name())) {
            return false;
        }
        String name = column.name().toLowerCase(Locale.ROOT);
        if (StringUtils.hasText(pkColumn) && pkColumn.equalsIgnoreCase(name)) {
            return true;
        }
        if ("source_system".equals(name) || "import_time".equals(name)) {
            return true;
        }
        return Boolean.FALSE.equals(column.nullable());
    }

    // ── Shared record ──────────────────────────────────────────────────

    public record ColumnProfile(
        String name,
        String dataType,
        Boolean nullable,
        String comment,
        String standardId,
        String standardRule
    ) {}

    // ── AutoYamlWriter (static inner class) ────────────────────────────

    static final class AutoYamlWriter {
        static String toYaml(Map<String, Object> root) {
            StringBuilder sb = new StringBuilder();
            writeMap(sb, root, 0);
            return sb.toString();
        }

        @SuppressWarnings("unchecked")
        private static void writeMap(StringBuilder sb, Map<String, Object> map, int indent) {
            String prefix = " ".repeat(Math.max(0, indent));
            for (Map.Entry<String, Object> entry : map.entrySet()) {
                sb.append(prefix).append(entry.getKey()).append(":");
                Object value = entry.getValue();
                if (value instanceof Map<?, ?> nested) {
                    sb.append("\n");
                    writeMap(sb, (Map<String, Object>) nested, indent + 2);
                } else if (value instanceof List<?> list) {
                    sb.append("\n");
                    writeList(sb, list, indent + 2);
                } else {
                    sb.append(" ").append(scalar(value)).append("\n");
                }
            }
        }

        @SuppressWarnings("unchecked")
        private static void writeList(StringBuilder sb, List<?> list, int indent) {
            String prefix = " ".repeat(Math.max(0, indent));
            for (Object item : list) {
                sb.append(prefix).append("-");
                if (item instanceof Map<?, ?> nested) {
                    sb.append("\n");
                    writeMap(sb, (Map<String, Object>) nested, indent + 2);
                } else if (item instanceof List<?> nestedList) {
                    sb.append("\n");
                    writeList(sb, nestedList, indent + 2);
                } else {
                    sb.append(" ").append(scalar(item)).append("\n");
                }
            }
        }

        private static String scalar(Object value) {
            if (value == null) {
                return "\"\"";
            }
            if (value instanceof Number || value instanceof Boolean) {
                return value.toString();
            }
            String text = String.valueOf(value);
            if (text.isEmpty()) {
                return "\"\"";
            }
            if (text.startsWith("ref('") && text.endsWith("')")) {
                return text;
            }
            String escaped = text.replace("\"", "\\\"");
            return "\"" + escaped + "\"";
        }
    }

    // ── String utilities ───────────────────────────────────────────────

    private String trimToNull(String value) {
        if (!StringUtils.hasText(value)) return null;
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

    private String trimToEmpty(String value) {
        return value == null ? "" : value.trim();
    }

    private String defaultText(String value, String fallback) {
        return StringUtils.hasText(value) ? value : fallback;
    }
}
