export const MODEL_TYPES = [
  { id: "dimension", label: "维度表", hint: "描述业务分析视角，支持被多个事实模型复用" },
  { id: "detail", label: "明细表", hint: "记录一个业务过程中的原子事实" },
  { id: "summary", label: "汇总表", hint: "按固定时间周期与维度汇总原子指标" },
  { id: "application", label: "应用表", hint: "面向具体应用场景组织可消费指标" },
];

export const LAYERS = [
  { id: "ODS", label: "贴源层", color: "slate", description: "保留来源结构，不承载业务加工" },
  { id: "DWD", label: "明细层", color: "cyan", description: "沉淀标准化明细事实与公共维度" },
  { id: "DWS", label: "汇总层", color: "violet", description: "按一致粒度组织公共汇总结果" },
  { id: "ADS", label: "应用层", color: "orange", description: "面向业务场景提供可消费数据" },
  { id: "DIM", label: "公共维度层", color: "green", description: "统一维护可复用的维度实体" },
];

export const MOCK_PROJECT_SPACES = [
  {
    id: "project-metro",
    name: "Metro",
    domain: "地铁域",
    owner: "王敏",
    ownerDept: "项目管理部",
    status: "DRAFT",
    version: "v1",
    scope: "地铁项目计划、节点执行与风险释放",
    description: "以 Metro 项目空间为边界，管理节点计划执行和交付风险。",
    count: 6,
    standardsReady: 6,
  },
  {
    id: "project-rent",
    name: "租赁",
    domain: "租赁域",
    owner: "陈默",
    ownerDept: "经营分析部",
    status: "DRAFT",
    version: "v1",
    scope: "租赁合同、收款与客户经营分析",
    description: "以租赁项目空间为边界，沉淀合同和经营指标模型。",
    count: 4,
    standardsReady: 4,
  },
  {
    id: "project-finance-test1",
    name: "财务test1",
    domain: "财务域",
    owner: "林峰",
    ownerDept: "财务部",
    status: "DRAFT",
    version: "v1",
    scope: "财务核算与预算执行",
    description: "用于验证财务域模型、标准和发布流程。",
    count: 3,
    standardsReady: 3,
  },
  {
    id: "project-management-1",
    name: "项目空间1",
    domain: "项目管理域",
    owner: "赵宁",
    ownerDept: "PMO",
    status: "DRAFT",
    version: "v1",
    scope: "项目进度、交付和资源管理",
    description: "项目管理域的通用建模空间。",
    count: 2,
    standardsReady: 2,
  },
];

export const MOCK_PROCESSES = MOCK_PROJECT_SPACES;

export const MOCK_STANDARDS = [
  { id: "std-project-id", code: "project_id", name: "项目ID", type: "BIGINT", length: "-", precision: "-", nullable: false, defaultValue: "-", category: "标识", status: "已发布" },
  { id: "std-node-id", code: "node_id", name: "节点ID", type: "BIGINT", length: "-", precision: "-", nullable: false, defaultValue: "-", category: "标识", status: "已发布" },
  { id: "std-plan-version", code: "plan_version", name: "计划版本", type: "VARCHAR", length: "32", precision: "-", nullable: false, defaultValue: "v1", category: "编码", status: "已发布" },
  { id: "std-execution-status", code: "execution_status", name: "执行状态", type: "VARCHAR", length: "16", precision: "-", nullable: false, defaultValue: "PLANNED", category: "标准代码", status: "已发布" },
  { id: "std-complete-rate", code: "complete_rate", name: "完成率", type: "DECIMAL", length: "8", precision: "4", nullable: true, defaultValue: "0", category: "度量", unit: "%", status: "已发布" },
  { id: "std-snapshot-date", code: "snapshot_date", name: "快照日期", type: "DATE", length: "-", precision: "-", nullable: false, defaultValue: "-", category: "时间", status: "已发布" },
];

export const MOCK_DATASETS = [
  {
    id: "ds-node-plan",
    projectId: "project-metro",
    name: "project_node_plan",
    label: "项目节点计划",
    source: "mysql · pjm",
    freshness: "12 分钟前",
    columns: 18,
    quality: 98,
  },
  {
    id: "ds-quality-issue",
    projectId: "project-rent",
    name: "quality_issue_event",
    label: "质量问题事件",
    source: "postgres · quality",
    freshness: "28 分钟前",
    columns: 14,
    quality: 96,
  },
];

export const MOCK_DIMENSIONS = [
  {
    id: "dim-project",
    code: "project",
    name: "项目维度",
    sourceModel: "dim_project",
    domain: "项目管理域",
    keys: ["project_id"],
    attributes: 12,
    status: "已登记",
  },
  {
    id: "dim-node-type",
    code: "node_type",
    name: "节点类型维度",
    sourceModel: "dim_node_type",
    domain: "项目管理域",
    keys: ["node_type_code"],
    attributes: 6,
    status: "已登记",
  },
  {
    id: "dim-date",
    code: "date",
    name: "日期维度",
    sourceModel: "dim_date",
    domain: "公共维度",
    keys: ["date_id"],
    attributes: 9,
    status: "已登记",
  },
  {
    id: "dim-risk-level",
    code: "risk_level",
    name: "风险等级维度",
    sourceModel: "dim_risk_level",
    domain: "风险域",
    keys: ["risk_level_code"],
    attributes: 4,
    status: "已登记",
  },
];

export const MOCK_MODELS = [
  {
    id: "model-node-plan-detail",
    name: "节点计划执行明细",
    code: "dwd_node_plan_execution",
    type: "detail",
    layer: "DWD",
    processId: "project-metro",
    projectId: "project-metro",
    projectName: "Metro",
    projectDomain: "地铁域",
    processName: "Metro",
    domain: "地铁域",
    status: "published",
    version: "v1.2.0",
    updatedAt: "今天 09:42",
    owner: "王敏",
    quality: 98,
    fieldCount: 16,
    standardCount: 6,
    grain: "一行代表一个项目节点在一个计划版本下的执行记录",
  },
  {
    id: "model-project-dim",
    name: "项目维度",
    code: "dim_project",
    type: "dimension",
    layer: "DIM",
    processId: "project-metro",
    projectId: "project-metro",
    projectName: "Metro",
    projectDomain: "地铁域",
    processName: "Metro",
    domain: "地铁域",
    status: "published",
    version: "v2.0.1",
    updatedAt: "昨天 16:20",
    owner: "陈默",
    quality: 100,
    fieldCount: 12,
    standardCount: 6,
    grain: "一行代表一个项目实体的当前有效版本",
  },
  {
    id: "model-quality-summary",
    name: "质量问题周汇总",
    code: "dws_quality_issue_weekly",
    type: "summary",
    layer: "DWS",
    processId: "project-rent",
    projectId: "project-rent",
    projectName: "租赁",
    projectDomain: "租赁域",
    processName: "租赁",
    domain: "租赁域",
    status: "draft",
    version: "草稿",
    updatedAt: "昨天 11:06",
    owner: "林峰",
    quality: 91,
    fieldCount: 9,
    standardCount: 4,
    grain: "一行代表一个项目、问题分类、周的质量统计",
  },
];

export const DEFAULT_FIELDS = [
  { id: "field-project", name: "project_id", label: "项目ID", type: "BIGINT", role: "key", standard: "项目ID", required: true },
  { id: "field-node", name: "node_id", label: "节点ID", type: "BIGINT", role: "key", standard: "节点ID", required: true },
  { id: "field-version", name: "plan_version", label: "计划版本", type: "VARCHAR(32)", role: "attribute", standard: "计划版本", required: true },
  { id: "field-status", name: "execution_status", label: "执行状态", type: "VARCHAR(16)", role: "attribute", standard: "执行状态", required: true },
  { id: "field-complete-rate", name: "complete_rate", label: "完成率", type: "DECIMAL(8,4)", role: "measure", standard: "完成率", required: false },
  { id: "field-date", name: "snapshot_date", label: "快照日期", type: "DATE", role: "partition", standard: "快照日期", required: true },
];

export const DEFAULT_RELATIONS = [
  { id: "rel-project", targetId: "dim-project", targetModel: "dim_project", type: "many-to-one", on: "project_id = project_id", status: "valid" },
  { id: "rel-node-type", targetId: "dim-node-type", targetModel: "dim_node_type", type: "many-to-one", on: "node_type_code = node_type_code", status: "valid" },
  { id: "rel-date", targetId: "dim-date", targetModel: "dim_date", type: "many-to-one", on: "snapshot_date = date_id", status: "valid" },
];

export const MOCK_MODEL = {
  id: "draft-node-plan",
  name: "节点计划执行明细",
  code: "dwd_node_plan_execution",
  description: "记录项目节点在不同计划版本下的执行状态与完成率。",
  processId: "project-metro",
  projectId: "project-metro",
  projectName: "Metro",
  projectDomain: "地铁域",
  layer: "DWD",
  modelType: "detail",
  datasetId: "ds-node-plan",
  standardBindings: ["std-project-id", "std-node-id", "std-plan-version", "std-execution-status", "std-complete-rate", "std-snapshot-date"],
  fields: DEFAULT_FIELDS,
  grainStatement: "一行代表一个项目节点在一个计划版本下的执行记录",
  grainKeys: ["project_id", "node_id", "plan_version"],
  dimensions: ["dim-project", "dim-node-type", "dim-date"],
  relations: DEFAULT_RELATIONS,
  savedAt: null,
  version: "草稿",
  status: "draft",
};
