window.PROTOTYPE_DATA = {
  modelTypes: {
    dimension: {
      group: "概念模型",
      label: "创建维度",
      layer: "公共层 / 维度层",
      toolbar: ["保存"],
      fields: [
        ["数仓分层", "公共层 / 维度层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["数据域", "财务域", "select", true],
        ["英文缩写", "budget_account", "input", true],
        ["中文名称", "预算科目", "input", true],
        ["描述", "财务预算分析使用的统一预算科目。", "textarea"],
      ],
    },
    source: {
      group: "逻辑模型",
      label: "创建贴源表",
      layer: "贴源层",
      toolbar: ["保存", "提交", "刷新", "发布", "日志", "质量规则", "模型开发", "导出"],
      fields: [
        ["数仓分层", "贴源层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["存储策略", "默认存储策略", "select"],
        ["表名规则", "ODS 表命名规范", "select"],
        ["表名", "ods_budget_execution", "input", true],
        ["表中文名", "预算执行导入表", "input", true],
        ["生命周期", "365", "number"],
        ["负责人", "xzmfly", "select", true],
        ["描述", "离线 Excel 导入的预算执行原始数据。", "textarea"],
      ],
    },
    "dimension-table": {
      group: "逻辑模型",
      label: "创建维度表",
      layer: "公共层 / 维度层",
      toolbar: ["保存", "提交", "刷新", "关联关系", "发布", "日志", "质量规则", "模型开发", "导出"],
      fields: [
        ["数仓分层", "公共层 / 维度层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["数据域", "财务域", "select", true],
        ["存储策略", "默认存储策略", "select"],
        ["维度", "预算科目", "select", true],
        ["表名规则", "DIM 表命名规范", "select"],
        ["表名", "dim_budget_account", "input", true],
        ["表中文名", "预算科目维度表", "input", true],
        ["生命周期", "长期", "input"],
        ["负责人", "xzmfly", "select", true],
        ["描述", "统一维护预算科目编码、名称、类别及状态。", "textarea"],
      ],
    },
    fact: {
      group: "逻辑模型",
      label: "创建明细表",
      layer: "公共层 / 明细层",
      toolbar: ["保存", "提交", "刷新", "关联关系", "发布", "日志", "质量规则", "模型开发", "导出"],
      fields: [
        ["数仓分层", "公共层 / 明细层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["业务过程", "预算执行", "select", true],
        ["存储策略", "默认存储策略", "select"],
        ["表名规则", "DWD 表命名规范", "select"],
        ["表名", "fct_budget_execution", "input", true],
        ["表中文名", "预算执行明细表", "input", true],
        ["生命周期", "1095", "number"],
        ["负责人", "xzmfly", "select", true],
        ["描述", "一个预算执行事项一行，记录预算、预付、成本与应付金额。", "textarea"],
      ],
    },
    aggregate: {
      group: "逻辑模型",
      label: "创建汇总表",
      layer: "公共层 / 汇总层",
      toolbar: ["保存", "提交", "刷新", "关联关系", "发布", "日志", "质量规则", "模型开发", "导出"],
      fields: [
        ["数仓分层", "公共层 / 汇总层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["数据域", "财务域", "select", true],
        ["统计粒度", "项目 + 预算科目 + 月", "select", true],
        ["统计周期", "月", "select", true],
        ["修饰词", "累计", "select"],
        ["表名规则", "DWS 表命名规范", "select"],
        ["表名", "agg_budget_monthly", "input", true],
        ["表中文名", "月度预算执行汇总表", "input", true],
        ["生命周期", "1095", "number"],
        ["负责人", "xzmfly", "select", true],
        ["描述", "按项目、预算科目和月份汇总预算执行金额。", "textarea"],
      ],
    },
    application: {
      group: "逻辑模型",
      label: "创建应用表",
      layer: "应用层",
      toolbar: ["保存", "提交", "刷新", "关联关系", "发布", "日志", "质量规则", "模型开发", "导出"],
      fields: [
        ["数仓分层", "应用层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["主题域", "预算驾驶舱", "select", true],
        ["统计粒度", "项目 + 月", "select", true],
        ["统计周期", "月", "select", true],
        ["修饰词", "累计", "select"],
        ["表名规则", "ADS 表命名规范", "select"],
        ["表名", "app_budget_dashboard", "input", true],
        ["表中文名", "预算驾驶舱应用表", "input", true],
        ["生命周期", "1095", "number"],
        ["负责人", "xzmfly", "select", true],
        ["描述", "面向预算驾驶舱的发布数据集。", "textarea"],
      ],
    },
  },
  domains: [
    {
      name: "财务域",
      count: 5,
      nodes: [
        ["dimension-table", "dim_fin_date", "财务日期维度表"],
        ["dimension-table", "dim_budget_account", "预算科目维度表"],
        ["fact", "fct_budget_execution", "预算执行明细表"],
        ["aggregate", "agg_budget_monthly", "月度预算执行汇总表"],
        ["application", "app_budget_dashboard", "预算驾驶舱应用表"],
      ],
    },
    {
      name: "项目域",
      count: 4,
      nodes: [
        ["dimension-table", "dim_project", "项目维度表"],
        ["dimension-table", "dim_department", "责任部门维度表"],
        ["fact", "fct_project_milestone", "项目节点明细表"],
        ["aggregate", "agg_project_weekly", "项目周进展汇总表"],
      ],
    },
  ],
  fields: {
    "dimension-table": [
      ["account_code", "STRING", "科目编码", true, true, "ACCOUNT_CODE"],
      ["account_name", "STRING", "科目名称", false, true, "ACCOUNT_NAME"],
      ["account_category", "STRING", "科目类别", false, false, "ACCOUNT_CATEGORY"],
      ["enabled_flag", "BOOLEAN", "是否启用", false, true, "ENABLED_FLAG"],
    ],
    source: [
      ["project_no", "STRING", "项目号", false, false, ""],
      ["budget_no", "STRING", "预算编号", false, false, ""],
      ["budget_amount_adjusted", "DECIMAL(18,2)", "调整后预算金额", false, false, ""],
      ["_dts_import_time", "TIMESTAMP", "导入时间", false, false, ""],
    ],
    fact: [
      ["budget_execution_id", "BIGINT", "预算执行主键", true, true, ""],
      ["date_key", "INT", "财务日期键", false, true, "DATE_KEY"],
      ["account_code", "STRING", "预算科目编码", false, true, "ACCOUNT_CODE"],
      ["project_no", "STRING", "项目号", false, true, "PROJECT_NO"],
      ["budget_amount", "DECIMAL(18,2)", "预算金额", false, false, ""],
      ["book_cost_amount", "DECIMAL(18,2)", "账面成本", false, false, ""],
    ],
    aggregate: [
      ["month_key", "INT", "月份键", true, true, ""],
      ["project_no", "STRING", "项目号", true, true, "PROJECT_NO"],
      ["account_code", "STRING", "预算科目编码", true, true, "ACCOUNT_CODE"],
      ["budget_amount", "DECIMAL(18,2)", "预算金额", false, false, ""],
      ["execution_rate", "DECIMAL(9,4)", "预算执行率", false, false, ""],
    ],
    application: [
      ["month_key", "INT", "月份键", true, true, ""],
      ["project_no", "STRING", "项目号", true, true, "PROJECT_NO"],
      ["budget_amount", "DECIMAL(18,2)", "预算金额", false, false, ""],
      ["executed_amount", "DECIMAL(18,2)", "已执行金额", false, false, ""],
      ["execution_rate", "DECIMAL(9,4)", "预算执行率", false, false, ""],
    ],
  },
  planning: {
    nav: [
      ["业务板块", 2],
      ["数据域", 2],
      ["业务过程", 4],
      ["维度", 5],
      ["业务限定", 3],
      ["统计周期", 4],
    ],
    domains: [
      ["财务域", "FINANCE", "财务管理", "预算、成本与资金执行分析", "xzmfly", "已发布"],
      ["项目域", "PROJECT", "项目管理", "节点、风险、质量与物料协同", "xzmfly", "草稿"],
    ],
    processes: [
      ["预算编制", "BUDGET_PLAN", "财务域", "预算计划形成", "已发布"],
      ["预算执行", "BUDGET_EXECUTION", "财务域", "预算执行与成本确认", "已发布"],
      ["节点跟踪", "MILESTONE_TRACKING", "项目域", "项目节点计划与完成跟踪", "草稿"],
      ["风险闭环", "RISK_CLOSURE", "项目域", "风险识别、跟进与释放", "草稿"],
    ],
  },
  standards: {
    nav: [
      ["字段标准", 12],
      ["标准代码", 7],
      ["词根", 18],
      ["命名词典", 9],
      ["标准映射", 6],
    ],
    rows: [
      ["ACCOUNT_CODE", "科目编码", "STRING", "预算科目的唯一业务编码", "财务管理", "v1", "已生效"],
      ["DATE_KEY", "日期键", "INT", "格式为 YYYYMMDD 的日期业务键", "公共标准", "v1", "已生效"],
      ["PROJECT_NO", "项目编号", "STRING", "项目全生命周期唯一编号", "项目管理", "v2", "已生效"],
      ["AMOUNT", "金额", "DECIMAL(18,2)", "以人民币元记录的含税金额", "财务管理", "v1", "草稿"],
      ["ENABLED_FLAG", "启用标志", "BOOLEAN", "记录业务对象当前是否有效", "公共标准", "v1", "已生效"],
    ],
  },
  metrics: {
    nav: [
      ["复合指标", 2],
      ["派生指标", 5],
      ["原子指标", 6],
      ["修饰词", 4],
      ["时间周期", 4],
    ],
    catalog: {
      原子指标: [
        ["默认", "budget_amount", "预算金额"],
        ["财务域", "executed_amount", "已执行金额"],
        ["财务域", "payable_amount", "应付金额"],
        ["项目域", "milestone_count", "节点数量"],
      ],
      派生指标: [
        ["财务域", "monthly_execution_rate", "月度预算执行率"],
        ["财务域", "project_budget_variance", "项目预算偏差"],
        ["项目域", "weekly_completion_rate", "周节点完成率"],
      ],
      复合指标: [
        ["财务域", "budget_health_score", "预算健康度"],
        ["项目域", "project_health_score", "项目健康度"],
      ],
      修饰词: [
        ["默认", "current", "当期"],
        ["默认", "cumulative", "累计"],
        ["默认", "year_on_year", "同比"],
        ["默认", "month_on_month", "环比"],
      ],
      时间周期: [
        ["默认", "day", "日"],
        ["默认", "week", "周"],
        ["默认", "month", "月"],
        ["默认", "year", "年"],
      ],
    },
    rows: [
      ["budget_amount", "预算金额", "原子指标", "预算执行", "SUM(budget_amount)", "已发布"],
      ["executed_amount", "已执行金额", "原子指标", "预算执行", "SUM(book_cost_amount)", "已发布"],
      ["monthly_execution_rate", "月度预算执行率", "派生指标", "月", "已执行金额 / 预算金额", "已发布"],
      ["project_budget_variance", "项目预算偏差", "派生指标", "项目", "预算金额 - 已执行金额", "草稿"],
      ["budget_health_score", "预算健康度", "复合指标", "项目 + 月", "执行率、偏差与进度综合评分", "草稿"],
    ],
  },
  tools: [
    ["模型批量导入", "Excel", "通过模板批量创建维度、模型和字段定义", "导入"],
    ["模型批量导出", "Export", "按数据域或模型类型导出当前逻辑设计", "导出"],
    ["FML 校验器", "FML", "校验模型代码的语法、命名及引用关系", "打开"],
    ["表名检查器", "Name", "统一验证 ODS、DIM、DWD、DWS、ADS 表命名", "配置"],
    ["数据字典", "Dict", "汇总维度、字段标准、指标及模型关系", "查看"],
    ["Excel 字段识别", "Excel", "预览离线 Excel 并生成贴源表字段草稿", "识别"],
  ],
};
