window.PROTOTYPE_DATA = {
  modelTypes: {
    dimension: {
      group: "概念模型",
      label: "创建维度",
      layer: "公共层 / 维度层",
      toolbar: ["保存"],
      fields: [
        ["数仓分层", "公共层 / 维度层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["数据域", "财务域", "select", true],
        ["英文缩写", "budget_account", "input", true],
        ["中文名称", "预算科目", "input", true],
        ["描述", "财务预算分析使用的统一预算科目。", "textarea"],
      ],
    },
    source: {
      group: "逻辑模型",
      label: "创建贴源表",
      layer: "贴源层",
      toolbar: ["保存", "提交", "刷新", "发布", "日志", "质量规则", "模型开发", "导出"],
      fields: [
        ["数仓分层", "贴源层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["存储策略", "默认存储策略", "select"],
        ["表名规则", "ODS 表命名规范", "select"],
        ["表名", "ods_budget_execution", "input", true],
        ["表中文名", "预算执行导入表", "input", true],
        ["生命周期", "365", "number"],
        ["负责人", "xzmfly", "select", true],
        ["描述", "离线 Excel 导入的预算执行原始数据。", "textarea"],
      ],
    },
    "dimension-table": {
      group: "逻辑模型",
      label: "创建维度表",
      layer: "公共层 / 维度层",
      toolbar: ["保存", "提交", "刷新", "关联关系", "发布", "日志", "质量规则", "模型开发", "导出"],
      fields: [
        ["数仓分层", "公共层 / 维度层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["数据域", "财务域", "select", true],
        ["存储策略", "默认存储策略", "select"],
        ["维度", "预算科目", "select", true],
        ["表名规则", "DIM 表命名规范", "select"],
        ["表名", "dim_budget_account", "input", true],
        ["表中文名", "预算科目维度表", "input", true],
        ["生命周期", "长期", "input"],
        ["负责人", "xzmfly", "select", true],
        ["描述", "统一维护预算科目编码、名称、类别及状态。", "textarea"],
      ],
    },
    fact: {
      group: "逻辑模型",
      label: "创建明细表",
      layer: "公共层 / 明细层",
      toolbar: ["保存", "提交", "刷新", "关联关系", "发布", "日志", "质量规则", "模型开发", "导出"],
      fields: [
        ["数仓分层", "公共层 / 明细层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["业务过程", "预算执行", "select", true],
        ["存储策略", "默认存储策略", "select"],
        ["表名规则", "DWD 表命名规范", "select"],
        ["表名", "fct_budget_execution", "input", true],
        ["表中文名", "预算执行明细表", "input", true],
        ["生命周期", "1095", "number"],
        ["负责人", "xzmfly", "select", true],
        ["描述", "一个预算执行事项一行，记录预算、预付、成本与应付金额。", "textarea"],
      ],
    },
    aggregate: {
      group: "逻辑模型",
      label: "创建汇总表",
      layer: "公共层 / 汇总层",
      toolbar: ["保存", "提交", "刷新", "关联关系", "发布", "日志", "质量规则", "模型开发", "导出"],
      fields: [
        ["数仓分层", "公共层 / 汇总层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["数据域", "财务域", "select", true],
        ["统计粒度", "项目 + 预算科目 + 月", "select", true],
        ["统计周期", "月", "select", true],
        ["修饰词", "累计", "select"],
        ["表名规则", "DWS 表命名规范", "select"],
        ["表名", "agg_budget_monthly", "input", true],
        ["表中文名", "月度预算执行汇总表", "input", true],
        ["生命周期", "1095", "number"],
        ["负责人", "xzmfly", "select", true],
        ["描述", "按项目、预算科目和月份汇总预算执行金额。", "textarea"],
      ],
    },
    application: {
      group: "逻辑模型",
      label: "创建应用表",
      layer: "应用层",
      toolbar: ["保存", "提交", "刷新", "关联关系", "发布", "日志", "质量规则", "模型开发", "导出"],
      fields: [
        ["数仓分层", "应用层", "select", true],
        ["业务分类", "财务管理", "select"],
        ["主题域", "预算驾驶舱", "select", true],
        ["统计粒度", "项目 + 月", "select", true],
        ["统计周期", "月", "select", true],
        ["修饰词", "累计", "select"],
        ["表名规则", "ADS 表命名规范", "select"],
        ["表名", "app_budget_dashboard", "input", true],
        ["表中文名", "预算驾驶舱应用表", "input", true],
        ["生命周期", "1095", "number"],
        ["负责人", "xzmfly", "select", true],
        ["描述", "面向预算驾驶舱的发布数据集。", "textarea"],
      ],
    },
  },
  domains: [
    {
      name: "财务域",
      count: 5,
      nodes: [
        ["dimension-table", "dim_fin_date", "财务日期维度表"],
        ["dimension-table", "dim_budget_account", "预算科目维度表"],
        ["fact", "fct_budget_execution", "预算执行明细表"],
        ["aggregate", "agg_budget_monthly", "月度预算执行汇总表"],
        ["application", "app_budget_dashboard", "预算驾驶舱应用表"],
      ],
    },
    {
      name: "项目域",
      count: 4,
      nodes: [
        ["dimension-table", "dim_project", "项目维度表"],
        ["dimension-table", "dim_department", "责任部门维度表"],
        ["fact", "fct_project_milestone", "项目节点明细表"],
        ["aggregate", "agg_project_weekly", "项目周进展汇总表"],
      ],
    },
  ],
  fields: {
    "dimension-table": [
      ["account_code", "STRING", "科目编码", true, true, "ACCOUNT_CODE"],
      ["account_name", "STRING", "科目名称", false, true, "ACCOUNT_NAME"],
      ["account_category", "STRING", "科目类别", false, false, "ACCOUNT_CATEGORY"],
      ["enabled_flag", "BOOLEAN", "是否启用", false, true, "ENABLED_FLAG"],
    ],
    source: [
      ["project_no", "STRING", "项目号", false, false, ""],
      ["budget_no", "STRING", "预算编号", false, false, ""],
      ["budget_amount_adjusted", "DECIMAL(18,2)", "调整后预算金额", false, false, ""],
      ["_dts_import_time", "TIMESTAMP", "导入时间", false, false, ""],
    ],
    fact: [
      ["budget_execution_id", "BIGINT", "预算执行主键", true, true, ""],
      ["date_key", "INT", "财务日期键", false, true, "DATE_KEY"],
      ["account_code", "STRING", "预算科目编码", false, true, "ACCOUNT_CODE"],
      ["project_no", "STRING", "项目号", false, true, "PROJECT_NO"],
      ["budget_amount", "DECIMAL(18,2)", "预算金额", false, false, ""],
      ["book_cost_amount", "DECIMAL(18,2)", "账面成本", false, false, ""],
    ],
    aggregate: [
      ["month_key", "INT", "月份键", true, true, ""],
      ["project_no", "STRING", "项目号", true, true, "PROJECT_NO"],
      ["account_code", "STRING", "预算科目编码", true, true, "ACCOUNT_CODE"],
      ["budget_amount", "DECIMAL(18,2)", "预算金额", false, false, ""],
      ["execution_rate", "DECIMAL(9,4)", "预算执行率", false, false, ""],
    ],
    application: [
      ["month_key", "INT", "月份键", true, true, ""],
      ["project_no", "STRING", "项目号", true, true, "PROJECT_NO"],
      ["budget_amount", "DECIMAL(18,2)", "预算金额", false, false, ""],
      ["executed_amount", "DECIMAL(18,2)", "已执行金额", false, false, ""],
      ["execution_rate", "DECIMAL(9,4)", "预算执行率", false, false, ""],
    ],
  },
};
