import type { ComponentCategory } from './types';

export const componentLibrary: ComponentCategory[] = [
    {
        name: '图表',
        icon: '📊',
        items: [
            {
                type: 'line-chart',
                name: '折线图',
                icon: '📈',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    title: '折线图',
                    xAxisData: ['一月', '二月', '三月', '四月', '五月', '六月'],
                    series: [
                        { name: '系列1', data: [120, 200, 150, 80, 70, 110] },
                    ],
                },
            },
            {
                type: 'bar-chart',
                name: '柱状图',
                icon: '📊',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    title: '柱状图',
                    xAxisData: ['一月', '二月', '三月', '四月', '五月', '六月'],
                    series: [
                        { name: '系列1', data: [120, 200, 150, 80, 70, 110] },
                    ],
                },
            },
            {
                type: 'pie-chart',
                name: '饼图',
                icon: '🥧',
                defaultWidth: 350,
                defaultHeight: 300,
                defaultConfig: {
                    title: '饼图',
                    data: [
                        { name: '类别A', value: 335 },
                        { name: '类别B', value: 310 },
                        { name: '类别C', value: 234 },
                        { name: '类别D', value: 135 },
                        { name: '类别E', value: 154 },
                    ],
                },
            },
            {
                type: 'gauge-chart',
                name: '仪表盘',
                icon: '🎯',
                defaultWidth: 300,
                defaultHeight: 300,
                defaultConfig: {
                    title: '完成率',
                    value: 75,
                    min: 0,
                    max: 100,
                },
            },
            {
                type: 'radar-chart',
                name: '雷达图',
                icon: '🕸️',
                defaultWidth: 350,
                defaultHeight: 300,
                defaultConfig: {
                    title: '雷达图',
                    indicator: [
                        { name: '销售', max: 6500 },
                        { name: '管理', max: 16000 },
                        { name: '技术', max: 30000 },
                        { name: '客服', max: 38000 },
                        { name: '研发', max: 52000 },
                    ],
                    data: [4300, 10000, 28000, 35000, 50000],
                },
            },
            {
                type: 'funnel-chart',
                name: '漏斗图',
                icon: '🔽',
                defaultWidth: 350,
                defaultHeight: 300,
                defaultConfig: {
                    title: '漏斗图',
                    data: [
                        { name: '访问', value: 100 },
                        { name: '咨询', value: 80 },
                        { name: '订单', value: 60 },
                        { name: '点击', value: 40 },
                        { name: '展现', value: 20 },
                    ],
                },
            },
            {
                type: 'scatter-chart',
                name: '散点图',
                icon: '⚫',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    title: '散点图',
                    data: [
                        [10, 8.04], [8, 6.95], [13, 7.58], [9, 8.81], [11, 8.33],
                        [14, 9.96], [6, 7.24], [4, 4.26], [12, 10.84], [7, 4.82],
                    ],
                },
            },
            {
                type: 'map-chart',
                name: '区域地图',
                icon: '🗺️',
                defaultWidth: 520,
                defaultHeight: 320,
                defaultConfig: {
                    title: '区域分布',
                    mapScope: 'china',
                    enableRegionDrill: true,
                    regions: [
                        {
                            name: '华北',
                            value: 120,
                            children: [
                                { name: '北京', value: 40 },
                                { name: '天津', value: 25 },
                                { name: '河北', value: 55 },
                            ],
                        },
                        {
                            name: '华东',
                            value: 180,
                            children: [
                                { name: '上海', value: 70 },
                                { name: '江苏', value: 60 },
                                { name: '浙江', value: 50 },
                            ],
                        },
                        {
                            name: '华南',
                            value: 140,
                            children: [
                                { name: '广东', value: 90 },
                                { name: '福建', value: 30 },
                                { name: '海南', value: 20 },
                            ],
                        },
                    ],
                },
            },
        ],
    },
    {
        name: '边框',
        icon: '🔲',
        items: [
            {
                type: 'border-box',
                name: '边框1',
                icon: '🔲',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 1,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框2',
                icon: '🔳',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 2,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框3',
                icon: '🔲',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 3,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框4',
                icon: '🔳',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 4,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框5',
                icon: '🔲',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 5,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框6',
                icon: '🔳',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 6,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框7',
                icon: '🔲',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 7,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'border-box',
                name: '边框8',
                icon: '🔳',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    boxType: 8,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
        ],
    },
    {
        name: '装饰',
        icon: '✨',
        items: [
            {
                type: 'decoration',
                name: '装饰1',
                icon: '💠',
                defaultWidth: 200,
                defaultHeight: 60,
                defaultConfig: {
                    decorationType: 1,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰2',
                icon: '💎',
                defaultWidth: 200,
                defaultHeight: 60,
                defaultConfig: {
                    decorationType: 2,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰3',
                icon: '✨',
                defaultWidth: 250,
                defaultHeight: 40,
                defaultConfig: {
                    decorationType: 3,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰4',
                icon: '⭐',
                defaultWidth: 200,
                defaultHeight: 60,
                defaultConfig: {
                    decorationType: 4,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰5',
                icon: '🌟',
                defaultWidth: 300,
                defaultHeight: 50,
                defaultConfig: {
                    decorationType: 5,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰6',
                icon: '💫',
                defaultWidth: 300,
                defaultHeight: 40,
                defaultConfig: {
                    decorationType: 6,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰8',
                icon: '🔷',
                defaultWidth: 300,
                defaultHeight: 60,
                defaultConfig: {
                    decorationType: 8,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
            {
                type: 'decoration',
                name: '装饰10',
                icon: '🔶',
                defaultWidth: 200,
                defaultHeight: 60,
                defaultConfig: {
                    decorationType: 10,
                    color: ['#6586ec', '#2cf7fe'],
                },
            },
        ],
    },
    {
        name: '数据展示',
        icon: '📋',
        items: [
            {
                type: 'number-card',
                name: '指标卡',
                icon: '🔢',
                defaultWidth: 200,
                defaultHeight: 120,
                defaultConfig: {
                    title: '总销售额',
                    value: 128456,
                    prefix: '¥',
                    suffix: '',
                    precision: 0,
                },
            },
            {
                type: 'scroll-board',
                name: '轮播表',
                icon: '📜',
                defaultWidth: 400,
                defaultHeight: 250,
                defaultConfig: {
                    header: ['列1', '列2', '列3'],
                    data: [
                        ['行1-1', '行1-2', '行1-3'],
                        ['行2-1', '行2-2', '行2-3'],
                        ['行3-1', '行3-2', '行3-3'],
                        ['行4-1', '行4-2', '行4-3'],
                        ['行5-1', '行5-2', '行5-3'],
                    ],
                    rowNum: 5,
                    headerBGC: '#00BAFF',
                    oddRowBGC: '#0A2732',
                    evenRowBGC: '#003B51',
                    waitTime: 2000,
                },
            },
            {
                type: 'table',
                name: '数据表',
                icon: '🗂️',
                defaultWidth: 480,
                defaultHeight: 280,
                defaultConfig: {
                    header: ['列1', '列2', '列3'],
                    data: [
                        ['行1-1', '行1-2', '行1-3'],
                        ['行2-1', '行2-2', '行2-3'],
                        ['行3-1', '行3-2', '行3-3'],
                    ],
                    headerColor: '#e5e7eb',
                    headerBackground: '#64748b',
                    bodyColor: '#d1d5db',
                    bodyBackground: 'transparent',
                    borderColor: '#94a3b8',
                    fontSize: 13,
                },
            },
            {
                type: 'scroll-ranking',
                name: '排行榜',
                icon: '🏆',
                defaultWidth: 300,
                defaultHeight: 250,
                defaultConfig: {
                    data: [
                        { name: '周口', value: 55 },
                        { name: '南阳', value: 120 },
                        { name: '西峡', value: 78 },
                        { name: '驻马店', value: 66 },
                        { name: '新乡', value: 80 },
                    ],
                    rowNum: 5,
                    waitTime: 2000,
                },
            },
            {
                type: 'water-level',
                name: '水位图',
                icon: '💧',
                defaultWidth: 200,
                defaultHeight: 200,
                defaultConfig: {
                    value: 65,
                    shape: 'round',
                },
            },
            {
                type: 'digital-flop',
                name: '数字翻牌',
                icon: '🔄',
                defaultWidth: 200,
                defaultHeight: 80,
                defaultConfig: {
                    number: [100],
                    content: '{nt}',
                    style: {
                        fontSize: 30,
                        fill: '#3de7c9',
                    },
                },
            },
            {
                type: 'percent-pond',
                name: '进度池',
                icon: '📊',
                defaultWidth: 200,
                defaultHeight: 100,
                defaultConfig: {
                    value: 66,
                    borderWidth: 3,
                    borderRadius: 5,
                    colors: ['#3de7c9', '#00baff'],
                },
            },
            {
                type: 'progress-bar',
                name: '进度条',
                icon: '📏',
                defaultWidth: 300,
                defaultHeight: 40,
                defaultConfig: {
                    value: 75,
                    showLabel: true,
                },
            },
        ],
    },
    {
        name: '文本',
        icon: '📝',
        items: [
            {
                type: 'title',
                name: '标题',
                icon: '🔤',
                defaultWidth: 300,
                defaultHeight: 60,
                defaultConfig: {
                    text: '大屏标题',
                    fontSize: 32,
                    fontWeight: 'bold',
                    color: '#ffffff',
                    textAlign: 'center',
                },
            },
            {
                type: 'datetime',
                name: '日期时间',
                icon: '🕐',
                defaultWidth: 200,
                defaultHeight: 40,
                defaultConfig: {
                    format: 'YYYY-MM-DD HH:mm:ss',
                    fontSize: 16,
                    color: '#ffffff',
                },
            },
            {
                type: 'markdown-text',
                name: 'Markdown',
                icon: '📄',
                defaultWidth: 420,
                defaultHeight: 220,
                defaultConfig: {
                    markdown: '# 标题\n\n- 要点 1\n- 要点 2\n\n[查看详情](https://example.com)',
                    fontSize: 14,
                    color: '#e2e8f0',
                    lineHeight: 1.6,
                },
            },
            {
                type: 'marquee',
                name: '跑马灯',
                icon: '📢',
                defaultWidth: 420,
                defaultHeight: 56,
                defaultConfig: {
                    text: 'DTS 实时播报：数据接入稳定，任务运行正常，模型服务在线。',
                    speed: 40,
                    color: '#e2e8f0',
                    fontSize: 15,
                    backgroundColor: 'rgba(15,23,42,0.45)',
                },
            },
            {
                type: 'countdown',
                name: '倒计时',
                icon: '⏳',
                defaultWidth: 320,
                defaultHeight: 88,
                defaultConfig: {
                    title: '发布倒计时',
                    targetTime: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
                    showDays: true,
                    color: '#e2e8f0',
                    accentColor: '#22d3ee',
                },
            },
        ],
    },
    {
        name: '形状容器',
        icon: '⬛',
        items: [
            {
                type: 'shape',
                name: '基础形状',
                icon: '🔷',
                defaultWidth: 240,
                defaultHeight: 140,
                defaultConfig: {
                    shapeType: 'rect',
                    fillColor: 'rgba(59, 130, 246, 0.2)',
                    borderColor: '#60a5fa',
                    borderWidth: 2,
                    radius: 8,
                },
            },
            {
                type: 'container',
                name: '容器框',
                icon: '🗂️',
                defaultWidth: 520,
                defaultHeight: 320,
                defaultConfig: {
                    title: '业务容器',
                    backgroundColor: 'rgba(15, 23, 42, 0.35)',
                    borderColor: 'rgba(148, 163, 184, 0.35)',
                    borderWidth: 1,
                    radius: 10,
                    titleColor: '#e2e8f0',
                    padding: 12,
                },
            },
        ],
    },
    {
        name: '筛选器',
        icon: '🎛️',
        items: [
            {
                type: 'filter-input',
                name: '输入筛选',
                icon: '⌨️',
                defaultWidth: 260,
                defaultHeight: 54,
                defaultConfig: {
                    label: '关键词',
                    variableKey: 'keyword',
                    placeholder: '请输入关键词',
                },
            },
            {
                type: 'filter-select',
                name: '下拉筛选',
                icon: '🔽',
                defaultWidth: 260,
                defaultHeight: 54,
                defaultConfig: {
                    label: '地区',
                    variableKey: 'region',
                    options: ['华北', '华东', '华南'],
                    placeholder: '请选择地区',
                },
            },
            {
                type: 'filter-date-range',
                name: '日期筛选',
                icon: '📅',
                defaultWidth: 320,
                defaultHeight: 72,
                defaultConfig: {
                    label: '日期区间',
                    startKey: 'startDate',
                    endKey: 'endDate',
                },
            },
        ],
    },
    {
        name: '媒体',
        icon: '🖼️',
        items: [
            {
                type: 'image',
                name: '图片',
                icon: '🖼️',
                defaultWidth: 300,
                defaultHeight: 200,
                defaultConfig: {
                    src: '',
                    fit: 'cover',
                },
            },
            {
                type: 'video',
                name: '视频',
                icon: '🎬',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    src: '',
                    autoplay: true,
                    loop: true,
                    muted: true,
                },
            },
            {
                type: 'iframe',
                name: 'iframe',
                icon: '🌐',
                defaultWidth: 400,
                defaultHeight: 300,
                defaultConfig: {
                    src: '',
                },
            },
        ],
    },
];
